bluesky-social/atproto

.github/workflows/cli.yaml, .github/workflows/common.yaml, .github/workflows/server.yaml
Set up basic CI:
- run `yarn test` in server and common
- run `yarn build` in common in order to run server tests
- run `yarn build` in server and cli 
Tests are passing on my branch: https://github.com/harlantwood/adx/actions?query=branch%3Aci
=> Github actions: run tests and builds

packages/README.md, packages/auth/README.md, packages/common/README.md, packages/crypto/README.md, packages/dev-env/README.md, packages/did-sdk/README.md, packages/repo/README.md, packages/server/README.md
Initial progress for documenting the codebase. Adds readmes to the package folder and to some of the packages that don't have them yet. (No real substance yet.)
=> Add some readmes

packages/nsid/.eslintignore, packages/nsid/README.md, packages/nsid/babel.config.js, packages/nsid/jest.config.js, packages/nsid/package.json, packages/nsid/src/index.ts, packages/nsid/tests/nsid.test.js, packages/nsid/tsconfig.build.json, packages/nsid/tsconfig.json, tsconfig.json
=> Add NSID package

packages/auth/package.json, packages/crypto/package.json, yarn.lock
Finally got version `0.11.0` out of alpha & published 🎉
=> Bump ucans to stable version

packages/dev-env/build.js, packages/dev-env/src/index.ts, packages/dev-env/src/mock/index.ts, packages/dev-env/src/types.ts, packages/server/build.js
Adds PLC server to dev-env.
Only allows one at a time & makes it a requirement to start up any PDSs
=> Add PLC server to dev-env

packages/dev-env/build.js, packages/dev-env/package.json, packages/server/build.js
Fixing a regressing to the dev-env's build introduced in #216.
=> Fix dev-env build, account for server's hbs templates

packages/dev-env/build.js
Fyi @devinivy I think this is the correct fix (at least, this is what worked for me)
=> Fix the external better-sqlite3 path in dev-env build

packages/auth/package.json, packages/cli/package.json, packages/common/package.json, packages/crypto/package.json, packages/dev-env/package.json, packages/did-resolver/package.json, packages/plc/package.json, packages/repo/package.json
=> MIT license

packages/lex-cli/src/mdgen/index.ts
Just some small improvements to how we generate docs
=> A couple improvements to the markdown generator to improve clarity

lexicons/app/bsky/actor/getUsersSearch.json, lexicons/app/bsky/actor/getUsersTypeahead.json, lexicons/app/bsky/actor/updateProfile.json, lexicons/app/bsky/feed/getAuthorFeed.json, lexicons/app/bsky/feed/getTimeline.json, lexicons/app/bsky/graph/follow.json, lexicons/app/bsky/notification/updateSeen.json, lexicons/com/atproto/account/requestPasswordReset.json, lexicons/com/atproto/account/resetPassword.json, lexicons/com/atproto/repo/createRecord.json, lexicons/com/atproto/repo/putRecord.json, lexicons/com/atproto/sync/getRepo.json
Done for docs consistency across files.
=> Added full stop to descriptions

lexicons/app/bsky/feed/setVote.json, packages/api/src/client/index.ts, packages/api/src/client/schemas.ts, packages/api/src/client/types/app/bsky/feed/setVote.ts, packages/api/src/client/types/com/atproto/repo/putRecord.ts, packages/pds/src/api/app/bsky/feed/setVote.ts, packages/pds/src/api/app/bsky/index.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/schemas.ts, packages/pds/src/lexicon/types/app/bsky/feed/setVote.ts, packages/pds/src/lexicon/types/com/atproto/repo/putRecord.ts, packages/pds/src/util/repo.ts, packages/pds/tests/views/votes.test.ts
Implements `app.bsky.feed.setVote()` so that we can transactionally switch between the three vote states that a user may have for a post: up, down, or none.  A switch from an upvote to a downvote, for example, requires deleting then adding a record in the user's repo.
I decided to mirror `post.myState` in the output from `setVote()`, so it looks something like `{ upvote?: uri, downvote?: uri }`.
=> Implement `setVote()` method

lexicons/app/bsky/feed/trend.json, lexicons/app/bsky/notification/list.json, packages/api/src/client/index.ts, packages/api/src/client/schemas.ts, packages/api/src/client/types/app/bsky/feed/trend.ts, packages/pds/src/db/database-schema.ts, packages/pds/src/db/index.ts, packages/pds/src/db/migrations/20221021T162202001Z-init.ts, packages/pds/src/db/records/trend.ts, packages/pds/src/db/types.ts, packages/pds/src/lexicon/schemas.ts, packages/pds/src/lexicon/types/app/bsky/feed/trend.ts
Schema & indexing for trend records
=> Trend schemas

packages/pds/src/db/records/confirmation.ts
=> Add missing execute() to confirmation delete

packages/pds/src/db/migrations/20221116T234458063Z-duplicate-records.ts
~this is best practice. but it's hanging for me 🧐~
~just keeping it here for safe keeping~
lol silly me figured it out
=> Tx migration

packages/pds/src/db/records/post.ts
Closes https://github.com/bluesky-social/atproto/issues/356
=> Don't give notifications for mentions & replies to self

packages/pds/src/db/record-processor.ts
=> Fix unclear indexedAt in processor

packages/pds/src/api/app/bsky/feed/getPostThread.ts, packages/pds/tests/views/__snapshots__/thread.test.ts.snap, packages/pds/tests/views/thread.test.ts
Recurses up thread to return ancestors
=> Return post ancestors

lexicons/app/bsky/actor/profile.json, lexicons/com/atproto/data/uploadFile.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/com/atproto/data/uploadFile.ts, packages/common/src/streams.ts, packages/pds/src/image/server.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/com/atproto/data/uploadFile.ts, packages/pds/src/repo/blobs.ts, packages/pds/src/repo/prepare.ts, packages/pds/src/storage/memory-blobstore.ts
- Fix byte streaming from mem blobstore
- Enlarge avatar max size to 300kb
- Treat empty files as "not found" in the cache (happens on errors during initial processing)
=> Various blob fixes

packages/common/src/streams.ts, packages/pds/src/index.ts, packages/pds/tests/file-uploads.test.ts, packages/xrpc-server/package.json, packages/xrpc-server/src/server.ts, packages/xrpc-server/src/types.ts, packages/xrpc-server/src/util.ts, packages/xrpc-server/tests/bodies.test.ts, packages/xrpc-server/tests/procedures.test.ts
Allow raw payloads to be sent compressed to xrpc-server.
=> Support compression in requests to xrpc-server

packages/pds/src/image/uri.ts, packages/pds/tests/views/__snapshots__/profile.test.ts.snap
Small fix to profile banner size: height and width were mixed-up! 🙃
=> Fix size/url for profile banner

packages/xrpc-server/README.md, packages/xrpc/README.md
* addSchema => addLexicon
* update lexicons for new defs.main structure
* update server ping method implementation to match XRPCHandler type signature
Hi all! First off, I know this is all under active development on your side. Hope you don't mind this PR. Should hopefully be straightforward and non-controversial, but if triaging it is more pain that it's worth, feel free to ignore it.
I've been writing my own Lexicon/XRPC implementation, https://github.com/snarfed/lexrpc , purely for fun, as part of a bigger project. I tested it against the xrpc and xrpc-server packages in this repo today, and got it working, but the example code in those packages' READMEs needed these tweaks.
=> Update example code in xrpc and xrpc-server READMEs

jest.config.base.js, package.json, packages/aws/package.json, packages/common/package.json, packages/common/src/blocks.ts, packages/crypto/package.json, packages/lex-cli/package.json, packages/pds/package.json, packages/pds/tsconfig.json, packages/repo/package.json, packages/repo/src/repo.ts, yarn.lock
Removing old unused dependencies.
A couple deps in PDS that weren't explicit & it was just getting from monorepo.
(that's where i installed a newer version of multiformats & kicked off dependency hell which i ended up just reverting cause we don't need to deal with it right now lol)
=> Cleanup dependencies

lexicons/app/bsky/embed/external.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/embed/external.ts, packages/pds/src/api/app/bsky/util/embeds.ts, packages/pds/src/db/migrations/20221212T195416407Z-post-media.ts, packages/pds/src/db/records/post.ts, packages/pds/src/db/tables/post-embed-external.ts, packages/pds/src/image/uri.ts, packages/pds/src/image/util.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/embed/external.ts, packages/pds/src/repo/blobs.ts, packages/pds/src/repo/prepare.ts, packages/pds/tests/crud.test.ts, packages/pds/tests/seeds/client.ts, packages/pds/tests/views/__snapshots__/author-feed.test.ts.snap, packages/pds/tests/views/__snapshots__/notifications.test.ts.snap, packages/pds/tests/views/__snapshots__/thread.test.ts.snap, packages/pds/tests/views/__snapshots__/timeline.test.ts.snap, packages/repo/bench/repo.bench.ts
A bundle of updates and fixes in this PR:
- Fix a typo (lmao)
- Fix image processing in post embeds
- Add proper validation of mimetype globs in the blob handler
- Modify the resize mode for embed images
- Make the thumbnail optional in external embeds
=> Fixes to post media

packages/pds/tests/auth.test.ts
Just a quick one. But the last needed to close out an old testing issue.
Closes https://github.com/bluesky-social/atproto/issues/211
=> Bad password test

packages/pds/src/api/com/atproto/password-reset.ts, packages/pds/src/auth.ts, packages/pds/src/db/migrations/20221215T220356370Z-password-reset-otp.ts, packages/pds/src/db/migrations/index.ts, packages/pds/src/db/tables/user.ts, packages/pds/src/logger.ts, packages/pds/src/mailer/index.ts, packages/pds/src/mailer/templates/reset-password.hbs, packages/pds/tests/account.test.ts
=> Reset password updates

lexicons/app/bsky/feed/post.json
Hi again, all! Really minor suggestion, I was working with this lexicon today and wanted to double check my understanding of the textSlice endpoint handling. Feel free to correct me if I'm wrong!
=> app.bsky.feed.post lexicon: add textSlice description

lexicons/app/bsky/actor/profile.json, lexicons/app/bsky/embed/external.json, lexicons/app/bsky/embed/images.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/feed/post.ts, packages/pds/src/image/sharp.ts, packages/pds/src/image/uri.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/feed/post.ts, packages/pds/tests/event-stream/__snapshots__/sync.test.ts.snap, packages/pds/tests/file-uploads.test.ts, packages/pds/tests/image/server.test.ts, packages/pds/tests/views/__snapshots__/assertions.test.ts.snap, packages/pds/tests/views/__snapshots__/author-feed.test.ts.snap, packages/pds/tests/views/__snapshots__/follows.test.ts.snap, packages/pds/tests/views/__snapshots__/members.test.ts.snap, packages/pds/tests/views/__snapshots__/notifications.test.ts.snap, packages/pds/tests/views/__snapshots__/profile.test.ts.snap, packages/pds/tests/views/__snapshots__/reposts.test.ts.snap, packages/pds/tests/views/__snapshots__/thread.test.ts.snap, packages/pds/tests/views/__snapshots__/timeline.test.ts.snap, packages/pds/tests/views/__snapshots__/votes.test.ts.snap, packages/pds/tests/views/user-search.test.ts
This PR:
- Doubles the max dimensions on all images
- Increases the size and quality of the images served
=> Improve image quality

packages/api/package.json, packages/lexicon/package.json, packages/xrpc/package.json
Bumping related to recent changes
=> Package version bumps

packages/pds/src/api/app/bsky/feed/getPostThread.ts, packages/pds/tests/views/__snapshots__/thread.test.ts.snap
This typo will never happen again 🙇
=> Remove "bksy"

packages/api/package.json, packages/lexicon/package.json, packages/lexicon/src/validators/primitives.ts, packages/lexicon/tests/_scaffolds/lexicons.ts, packages/lexicon/tests/general.test.ts, packages/lexicon/tsconfig.json, packages/lexicon/update-pkg.js, packages/pds/tests/views/__snapshots__/thread.test.ts.snap, packages/xrpc/package.json, packages/xrpc/tsconfig.json, packages/xrpc/update-pkg.js, yarn.lock
Fixes an issue with date-time validation in lexicon which caused it to reject valid iso8601 timestamps
Closes #402
=> Datetime validation fix

packages/dev-env/src/mock/index.ts
Includes some simple mocks in dev-env for working with moderation reports and actions.
=> Add some reporting mocks to dev-env

lexicons/app/bsky/graph/getFollows.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/graph/getFollows.ts, packages/api/src/client/types/com/atproto/admin/getModerationActions.ts, packages/api/src/client/types/com/atproto/admin/getModerationReports.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/graph/getFollows.ts, packages/pds/src/lexicon/types/com/atproto/admin/getModerationActions.ts, packages/pds/src/lexicon/types/com/atproto/admin/getModerationReports.ts
Smol bug in the lexicon for getFollows, the avatar field is missing
=> Add missing 'avatar' field in app.bsky.graph.getFollows

packages/lexicon/src/lexicons.ts, packages/lexicon/src/types.ts, packages/lexicon/src/validation.ts, packages/xrpc-server/package.json, packages/xrpc-server/src/server.ts, packages/xrpc-server/src/types.ts, packages/xrpc-server/src/util.ts, packages/xrpc-server/tests/_util.ts, packages/xrpc-server/tests/subscriptions.test.ts, packages/xrpc-stream/README.md, packages/xrpc-stream/babel.config.js, packages/xrpc-stream/build.js, packages/xrpc-stream/jest.config.js, packages/xrpc-stream/package.json, packages/xrpc-stream/src/frames.ts, packages/xrpc-stream/src/index.ts, packages/xrpc-stream/src/logger.ts, packages/xrpc-stream/src/server.ts, packages/xrpc-stream/src/stream.ts, packages/xrpc-stream/src/types.ts, packages/xrpc-stream/tests/frames.test.ts, packages/xrpc-stream/tests/server.test.ts, packages/xrpc-stream/tsconfig.build.json, packages/xrpc-stream/tsconfig.json, packages/xrpc-stream/update-pkg.js, tsconfig.json, yarn.lock
Devin's XRPC stream base work.
Pulling it into our repo on a branch to develop further
=> Xrpc stream base

packages/pds/package.json
Need the latest published for the app tests suite
=> Bump @atproto/pds@0.0.2

packages/api/package.json
Published 0.0.8 to include account deletion apis in #488
=> Bump @atproto/api@0.0.8

packages/pds/src/db/index.ts, packages/pds/src/services/repo/blobs.ts, packages/pds/tests/account-deletion.test.ts, packages/pds/tests/seeds/client.ts
We were doing a `SELECT WHERE IN` on an empty list which was causing a postgres syntax error.
This applies a fix that checks for empty arrays & a simple test that deletes an empty account
=> Account deletion hotfix

packages/pds/src/image/sharp.ts, packages/pds/tests/file-uploads.test.ts
This handles an issue with propagating stream errors during image upload, i.e. if a client aborts their request during the upload.
=> Handle client abort on image upload

packages/api/package.json, packages/xrpc/package.json
=> Bump @atproto/xrpc@0.0.4, @atproto/api@0.1.0

packages/plc/bin/did-create.ts, packages/plc/package.json
Just a utility to easily test did creation with PLC.
=> Add utility for testing PLC

lexicons/com/atproto/report/reasonType.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/com/atproto/report/reasonType.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/com/atproto/report/reasonType.ts
Small reasonType-o in the lexicon there.
=> Fix knownValues for reasonType lexicon

packages/api/package.json, packages/pds/package.json
Reflects updates in https://github.com/bluesky-social/atproto/pull/539
=> Bump @atproto/pds@0.0.3, @atproto/api@0.1.2

packages/common/package.json, packages/crypto/package.json, packages/plc/package.json
Just bumping package versions for common & crypto as I'm using them in the new plc repo
=> Bump package versions

packages/pds/Dockerfile, packages/plc/Dockerfile
Not required but nice to have them in there so they can be used by various UIs.
=> Add standard container image labels

packages/api/package.json, packages/pds/package.json
This is to capture the new post embed records
=> Bump @atproto/api@0.1.3, @atproto/pds@0.0.4

packages/pds/src/db/migrations/20230304T193548198Z-creator-indices.ts, packages/pds/src/db/migrations/20230304T193548198Z-pagination-indices.ts, packages/pds/src/db/migrations/index.ts
Adding orderBy indices on 
- post 
- repost
For their pagination keyset which is `(indexedAt, cid)`
=> Feed builder indices

packages/common/src/fs.ts, packages/common/src/index.ts, packages/pds/src/image/server.ts, packages/pds/src/storage/disk-blobstore.ts
Couple spots where we weren't closing open file handles. Started popping up in tests
=> Close open file handles

lexicons/com/atproto/sync/listBlobs.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/com/atproto/sync/listBlobs.ts, packages/pds/src/api/com/atproto/sync/index.ts, packages/pds/src/api/com/atproto/sync/listBlobs.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/com/atproto/sync/listBlobs.ts, packages/pds/src/services/repo/blobs.ts, packages/pds/tests/sync/sync.test.ts
Added in an XRPC method for listing blob cids for a given commit range
=> List blobs method

packages/pds/src/api/com/atproto/account/createInviteCode.ts, packages/pds/tests/account.test.ts
Make brute forcing a bit harder 😛
=> Increase inv code length to 7

packages/identifier/src/did.ts
Hi,
I just fixed a simple typo.
=> docs: fixed typo

packages/identifier/src/did.ts, packages/identifier/tests/did.test.ts
Hi,
I gave a specific name to the error about the DID validation. And for the name, I referred to `InvalidHandleError` in `handle.ts`.
=> feat: added `InvalidDidError`

packages/pds/src/api/com/atproto/account/createInviteCode.ts
kindly please first learn base32 rfc then use it :))
=> fix example invite code

packages/pds/src/app-migrations/update-follow-subjects.ts
Removes follows of scene records.  I used a static list here since it's short, it's fixed, and the `actorType` information would be dropped from the db before running the app migration unless we wanted to do some special coordination around that.
=> Lexicon: remove follows of scenes

packages/api/package.json, packages/common-web/package.json, packages/common/package.json, packages/crypto/package.json, packages/dev-env/package.json, packages/identifier/package.json, packages/lex-cli/package.json, packages/lexicon/package.json, packages/pds/package.json, packages/repo/package.json, packages/xrpc-server/package.json, packages/xrpc/package.json
=> Post lex refactor pkg publishes

packages/pds/Dockerfile
Fix the current build error in CI
=> Copy @atproto/common-web in Dockerfile

packages/api/package.json, packages/pds/package.json
Bump pds@0.1.2, api@0.2.3
Includes updates to createSession (include email) and displayName/description maxGrapheme & maxLength
=> Bump pds@0.1.2, api@0.2.3

packages/api/package.json, packages/pds/package.json
Publishes updates from #757 and #764
=> api@0.2.4, pds@0.1.3

packages/pds/src/api/com/atproto/server/getAccountInviteCodes.ts, packages/pds/tests/account.test.ts
Just fixing some arithmetic in here!
=> Fix for available invite creation

packages/api/package.json
Includes https://github.com/bluesky-social/atproto/pull/775
=> Bump @atproto/api@0.2.5

packages/pds/tests/sequencer.test.ts
Timing error in the test because PG notify/listen takes a split second to go out
=> Fix pg sequencer test

packages/bsky/src/db/database-schema.ts, packages/bsky/src/db/migrations/20230309T045948368Z-init.ts, packages/bsky/src/db/tables/feed-item.ts, packages/bsky/src/services/indexing/plugins/post.ts, packages/bsky/src/services/indexing/plugins/repost.ts, packages/pds/src/app-view/db/index.ts, packages/pds/src/app-view/db/tables/feed-item.ts, packages/pds/src/app-view/services/indexing/plugins/post.ts, packages/pds/src/app-view/services/indexing/plugins/repost.ts, packages/pds/src/db/migrations/20230406T185855842Z-feed-item-init.ts, packages/pds/src/db/migrations/index.ts, packages/pds/tests/event-stream/sync.test.ts, packages/pds/tests/subscription/repo.test.ts
This uses writes to posts and reposts to build-out an index of feed items (i.e. to appear in timeline and author feeds).
=> Index posts and reposts as feed items

lexicons/com/atproto/server/createInviteCodes.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/com/atproto/admin/defs.ts, packages/api/src/client/types/com/atproto/repo/listRecords.ts, packages/api/src/client/types/com/atproto/server/createInviteCodes.ts, packages/pds/src/api/com/atproto/server/createInviteCode.ts, packages/pds/src/api/com/atproto/server/createInviteCodes.ts, packages/pds/src/api/com/atproto/server/index.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/com/atproto/admin/defs.ts, packages/pds/src/lexicon/types/com/atproto/repo/listRecords.ts, packages/pds/src/lexicon/types/com/atproto/server/createInviteCodes.ts
Adds a route to create more than one invite code
=> Create bulk invite codes

lexicons/com/atproto/server/createSession.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/com/atproto/server/createSession.ts, packages/pds/src/api/com/atproto/server/createSession.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/com/atproto/server/createSession.ts, packages/pds/tests/account-deletion.test.ts, packages/pds/tests/auth.test.ts
This got about half handled in lex refactor & noticed it today while pruning issues
Closes https://github.com/bluesky-social/atproto/issues/493
=> Fully deprecate handle on createSession

packages/pds/src/api/app/bsky/notification/getUnreadCount.ts, packages/pds/src/api/app/bsky/notification/listNotifications.ts, packages/pds/tests/views/__snapshots__/notifications.test.ts.snap, packages/pds/tests/views/notifications.test.ts
We were removing mentions & replies, but now we remove all notifs
=> No notifs for any records from muted accounts

packages/pds/service/index.js, packages/pds/src/db/index.ts
Add env var for adjustable postgres pool size: rec trying out 20 first, default is 10
=> Adjustable db pool size

lexicons/com/atproto/moderation/defs.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/com/atproto/admin/defs.ts, packages/api/src/client/types/com/atproto/moderation/defs.ts, packages/bsky/src/lexicon/index.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts, packages/bsky/src/lexicon/types/app/bsky/feed/defs.ts, packages/bsky/src/lexicon/types/com/atproto/admin/defs.ts, packages/bsky/src/lexicon/types/com/atproto/admin/disableInviteCodes.ts, packages/bsky/src/lexicon/types/com/atproto/admin/getInviteCodes.ts, packages/bsky/src/lexicon/types/com/atproto/admin/searchRepos.ts, packages/bsky/src/lexicon/types/com/atproto/admin/takeModerationAction.ts, packages/bsky/src/lexicon/types/com/atproto/label/defs.ts, packages/bsky/src/lexicon/types/com/atproto/label/queryLabels.ts, packages/bsky/src/lexicon/types/com/atproto/label/subscribeLabels.ts, packages/bsky/src/lexicon/types/com/atproto/moderation/defs.ts, packages/bsky/src/lexicon/types/com/atproto/repo/listRecords.ts, packages/bsky/src/lexicon/types/com/atproto/server/createInviteCode.ts, packages/bsky/src/lexicon/types/com/atproto/server/defs.ts, packages/bsky/src/lexicon/types/com/atproto/server/getAccountInviteCodes.ts, packages/bsky/src/lexicon/types/com/atproto/server/getSession.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/com/atproto/admin/defs.ts, packages/pds/src/lexicon/types/com/atproto/moderation/defs.ts
Also added basic descriptions, not sure if we actually want those or should pull them out.
=> Lex: additional report types

packages/pds/src/api/com/atproto/admin/reverseModerationAction.ts, packages/pds/src/services/moderation/index.ts, packages/pds/src/services/moderation/views.ts, packages/pds/tests/moderation.test.ts
Ensure we're not splitting/joining an empty array into a string
=> Label reversal fix

lexicons/com/atproto/admin/updateAccountEmail.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/com/atproto/admin/updateAccountEmail.ts, packages/pds/src/api/com/atproto/admin/index.ts, packages/pds/src/api/com/atproto/admin/updateAccountEmail.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/com/atproto/admin/updateAccountEmail.ts, packages/pds/src/services/account/index.ts, packages/pds/tests/account.test.ts
Holding off on adding in user email updates because there are some security issues to take into account there
=> Add admin.updateAccountEamil

lexicons/com/atproto/server/createInviteCodes.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/com/atproto/server/createInviteCodes.ts, packages/pds/src/api/com/atproto/server/createInviteCodes.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/com/atproto/server/createInviteCodes.ts, packages/pds/tests/account.test.ts
allows you to send an array for dids to create invite codes for
=> Create invite codes for many accounts

packages/common-web/src/util.ts, packages/common/src/streams.ts, packages/pds/src/api/com/atproto/sync/getBlocks.ts, packages/pds/src/api/com/atproto/sync/getCheckout.ts, packages/pds/src/api/com/atproto/sync/getRecord.ts, packages/pds/src/api/com/atproto/sync/getRepo.ts, packages/pds/src/sequencer/events.ts, packages/pds/src/sql-repo-storage.ts, packages/pds/src/storage/memory-blobstore.ts, packages/repo/src/sync/provider.ts, packages/repo/src/util.ts, packages/repo/tests/sync/checkout.test.ts, packages/repo/tests/sync/diff.test.ts, packages/repo/tests/sync/narrow.test.ts
Previously, we were reading the car file to a buffer before writing it out to the response.
Now we just stream it directly out
=> Improve streaming sync routes

packages/pds/service/index.js, packages/pds/src/db/index.ts
Allow setting some more postgres connection pool settings via env vars for the PDS.
=> Add more config for pds db pool

lexicons/app/bsky/feed/getPosts.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/feed/getPosts.ts, packages/api/src/client/types/com/atproto/sync/getRepo.ts, packages/bsky/src/api/app/bsky/feed/getPosts.ts, packages/bsky/src/api/index.ts, packages/bsky/src/lexicon/index.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/feed/getPosts.ts, packages/bsky/src/lexicon/types/com/atproto/server/createAppPassword.ts, packages/bsky/src/lexicon/types/com/atproto/server/listAppPasswords.ts, packages/bsky/src/lexicon/types/com/atproto/server/revokeAppPassword.ts, packages/bsky/tests/_util.ts, packages/bsky/tests/views/__snapshots__/posts.test.ts.snap, packages/bsky/tests/views/posts.test.ts, packages/common-web/src/util.ts, packages/pds/src/app-view/api/app/bsky/feed/getPosts.ts, packages/pds/src/app-view/api/app/bsky/index.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/feed/getPosts.ts, packages/pds/tests/views/__snapshots__/posts.test.ts.snap, packages/pds/tests/views/posts.test.ts
Add a method for getting an array of post views
Added to both PDS & AppView
=> Get posts method

packages/api/package.json
To include the new `getPosts()` API
=> @atproto/api@0.2.9

packages/bsky/src/api/com/atproto/moderation/util.ts, packages/bsky/src/db/tables/moderation.ts, packages/pds/src/api/com/atproto/moderation/util.ts, packages/pds/src/db/tables/moderation.ts
Ideally in the future codegen will help us with these kinds of unions— this should conclude some of the "manual" work to support the new moderation report types.
=> Finalize support for new moderation report reasons

packages/pds/src/services/account/index.ts
Dumb typo. I check str length instead of arr len
=> Fix typo in appview

packages/api/package.json
for https://github.com/bluesky-social/atproto/pull/887 and https://github.com/bluesky-social/atproto/pull/854
=> Publish @atproto/api@0.2.10

packages/bsky/src/services/indexing/processor.ts, packages/pds/src/app-view/services/indexing/processor.ts, packages/pds/tests/indexing.test.ts
Notifications can be created out-of-band from record writes.
=> Background notification creation and deletion

packages/api/package.json, packages/pds/package.json
=> api@0.2.11, pds@0.1.5

CONTRIBUTORS.md
=> Add @ianklatzco to contributors file

packages/pds/src/labeler/hive.ts
Tune "porn", "sexual", and "nudity" label categorization, including re-structuring of code paths.
This comes out of some image testing as well as review of Hive API docs.
=> pds: iterated Hive label parsing

packages/api/package.json, packages/aws/package.json, packages/bsky/package.json, packages/common-web/package.json, packages/common/package.json, packages/crypto/package.json, packages/dev-env/package.json, packages/did-resolver/package.json, packages/identifier/package.json, packages/lex-cli/package.json, packages/lexicon/package.json, packages/nsid/package.json, packages/pds/package.json, packages/repo/package.json, packages/uri/package.json, packages/xrpc-server/package.json, packages/xrpc/package.json
All your packages on the npm website have no link back to the source code. This fixes that. Thanks!
=> add repository field to package.json

packages/bsky/src/api/blob-resolver.ts, packages/did-resolver/src/atproto-data.ts
**Description**
First of all, sorry in advance if this PR is a bit hilarious as this is one of my first contributions to any open-source project of this scale. SSRF potential may have seemed to me because I did not fully understand the protocol is also a possibility. However, if there is such vulnerability potential and more needs to be done to fix it than I have committed, please point it out in the comments, even if you are not a maintainer!
**Change(s) Made**
- Added URL validation to `getBlob()` function to prevent SSRF attacks.
**Related Issues**
None. Since I didn't come across any guidelines whatsoever I didn't open any on this topic either.
=> Fix SSRF vulnerability on blob

packages/pds/src/repo/prepare.ts, packages/pds/tests/crud.test.ts
The PDS can't reliably transform a record between lex and cbor, it will not allow the record to be written.
=> Disallow writes of bad records

packages/pds/src/app-view/services/label/index.ts
quick fix: made it into appview but not pds
=> Filter server-side labels

packages/pds/src/app-view/services/indexing/index.ts, packages/pds/src/services/account/index.ts, packages/pds/tests/account-deletion.test.ts
Weren't properly catching user state delete or block deletes in account delete
Closes https://github.com/bluesky-social/atproto/issues/937
=> Delete user state on account delete

packages/pds/src/app-view/services/indexing/plugins/post.ts
=> Blessed hell thread

packages/api/README.md
=> Update README.md example

CONTRIBUTORS.md
=> Add april to contributors for sec disclosure

packages/pds/src/services/index.ts, packages/pds/src/services/repo/blobs.ts, packages/pds/src/services/repo/index.ts
This is an expensive operation & was causing some deletes to fail
=> No cache invalidation on blob deletion

packages/pds/src/db/migrations/20230508T193807762Z-acct-deletion-indexes.ts
Followup to #1003, as promised!
=> Sync-up account deletion indexes migration

packages/pds/src/api/com/atproto/server/createAccount.ts, packages/pds/src/services/repo/index.ts
Still getting timing issues in firehose
=> Ensure sequencing is the last query in each tx

CONTRIBUTORS.md
Recent security disclosure credit
=> Add to CONTRIBUTORS

packages/pds/src/db/migrations/20230511T200212974Z-feed-generators.ts, packages/pds/src/db/migrations/index.ts
This is the same migration found in #1001.  Plan is to ship this first just to help things go smooth.
=> Db migration to prep for custom feeds

lexicons/app/bsky/unspecced/getPopularFeedGenerators.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/unspecced/getPopularFeedGenerators.ts, packages/pds/src/app-view/api/app/bsky/unspecced.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/unspecced/getPopularFeedGenerators.ts, packages/pds/tests/feed-generation.test.ts
Endpoint for fetching top 50 popular feed generators, ranked by like count.
=> Get popular feedgens

packages/pds/src/feed-gen/index.ts, packages/pds/src/feed-gen/mutuals.ts
Another custom feed content from people you follow that follow you back
=> Mutuals feed

packages/pds/src/db/index.ts
=> Improve logging around materialized view refresh

packages/pds/src/feed-gen/best-of-follows.ts, packages/pds/src/feed-gen/index.ts
Ranked feed (similar to new what's hot) but limits content to only people you follow
=> Best of follows feed

packages/pds/src/feed-gen/mutuals.ts
had to pull a quick one on the query optimizer
=> Improve mutuals feed

packages/pds/src/feed-gen/best-of-follows.ts, packages/pds/src/feed-gen/mutuals.ts
=> Improving mutuals again

packages/pds/tests/algos/with-friends.test.ts
Since we changed the algo & didn't update the test yet
=> Skip popular with friends test

packages/pds/src/feed-gen/with-friends.ts
This tweak to with-friends from #1124 worked well in testing but in practice it didn't move the needle for us, so reverting.
=> Revert perf tweak to with-friends

.github/workflows/build-and-push-pds-aws.yaml, packages/pds/src/app-view/api/app/bsky/unspecced.ts, packages/pds/src/feed-gen/hot-classic.ts, packages/pds/src/feed-gen/whats-hot.ts
Use a values list to help the database out a bit on these label subqueries.
=> Optimization for label subqueries on feeds

packages/dev-env/src/pds.ts, packages/pds/src/api/com/atproto/server/getAccountInviteCodes.ts, packages/pds/src/config.ts, packages/pds/src/db/index.ts, packages/pds/tests/_util.ts, packages/pds/tests/account.test.ts
Adds an inviteEpoch config variable
This allows us to change the invite interval without giving a big invite drop to old accounts
=> Invite epochs

packages/nsid/README.md
Closes https://github.com/bluesky-social/atproto/issues/1163
=> nsid: update package README (no blob pattern)

Makefile
Quick helper so I don't need to dig around in multiple packages to remember how to do this.
=> Makefile: API codegen helper

packages/crypto/src/multibase.ts, packages/crypto/src/secp256k1/operations.ts, packages/crypto/tests/signature-fixtures.json, packages/crypto/tests/signatures.test.ts
Just throwing up some test vectors to help us dummy-check interop with other implementations.
=> Test vectors for secp and p256 signature verification

packages/bsky/package.json, packages/dev-env/build.js, packages/dev-env/package.json, packages/dev-env/tsconfig.json, packages/dev-env/update-pkg.js
Fix up publishing the dev-env package.
- Ensure main gets set to `dist/index.js`
- build `.d.ts` files to root of `dist`
- publish `@atproto/bsky`
=> Fix dev env package

packages/pds/src/services/repo/index.ts
Check for and store unstored blocks on rebase. In most cases, we will not have any unstored blocks, but this should let us recover from cases of a borked repo
Closes https://github.com/bluesky-social/atproto/issues/1241
=> Ensure rebase recovers repos in a broken state

packages/pds/src/app-view/api/app/bsky/feed/getFeedGenerator.ts, packages/pds/src/app-view/api/app/bsky/feed/getFeedGenerators.ts, packages/pds/src/app-view/api/app/bsky/feed/getPostThread.ts, packages/pds/src/app-view/api/app/bsky/feed/getPosts.ts, packages/pds/src/app-view/api/app/bsky/unspecced.ts, packages/pds/src/app-view/services/feed/index.ts, packages/pds/src/app-view/services/feed/types.ts, packages/pds/src/app-view/services/feed/views.ts, packages/pds/tests/proxied/procedures.test.ts
Cleans up logic around record embeds
Also dramatically cuts down on database hits for formatting embeds
=> Rework record embeds

lexicons/app/bsky/unspecced/getTimelineSkeleton.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/unspecced/getTimelineSkeleton.ts, packages/bsky/src/api/app/bsky/unspecced/getPopularFeedGenerators.ts, packages/bsky/src/api/app/bsky/unspecced/getTimelineSkeleton.ts, packages/bsky/src/api/index.ts, packages/bsky/src/lexicon/index.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/unspecced/getTimelineSkeleton.ts, packages/dev-env/src/pds.ts, packages/dev-env/src/types.ts, packages/pds/src/app-view/api/app/bsky/feed/getFeed.ts, packages/pds/src/app-view/api/app/bsky/feed/getTimeline.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/unspecced/getTimelineSkeleton.ts, packages/pds/tests/proxied/__snapshots__/timeline-skeleton.test.ts.snap, packages/pds/tests/proxied/timeline-skeleton.test.ts, packages/pds/tests/proxied/views.test.ts
This is a partial measure to start proxying timeline construction to the appview
The unspecced route will likely only be staying around for a week or two
=> Proxy timeline skeleton construction

packages/pds/src/index.ts, packages/pds/src/sequencer/sequencer-leader.ts
A little utility to help PDS operators keep track of their sequencer.
=> Log pds sequencer leader stats

packages/identity/src/handle/index.ts, packages/identity/src/types.ts, packages/pds/src/config.ts, packages/pds/src/index.ts
Add ability to set up explicit dns servers to query for handle dns resolution
=> Explicit dns servers

packages/identity/src/id-resolver.ts
=> Thread through id-resolver cfg

packages/bsky/src/api/app/bsky/util/feed.ts
=> Sync-up appview feed date threshold w/ pds

packages/bsky/src/subscription/repo.ts
Possible fix for memory leak in repo subscription. We move error handling to to the handler so that it doesn't use a closure in the for loop
=> Refactor appview repo subscription for memleak

packages/bsky/src/services/feed/index.ts, packages/pds/src/api/com/atproto/sync/getBlob.ts, packages/pds/src/api/com/atproto/sync/getBlocks.ts, packages/pds/src/api/com/atproto/sync/getCheckout.ts, packages/pds/src/api/com/atproto/sync/getCommitPath.ts, packages/pds/src/api/com/atproto/sync/getHead.ts, packages/pds/src/api/com/atproto/sync/getRecord.ts, packages/pds/src/api/com/atproto/sync/getRepo.ts, packages/pds/src/api/com/atproto/sync/listBlobs.ts, packages/pds/src/app-view/api/app/bsky/feed/getAuthorFeed.ts, packages/pds/src/app-view/services/feed/index.ts, packages/pds/src/app-view/services/feed/types.ts, packages/pds/src/app-view/services/feed/views.ts, packages/pds/src/app-view/services/graph/index.ts, packages/pds/src/auth.ts, packages/pds/src/context.ts, packages/pds/tests/views/author-feed.test.ts
Builds off of #1301, also looking ahead to #1233 and unifying the pds a bit with the bsky appview implementation.
=> Include takendown posts for admins (feature branch)

packages/pds/bench/sequencer.bench.ts, packages/pds/jest.bench.config.js, packages/pds/package.json, packages/pds/src/sequencer/outbox.ts, packages/pds/src/sequencer/sequencer-leader.ts, packages/pds/src/sequencer/sequencer.ts
Add some simple benchmarks for sequencing & a couple small performance improvements:
- don't use zod in the sequencer path
- increase page size for both backfill & live tail
=> Sequencer benching

packages/bsky/tests/subscription/util.test.ts
Shamelessly stolen from https://github.com/bluesky-social/atproto/pull/1368
I just keep getting bit by it & want it merged sooner 😛
=> Fix flaky partition queue test

lexicons/com/atproto/moderation/defs.json, packages/bsky/tests/db.test.ts, packages/bsky/tests/labeler/hive.test.ts, packages/bsky/tests/views/posts.test.ts, packages/pds/tests/crud.test.ts, packages/pds/tests/db.test.ts, packages/pds/tests/invite-codes.test.ts, packages/pds/tests/labeler/hive.test.ts, packages/pds/tests/views/posts.test.ts, packages/xrpc-server/src/types.ts, packages/xrpc/src/types.ts
This PR aims to fix various minor typos in the codebase.
=> Fix various typos

packages/bsky/service/index.js, packages/pds/service/index.js
Inject datadog trace info into logs
=> Log injection

.github/workflows/build-and-push-pds-aws.yaml, packages/pds/src/app-view/api/app/bsky/graph/muteActor.ts, packages/pds/src/app-view/api/app/bsky/graph/muteActorList.ts, packages/pds/src/app-view/api/app/bsky/graph/unmuteActor.ts, packages/pds/src/app-view/api/app/bsky/graph/unmuteActorList.ts, packages/pds/src/app-view/api/app/bsky/notification/updateSeen.ts, packages/pds/src/context.ts
This turns ons proxying writes (mutes & updateSeen) to appview
=> Proxy writes to appview

packages/bsky/src/feed-gen/bsky-team.ts, packages/pds/src/feed-gen/bsky-team.ts
Adjust members of bsky team feed
=> Adjust bsky team feed

.github/workflows/build-and-push-pds-aws.yaml, packages/bsky/src/feed-gen/index.ts, packages/bsky/tests/algos/whats-hot.test.ts, packages/pds/src/app-view/api/app/bsky/feed/getFeed.ts, packages/pds/src/feed-gen/index.ts, packages/pds/tests/algos/hot-classic.test.ts, packages/pds/tests/algos/whats-hot.test.ts
Use feed generator routing just like any other 3rd party feed
=> Remove local whats hot from pds

packages/bsky/src/services/actor/views.ts, packages/pds/src/app-view/services/actor/views.ts
Similar to in feedServer.`getActorInfos`, do takedown checks in actor service
=> Reflect takedowns in actor service

packages/dev-env/src/bsky.ts
Fix open handles in appview tests but waiting for the indexer to be destroyed in dev-env
=> Fix open handles in appview tests

packages/bsky/src/context.ts, packages/bsky/src/index.ts, packages/bsky/src/indexer/services.ts, packages/bsky/src/label-cache.ts, packages/bsky/src/services/actor/index.ts, packages/bsky/src/services/actor/views.ts, packages/bsky/src/services/feed/index.ts, packages/bsky/src/services/index.ts, packages/bsky/src/services/label/index.ts, packages/dev-env/src/bsky.ts, packages/pds/src/app-view/services/label/index.ts, packages/pds/tests/proxied/admin.test.ts
Porting label cache to appview from https://github.com/bluesky-social/atproto/pull/1284
=> Appview label cache

packages/pds/src/sequencer/outbox.ts
Try bumping this up to see if it helps out at all with deploy db load
=> Increase backfill page size

packages/bsky/package.json, packages/pds/package.json
Forgot to push these changes from last week 😬
=> Bump packages

packages/pds/src/app-view/api/app/bsky/graph/getFollowers.ts
Followup to #1456 w/ a fix on the followers view.
=> Fix condition for viewing soft-deleted followers

.github/workflows/repo.yaml, packages/bsky/tests/views/author-feed.test.ts, packages/pds/tests/views/author-feed.test.ts
To help with flaky tests:
- increase matrix size from 4 -> 8
- decrease maxWorkers from 2 -> 1
=> Increase CI test matrix size

packages/common-web/src/util.ts, packages/pds/src/index.ts, packages/pds/src/runtime-flags.ts
Fixes some open handles that were introduced in runtime flags
=> Fix runtime flags open handles

.github/workflows/build-and-push-bsky-aws.yaml, packages/bsky/src/indexer/config.ts, packages/bsky/src/indexer/index.ts, packages/bsky/src/indexer/server.ts, packages/bsky/src/indexer/subscription.ts, packages/bsky/src/services/indexing/index.ts, packages/bsky/tests/reprocessing.test.ts, packages/dev-env/src/bsky.ts
Provides a simple http endpoint on indexers through which you can request that a given repo be reprocessed
=> Indexer request reprocess

packages/bsky/Dockerfile, packages/bsky/tests/reprocessing.test.ts, packages/pds/Dockerfile
Update renamed packages in Dockerfiles
=> Fix dependencies in dockerfiles

packages/pds/src/db/migrations/20230824T182048120Z-remove-post-hierarchy.ts
Doesn't _really_ matter cause this table is going away soon anyway. But for now, it's breaking some local dev-envs
Closes https://github.com/bluesky-social/atproto/issues/1523
=> Fix broken sqlite migration

packages/pds/src/app-view/api/app/bsky/feed/getAuthorFeed.ts
Users' posts were ending up on other users' feeds when applying read after write
=> Only do read after write on own author feed

packages/pds/src/app-view/api/app/bsky/unspecced.ts
=> getPopular hotfix

LICENSE, README.md, package.json
=> update Bluesky PBLLC to PBC (Public Benefit Corporation)

.changeset/tasty-countries-approve.md, packages/syntax/README.md
Noticed when sketching out #1610 that these imports were incorrect. Closed that PR, but might as well publish this.
=> fix syntax docs

packages/pds/src/api/app/bsky/actor/getPreferences.ts
In lieu of a more major authorization system, we filter out some user preferences in the `getPreferences` response
Closes https://github.com/bluesky-social/atproto/issues/1624
=> Filter preferences for app passwords

lexicons/app/bsky/actor/defs.json, packages/api/src/bsky-agent.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/actor/defs.ts, packages/api/src/types.ts, packages/api/tests/bsky-agent.test.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
Adds some preference fields for feeds and threads. For feeds, it has support for multiple different feeds; it seems pretty likely that people will want to set per-feed settings so that seems like a good place to start.
=> Add feed-vew and thread-view preferences

.changeset/quiet-carrots-leave.md
This got missed in https://github.com/bluesky-social/atproto/pull/1638
=> Add changeset for new preferences 

packages/api/README.md
The existing example caused some folks confusion:
https://github.com/bluesky-social/atproto/discussions/1618
added comments to try and clarify a bit
=> api: update login/resumeSession examples in README

.eslintrc, packages/api/src/agent.ts, packages/api/src/bsky-agent.ts, packages/api/src/moderation/subjects/feed-generator.ts, packages/api/src/moderation/subjects/user-list.ts, packages/api/src/moderation/util.ts, packages/api/src/rich-text/sanitization.ts, packages/api/tests/bsky-agent.test.ts, packages/bsky/src/api/com/atproto/admin/reverseModerationAction.ts, packages/bsky/tests/seeds/client.ts, packages/bsky/tests/views/actor-likes.test.ts, packages/common/tests/streams.test.ts, packages/crypto/tests/signatures.test.ts, packages/lexicon/tests/general.test.ts, packages/pds/src/app-view/services/label/index.ts, packages/pds/src/feed-gen/with-friends.ts, packages/pds/src/services/moderation/views.ts, packages/pds/tests/views/actor-likes.test.ts, packages/repo/tests/util.test.ts
mostly these crop up in github reviews for whatever reason, might as well just fix them
=> small syntax lints

lexicons/app/bsky/unspecced/getPopular.json, packages/api/src/client/lexicons.ts, packages/bsky/src/lexicon/lexicons.ts, packages/pds/src/lexicon/lexicons.ts
As discussed, a quick first step to ripping this out soon.
=> indicate that getPopular is deprecated

packages/api/package.json, packages/aws/package.json, packages/bsky/README.md, packages/bsky/package.json, packages/common-web/README.md, packages/common-web/package.json, packages/common/README.md, packages/common/package.json, packages/crypto/README.md, packages/crypto/package.json, packages/dev-env/README.md, packages/dev-env/package.json, packages/identity/README.md, packages/identity/package.json, packages/lex-cli/package.json, packages/lexicon/README.md, packages/lexicon/package.json, packages/pds/README.md, packages/pds/package.json, packages/repo/README.md, packages/repo/package.json, packages/syntax/README.md, packages/syntax/package.json, packages/xrpc-server/README.md, packages/xrpc-server/package.json, packages/xrpc/README.md, packages/xrpc/package.json
These are mostly tweaks to look better in npm. The identity and crypto packages got usage examples.
Will probably want to spend more time on some of these READMEs in the future, but want to push these small consistency tweaks.
=> tidy up package.json and READMEs

packages/bsky/src/api/app/bsky/actor/searchActors.ts, packages/bsky/src/api/app/bsky/actor/searchActorsTypeahead.ts
Fix a bug with hydrating profiles of DIDs from search that our Appview doesn't have
=> Proxy search bugfix

packages/dev-env/package.json, packages/dev-env/src/util.ts, packages/dev-infra/_common.sh, pnpm-lock.yaml
- Use axios instead of fetch for network mocks so we can mock the host header
- Normalize output from docker for dev-infra
=> Fix CI Issues

.changeset/giant-humans-argue.md, lexicons/app/bsky/actor/defs.json, packages/api/README.md, packages/api/definitions/moderation-behaviors.d.ts, packages/api/definitions/profile-moderation-behaviors.json, packages/api/docs/moderation-behaviors/profiles.md, packages/api/src/bsky-agent.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/actor/defs.ts, packages/api/src/moderation/accumulator.ts, packages/api/src/moderation/subjects/account.ts, packages/api/tests/util/index.ts, packages/api/tests/util/moderation-behavior.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts, packages/bsky/src/services/actor/types.ts, packages/bsky/src/services/actor/views.ts, packages/bsky/src/services/graph/index.ts, packages/bsky/tests/views/__snapshots__/block-lists.test.ts.snap, packages/bsky/tests/views/__snapshots__/mute-lists.test.ts.snap, packages/bsky/tests/views/block-lists.test.ts, packages/bsky/tests/views/blocks.test.ts, packages/bsky/tests/views/mute-lists.test.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
- Add modlist helper functions to the sdk bsky-agent (muteModList, unmuteModList, blockModList, unblockModList)
- Add "blocking by list" behaviors to moderation output
- Add `blockingByList` to viewer state of actors
=> Modlist updates: add "blockingByList" information and some utility functions to the sdk

packages/pds/src/config/config.ts, packages/pds/src/config/env.ts, packages/pds/src/context.ts
This PR is just intended to allow configuring non-AWS S3 blob storage.
See https://github.com/bluesky-social/atproto/issues/1583
=> PDS: Allow configuring non-AWS S3 blob storage.

packages/xrpc-server/README.md, packages/xrpc-server/tests/auth.test.ts, packages/xrpc-server/tests/bodies.test.ts, packages/xrpc-server/tests/errors.test.ts, packages/xrpc-server/tests/ipld.test.ts, packages/xrpc-server/tests/parameters.test.ts, packages/xrpc-server/tests/procedures.test.ts, packages/xrpc-server/tests/queries.test.ts, packages/xrpc-server/tests/rate-limiter.test.ts, packages/xrpc-server/tests/responses.test.ts, packages/xrpc-server/tests/subscriptions.test.ts, packages/xrpc/README.md
Follow-up to https://github.com/bluesky-social/atproto/pull/1790, as discussed in https://github.com/bluesky-social/atproto/pull/1801.
=> Adjust types to use LexiconDoc

packages/pds/src/api/com/atproto/admin/getSubjectStatus.ts, packages/pds/src/api/com/atproto/admin/updateSubjectStatus.ts
Ensures entryway proxies status updates to the user's pds, pairs with #1804.
=> Entryway proxying for admin subject status endpoints

.github/workflows/build-and-push-pds-ghcr.yaml, pnpm-lock.yaml, services/pds/index.js, services/pds/package.json
Wiring-up instrumentation of sqlite for pds v2.
=> Sqlite instrumentation for pds v2

packages/pds/src/api/com/atproto/server/createAccount.ts
A sync function was marked as async & it was making it's error the entire process's problem
Also, normalize handle inputs from entry way pds (which was causing the error to be thrown in the first place
=> catch handle validation error

packages/bsky/package.json, packages/dev-env/package.json, packages/pds/package.json, pnpm-lock.yaml
=> Upgrade sharp on pds and appview

packages/pds/package.json, pnpm-lock.yaml
=> Upgrade sharp on pds v2

packages/pds/tests/entryway.test.ts
- Test `AtpAgent` handles switch from entryway to pds based on `didDoc` served with sessions.
- Test transparent session refresh when user is assigned a new pds.
=> Test entryway session handling

packages/xrpc-server/src/server.ts
The `if` is always "truthy" here.
=> style(xrpc-server): avoid un-neccessary "if" statement

lexicons/app/bsky/graph/defs.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/graph/defs.ts, packages/bsky/src/api/app/bsky/graph/getList.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/graph/defs.ts, packages/bsky/src/services/graph/index.ts, packages/bsky/tests/views/__snapshots__/block-lists.test.ts.snap, packages/bsky/tests/views/__snapshots__/mute-lists.test.ts.snap, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/graph/defs.ts, packages/pds/tests/proxied/__snapshots__/views.test.ts.snap
Fixes https://github.com/bluesky-social/atproto/issues/1622
=> Attach record URI to listItemView

packages/bsky/tests/views/__snapshots__/block-lists.test.ts.snap, packages/bsky/tests/views/__snapshots__/mute-lists.test.ts.snap, packages/pds/tests/proxied/__snapshots__/views.test.ts.snap
Missed a couple snapshots in https://github.com/bluesky-social/atproto/pull/1758
=> Fix snapshots for list items

packages/bsky/src/services/indexing/plugins/post.ts, packages/bsky/tests/views/threadgating.test.ts
Ensures that replies that violate a threadgate do not generate notifications within the thread.
=> Do not generate notifs when post violates threadgate

services/bsky/api.js
The current logic prevents using two image invalidators. Indeed, the `if (bunnyInvalidator && imgInvalidator)` check is never `true` since `imgInvalidator` was never initialized at this point. The "simple" fix is to change `imgInvalidator` to `cfInvalidator` at this place. The approach I took is less error prone by confining the initialization of individual invalidators to a single place (`if (has config for invalidator) imgInvalidators.push(new invalidator)`).
=> fix(bsky): cf image invalidator not taken into account when bunny used

.github/workflows/build-and-push-bsky-aws.yaml, packages/bsky/src/cache/read-through.ts, packages/bsky/src/redis.ts, packages/bsky/src/services/label/index.ts
- fix some negative caching behavior
- fix handling on stale cache items
- correctly namespace expirations
=> Cache tweaks

packages/pds/package.json, packages/pds/src/api/com/atproto/server/createAccount.ts, packages/pds/tests/entryway.test.ts, pnpm-lock.yaml
Also updates the plc lib used in the pds.
=> Proper validation of entryway op in account creation

packages/bsky/src/db/util.ts, packages/bsky/src/services/graph/index.ts, packages/bsky/tests/views/block-lists.test.ts, packages/bsky/tests/views/mute-lists.test.ts
No longer enforce lists if the list has
- been deleted
- changed its purpose to a curatelist
=> Do not enforce deleted lists

.github/workflows/publish.yaml
=> Run the publishing workflow in the original repository only

.changeset/light-lizards-tap.md, packages/api/src/agent.ts, packages/api/src/types.ts
Porting changes to main from https://github.com/bluesky-social/atproto/pull/2055/commits/e56003988404607cf3b8914753e32ab08a285417
=> Directly pass create account params in agent

lexicons/app/bsky/unspecced/getTaggedSuggestions.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/unspecced/getTaggedSuggestions.ts, packages/bsky/src/api/app/bsky/unspecced/getTaggedSuggestions.ts, packages/bsky/src/api/index.ts, packages/bsky/src/db/database-schema.ts, packages/bsky/src/db/migrations/20240124T023719200Z-tagged-suggestions.ts, packages/bsky/src/db/migrations/index.ts, packages/bsky/src/db/tables/tagged-suggestion.ts, packages/bsky/src/lexicon/index.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/unspecced/getTaggedSuggestions.ts, packages/bsky/tests/views/suggestions.test.ts, packages/ozone/src/lexicon/index.ts, packages/ozone/src/lexicon/lexicons.ts, packages/ozone/src/lexicon/types/app/bsky/unspecced/getTaggedSuggestions.ts, packages/pds/src/api/app/bsky/unspecced/getTaggedSuggestions.ts, packages/pds/src/api/app/bsky/unspecced/index.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/unspecced/getTaggedSuggestions.ts
Adds a new route to return a simple list of suggested feeds/actors each tagged by category
=> Tagged suggestions

lexicons/app/bsky/graph/getRelationships.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/graph/defs.ts, packages/api/src/client/types/app/bsky/graph/getRelationships.ts, packages/bsky/src/lexicon/index.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/graph/defs.ts, packages/bsky/src/lexicon/types/app/bsky/graph/getRelationships.ts, packages/ozone/src/lexicon/index.ts, packages/ozone/src/lexicon/lexicons.ts, packages/ozone/src/lexicon/types/app/bsky/graph/defs.ts, packages/ozone/src/lexicon/types/app/bsky/graph/getRelationships.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/graph/defs.ts, packages/pds/src/lexicon/types/app/bsky/graph/getRelationships.ts
Just a small typo
Also take the chance to codegen for new schemas
=> Fix typo in getRelationships

packages/pds/src/api/com/atproto/server/createAccount.ts
Do network requests outside of the createAccount transaction on entrway. If the requests errors, then attempt to delete/cleanup the partially created entryway account.
=> Entryway: non-transactional createAccount

packages/pds/src/api/com/atproto/server/updateEmail.ts, packages/pds/src/services/account/index.ts
reflected in PDS in https://github.com/bluesky-social/atproto/pull/2131
=> Clear email tokens on email update - entryway

packages/pds/src/account-manager/index.ts, packages/pds/src/api/com/atproto/server/updateEmail.ts
=> Remove all email tokens on email change

packages/bsky/src/config.ts
Small fix to admin environment variable in appview v2.
=> Appview v2 fix admin environment variable

packages/pds/src/mailer/templates/account-activated.hbs
**Note**: this embeds https://bsky.social/about/images/social-card-default-gradient.png. If there's any concern that the image won't be reliably available, you should find another place to host it.
Here's the HTML used in the bootstrap email editor to generate this:
```html
<html>
<head>
<preview>Head over to the Bluesky app to sign in</preview>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
/* Add custom classes and styles that you want inlined here */
</style>
</head>
<body class="bg-light">
<div class="container">
<div class="card my-10">
<div class="card-body">
<a href="https://bsky.app/" target="_blank">
</a>
<h5 class="mt-4 mb-2 text-gray-600">Great news!</h5>
<h1 class="h4">Your Bluesky account is activated.</h1>
<hr>
<div class="space-y-3">
<p …
```
=> Activation email template

packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts, packages/bsky/src/services/feed/index.ts, packages/bsky/src/services/feed/views.ts, packages/bsky/tests/views/author-feed.test.ts
This allows moderators/admins to review posts from taken down accounts.
=> Include takendown posts on author feed for admins

packages/pds/src/api/com/atproto/server/createAccount.ts, packages/pds/src/auth-verifier.ts, packages/pds/src/index.ts, packages/pds/src/registration-checker.ts, packages/pds/tests/phone-verification.test.ts
Additional support for out-of-band verification code in place of phone verification.
=> Setup alternative self-verification in account creation

packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts, packages/bsky/src/hydration/hydrator.ts, packages/bsky/tests/views/author-feed.test.ts
Porting over already implemented behavior from main.
=> :sparkles: Show author feed of takendown author to admins only

packages/pds/src/api/com/atproto/admin/updateAccountHandle.ts, packages/pds/src/api/com/atproto/identity/updateHandle.ts
Follow up to https://github.com/bluesky-social/atproto/pull/2208
Forgot to send identity events after handle change
=> Send identity evts on handle change

packages/pds/src/api/com/atproto/admin/updateAccountHandle.ts, packages/pds/src/api/com/atproto/identity/updateHandle.ts, packages/pds/tests/sync/subscribe-repos.test.ts
Fix tests from the too-quickly-merged https://github.com/bluesky-social/atproto/pull/2209
=> Firehose identity cleanup

.changeset/cuddly-adults-beg.md, interop-test-files/syntax/aturi_syntax_valid.txt, interop-test-files/syntax/recordkey_syntax_invalid.txt, interop-test-files/syntax/recordkey_syntax_valid.txt, packages/syntax/src/recordkey.ts
Does what it says!
I'm not sure if we are doing any additional check at record-creation time, which we should now relax.
=> syntax: allow colon in record-key

packages/pds/src/api/com/atproto/server/createAccount.ts, packages/pds/src/auth-verifier.ts, packages/pds/src/config/env.ts, packages/pds/src/config/secrets.ts, packages/pds/tests/phone-verification.test.ts
Adds support for encrypted jwts as self-verification tokens during account creation.
=> Entryway: support jwe self-verification tokens

packages/pds/src/api/com/atproto/admin/sendEmail.ts, packages/pds/src/auth-verifier.ts, packages/pds/tests/admin-auth.test.ts
In the case that a pds is behind the entryway, the pds may prompt the entryway to send an email to a user by hitting `com.atproto.admin.sendEmail` using account service auth.  The old behavior using role auth and passing along `emitModerationEvent` to the moderation service is deprecated.
=> Entryway sending email via account service auth, deprecate mod service email flow

packages/bsky/src/api/app/bsky/graph/getFollowers.ts, packages/bsky/src/api/app/bsky/graph/getFollows.ts
Just a little bit of missing plumbing.
=> Appview: include takedowns properly on follow endpoints

packages/bsky/src/hydration/label.ts
Signature does not need to be returned in application views
=> Remove sig in label hydration

packages/ozone/src/api/label/subscribeLabels.ts
Use schema fragment id rather than full name
=> Fix output type on subscribeLabels

packages/api/src/bsky-agent.ts, packages/api/tests/bsky-agent.test.ts, packages/api/tests/moderation-prefs.test.ts
Ensures our default labeler is supplied to `moderationPrefs` and thereby `ModerationOpts`
=> Mod sdk fixes

.changeset/beige-eagles-smoke.md
=> Add changeset

packages/aws/src/s3.ts
Add a 10s timeout to blob uploads
=> Timeout blob uploads

packages/dev-env/package.json, packages/dev-env/src/bin.ts, packages/dev-env/src/introspect.ts, packages/dev-env/src/network.ts, packages/dev-env/src/types.ts, pnpm-lock.yaml
Adds an optional introspection server to the dev-env so that other packages have an entrypoint to join the network. 
For now, it's just a simple server with only one route that supplies the url & did of relevant services in the network
=> Dev-env introspection server

.changeset/swift-sloths-train.md, .changeset/thin-beers-approve.md, packages/pds/src/account-manager/helpers/auth.ts
=> Bugfix: privileged app passwords

packages/api/src/agent.ts, packages/api/src/rich-text/detection.ts, packages/api/src/rich-text/util.ts, packages/api/src/util.ts, packages/api/tests/moderation-quoteposts.test.ts, packages/bsky/tests/label-hydration.test.ts, packages/bsky/tests/query-labels.test.ts, packages/ozone/tests/lang.test.ts, packages/pds/tests/handle-validation.test.ts
Simple PR fixing some linting warnings
=> Fix some linting warnings

packages/ozone/src/api/proxied.ts, packages/ozone/src/config/config.ts, packages/ozone/src/config/env.ts, packages/ozone/src/context.ts
Follow up to https://github.com/bluesky-social/atproto/pull/2587
Tidy the cfg by replacing entryway agent with the already existing pds agent
=> Tidy ozone config

README.md, packages/pds/example.env
https://github.com/bluesky-social/atproto/discussions/2610
=> remove mentions of sandbox

.changeset/fluffy-yaks-talk.md, lexicons/app/bsky/embed/record.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/embed/record.ts, packages/bsky/src/hydration/hydrator.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/embed/record.ts, packages/bsky/src/views/index.ts, packages/bsky/tests/__snapshots__/feed-generation.test.ts.snap, packages/bsky/tests/feed-generation.test.ts, packages/ozone/src/lexicon/lexicons.ts, packages/ozone/src/lexicon/types/app/bsky/embed/record.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/embed/record.ts
Adds support for adding starter packs to post embeds. See https://github.com/bluesky-social/social-app/pull/4699
=> Add starter packs to post hydration

.github/workflows/publish.yaml, .github/workflows/repo.yaml
The pnpm/action-setup action was causing errors in CI, see also https://github.com/pnpm/action-setup/issues/135
=> Upgrade pnpm/action-setup in workflows

.changeset/seven-shrimps-build.md, packages/oauth/oauth-provider/package.json, packages/oauth/oauth-provider/src/lib/http/parser.ts, packages/oauth/oauth-provider/src/lib/http/stream.ts, pnpm-lock.yaml
Replaces https://github.com/bluesky-social/atproto/pull/2717
Thanks @tom-sherman
=> Allow charset in content-type header of incoming requests

.github/workflows/build-and-push-bsky-ghcr.yaml, services/bsky/Dockerfile
Copy sync file over in bsky Dockerfile
=> Fix bsky build

packages/bsky/src/api/app/bsky/graph/getSuggestedFollowsByActor.ts, packages/bsky/src/feature-gates.ts
Just doing a little cleanup here, we ramped this gate to 100% a couple weeks ago.
=> Remove launched feature gate

.changeset/lemon-bags-tan.md, packages/common-web/src/did-doc.ts
https://caniuse.com/mdn-api_url_canparse_static
=> ponyfill URL.canParse

packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts, packages/bsky/tests/views/__snapshots__/author-feed.test.ts.snap, packages/bsky/tests/views/author-feed.test.ts
Just a simple check that the post URI includes the user's DID. Includes a new test
=> Disallow pinning someone else's post

packages/pds/src/sequencer/events.ts, packages/pds/tests/sequencer.test.ts
=> Fix root block missing in too big seq commit

.changeset/new-pears-shout.md
Changset for https://github.com/bluesky-social/atproto/pull/2922
=> updateHandle changeset

.changeset/wet-cars-doubt.md, lexicons/tools/ozone/moderation/defs.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/tools/ozone/moderation/defs.ts, packages/ozone/src/api/util.ts, packages/ozone/src/lexicon/lexicons.ts, packages/ozone/src/lexicon/types/tools/ozone/moderation/defs.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/tools/ozone/moderation/defs.ts
Follow up to https://github.com/bluesky-social/atproto/pull/2929
=> Add threat signatures to ozone repo views

.changeset/mighty-schools-yawn.md, packages/pds/src/api/app/bsky/feed/getFeed.ts
Simpler request, should be faster & takes load off of labels, profiles, aggregations tables, etc
=> Resolve record instead of feed view for getFeed

.changeset/dry-lamps-help.md, .changeset/five-emus-retire.md, packages/internal/fetch/src/fetch-error.ts, packages/internal/fetch/src/fetch-request.ts, packages/oauth/oauth-provider/src/client/client-manager.ts, packages/oauth/oauth-provider/src/errors/invalid-client-metadata-error.ts, packages/oauth/oauth-provider/src/lib/util/function.ts, packages/oauth/oauth-provider/src/token/token-manager.ts
=> Improve messaging of client metadata loading errors

.changeset/perfect-dodos-prove.md
=> Add changeset for #2819

packages/bsky/src/api/app/bsky/unspecced/getConfig.ts, packages/bsky/src/config.ts
=> add trending topics to server cfg

packages/api/src/client/lexicons.ts, packages/ozone/src/lexicon/lexicons.ts, packages/pds/src/lexicon/lexicons.ts
Lexgen on main is not in sync with lexicon defs. This fixes that.
=> Fixes lexgen on main

.changeset/ten-seahorses-wash.md, lexicons/app/bsky/actor/getSuggestions.json, lexicons/app/bsky/graph/getSuggestedFollowsByActor.json, lexicons/app/bsky/unspecced/getSuggestionsSkeleton.json, packages/api/src/client/types/app/bsky/actor/getSuggestions.ts, packages/api/src/client/types/app/bsky/graph/getSuggestedFollowsByActor.ts, packages/api/src/client/types/app/bsky/unspecced/getSuggestionsSkeleton.ts, packages/bsky/src/lexicon/types/app/bsky/actor/getSuggestions.ts, packages/bsky/src/lexicon/types/app/bsky/graph/getSuggestedFollowsByActor.ts, packages/bsky/src/lexicon/types/app/bsky/unspecced/getSuggestionsSkeleton.ts, packages/ozone/src/lexicon/types/app/bsky/actor/getSuggestions.ts, packages/ozone/src/lexicon/types/app/bsky/graph/getSuggestedFollowsByActor.ts, packages/ozone/src/lexicon/types/app/bsky/unspecced/getSuggestionsSkeleton.ts, packages/pds/src/lexicon/types/app/bsky/actor/getSuggestions.ts, packages/pds/src/lexicon/types/app/bsky/graph/getSuggestedFollowsByActor.ts, packages/pds/src/lexicon/types/app/bsky/unspecced/getSuggestionsSkeleton.ts
Add recids to getSuggestion response
=> Add recId to getSuggestionsSkeleton

lexicons/com/atproto/lexicon/schema.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/com/atproto/lexicon/schema.ts, packages/bsky/src/lexicon/index.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/com/atproto/lexicon/schema.ts, packages/ozone/src/lexicon/index.ts, packages/ozone/src/lexicon/lexicons.ts, packages/ozone/src/lexicon/types/com/atproto/lexicon/schema.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/com/atproto/lexicon/schema.ts
See Lexicon Resolution spec discussion: https://github.com/bluesky-social/atproto/discussions/3074
This needs a codegen and maybe a patch-level changeset before merging; looking for review on just the schema to start.
=> lexicon schema for lexicon schema records (meta)

.changeset/lemon-adults-sparkle.md, .changeset/tall-kings-poke.md, packages/ozone/src/mod-service/views.ts, packages/ozone/tests/__snapshots__/get-record.test.ts.snap, packages/ozone/tests/__snapshots__/get-records.test.ts.snap, packages/ozone/tests/__snapshots__/get-repo.test.ts.snap, packages/ozone/tests/__snapshots__/get-repos.test.ts.snap, packages/ozone/tests/__snapshots__/moderation-events.test.ts.snap, packages/ozone/tests/__snapshots__/moderation-statuses.test.ts.snap, packages/pds/tests/__snapshots__/takedown-appeal.test.ts.snap, packages/pds/tests/proxied/__snapshots__/admin.test.ts.snap, packages/pds/tests/sequencer.test.ts, packages/pds/tests/takedown-appeal.test.ts
This makes tests on PDS more consistent
=> fix pds tests flakiness

.changeset/cool-yaks-change.md, lexicons/app/bsky/actor/defs.json, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/actor/defs.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts, packages/ozone/src/lexicon/lexicons.ts, packages/ozone/src/lexicon/types/app/bsky/actor/defs.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
=> Include new `followerRule` as valid setting in `postInteractionSettings` pref

.changeset/few-rice-enjoy.md, packages/lex-cli/src/codegen/lex-gen.ts
=> Fix lex-cli Windows compatibility

.changeset/dirty-islands-dance.md
Changeset missing in https://github.com/bluesky-social/atproto/pull/3532
=> changeset for Appview: apply needs-review to individual records

.changeset/slimy-chicken-vanish.md, packages/bsky/src/data-plane/server/subscription.ts, packages/pds/src/api/com/atproto/server/createAccount.ts, packages/pds/src/sequencer/events.ts, packages/pds/tests/sequencer.test.ts, packages/pds/tests/sync/subscribe-repos.test.ts, packages/sync/src/events.ts, packages/sync/src/firehose/index.ts, packages/sync/src/firehose/lexicons.ts, packages/sync/src/util.ts, packages/sync/tests/firehose.test.ts
Add basic sync event handling to `@atproto/sync`.
Emit sync events on createAccount.
=> Sync event handling

.changeset/unlucky-adults-appear.md
I generated this but forgot to commit it as part of https://github.com/bluesky-social/atproto/pull/3633
Might self-merge
=> add missing changeset

.changeset/itchy-shrimps-buy.md, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/chat/bsky/convo/addReaction.ts, packages/api/src/client/types/chat/bsky/convo/defs.ts, packages/api/src/client/types/chat/bsky/convo/getLog.ts, packages/api/src/client/types/chat/bsky/convo/removeReaction.ts, packages/bsky/src/lexicon/index.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/chat/bsky/convo/addReaction.ts, packages/bsky/src/lexicon/types/chat/bsky/convo/defs.ts, packages/bsky/src/lexicon/types/chat/bsky/convo/removeReaction.ts, packages/ozone/src/lexicon/index.ts, packages/ozone/src/lexicon/lexicons.ts, packages/ozone/src/lexicon/types/chat/bsky/convo/addReaction.ts, packages/ozone/src/lexicon/types/chat/bsky/convo/defs.ts, packages/ozone/src/lexicon/types/chat/bsky/convo/getLog.ts, packages/ozone/src/lexicon/types/chat/bsky/convo/removeReaction.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/chat/bsky/convo/addReaction.ts, packages/pds/src/lexicon/types/chat/bsky/convo/defs.ts, packages/pds/src/lexicon/types/chat/bsky/convo/getLog.ts, packages/pds/src/lexicon/types/chat/bsky/convo/removeReaction.ts
Whoopsie, previous PR forgot to do it
=> Run codegen for reaction lexicon changes

.changeset/tiny-snakes-shop.md, lexicons/app/bsky/unspecced/getSuggestedUsers.json, lexicons/app/bsky/unspecced/getSuggestedUsersSkeleton.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/app/bsky/unspecced/getSuggestedUsers.ts, packages/api/src/client/types/app/bsky/unspecced/getSuggestedUsersSkeleton.ts, packages/bsky/src/api/app/bsky/unspecced/getSuggestedUsers.ts, packages/bsky/src/api/index.ts, packages/bsky/src/lexicon/index.ts, packages/bsky/src/lexicon/lexicons.ts, packages/bsky/src/lexicon/types/app/bsky/unspecced/getSuggestedUsers.ts, packages/bsky/src/lexicon/types/app/bsky/unspecced/getSuggestedUsersSkeleton.ts, packages/ozone/src/lexicon/index.ts, packages/ozone/src/lexicon/lexicons.ts, packages/ozone/src/lexicon/types/app/bsky/unspecced/getSuggestedUsers.ts, packages/ozone/src/lexicon/types/app/bsky/unspecced/getSuggestedUsersSkeleton.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/app/bsky/unspecced/getSuggestedUsers.ts, packages/pds/src/lexicon/types/app/bsky/unspecced/getSuggestedUsersSkeleton.ts
=> add `getSuggestedUsers`

.changeset/old-students-greet.md, lexicons/tools/ozone/hosting/getAccountHistory.json, packages/api/src/client/index.ts, packages/api/src/client/lexicons.ts, packages/api/src/client/types/tools/ozone/hosting/getAccountHistory.ts, packages/ozone/src/api/proxied.ts, packages/ozone/src/lexicon/index.ts, packages/ozone/src/lexicon/lexicons.ts, packages/ozone/src/lexicon/types/tools/ozone/hosting/getAccountHistory.ts, packages/pds/src/lexicon/index.ts, packages/pds/src/lexicon/lexicons.ts, packages/pds/src/lexicon/types/tools/ozone/hosting/getAccountHistory.ts
Wiring-up proxying for ozone hosting interfaces.
=> Ozone: support for tools.ozone.hosting.getAccountHistory

packages/bsky/src/api/com/atproto/repo/getRecord.ts, packages/ozone/src/api/moderation/getRecord.ts, packages/ozone/src/context.ts, packages/ozone/src/mod-service/index.ts, packages/ozone/src/mod-service/util.ts, packages/ozone/src/mod-service/views.ts, packages/ozone/tests/__snapshots__/get-record.test.ts.snap, packages/ozone/tests/get-record.test.ts, packages/pds/tests/proxied/admin.test.ts
This should help ozone display records from custom lexicons.
=> :bug: Fetch record from pds if appview fails to find it for ozone

.changeset/three-actors-greet.md, packages/oauth/oauth-client/src/fetch-dpop.ts, packages/oauth/oauth-client/src/oauth-server-agent.ts, packages/oauth/oauth-client/src/oauth-session.ts
Related to: bluesky-social/cookbook#23
=> Remove `iss` claim from DPoP proofs

packages/bsky/src/api/blob-resolver.ts, packages/dev-env/src/mock/index.ts
**Description:**  
- Fixed a typo in a mock post text ("reallly" → "really").
- Improved comment formatting in blob-resolver middleware for clarity.
=> Minor Fixes: Typo Correction and Comment Update

packages/bsky/proto/bsky.proto, packages/bsky/src/api/app/bsky/notification/util.ts, packages/bsky/src/data-plane/server/routes/private-data.ts, packages/bsky/src/proto/bsky_pb.ts
Small change here to come up to speed with a breaking change to bsky protos.
=> Appview: sync up protos for notification prefs

.changeset/few-rules-confess.md, packages/repo/src/mst/util.ts, packages/repo/tests/mst.test.ts
Closes: https://github.com/bluesky-social/atproto/issues/3972
=> repo: MST should allow tilde in keys

.changeset/wet-beans-listen.md, packages/pds/src/pipethrough.ts, packages/pds/tests/proxied/proxy-header.test.ts
=> Improve error handling when destroying pipethrough stream

.changeset/chilled-rules-speak.md, .changeset/swift-wasps-perform.md, packages/oauth/oauth-client-browser/src/browser-oauth-client.ts, packages/oauth/oauth-client/src/oauth-client.ts
Followup on https://github.com/bluesky-social/atproto/pull/4147
=> Improve oauth client callback handling

packages/bsky/src/api/app/bsky/feed/getFeed.ts
remove redundant word in comment
=> chore: remove redundant word in comment
