bluesky-social/atproto

- package.json
- packages/ws-relay/build.js
- packages/ws-relay/package.json
- yarn.lock
Quick patch for the build script for `ws-relay`
and adding in missing peer dependency `@babel/core`
> Quick patch - refactor followup

- packages/auth/package.json
- packages/awake/package.json
- packages/common/package.json
- packages/crypto/package.json
- packages/did-sdk/package.json
- packages/server/package.json
- packages/ws-relay/package.json
I was exporting `dist/index.js` in most packages.
We want to export `src/index.ts` so that esbuild can build in the original typescript. This also fixes issues with jest running.
We'll need to figure out how to set this to `dist/index.js` on publish.
This can probably be done w a publishing script or by using pnpm's `publishConfig` feature ([as seen here](https://github.com/CryogenicPlanet/typescript-monorepo-example/blob/master/packages/package-a/package.json#L22)). But this would require using pnpm instead of yarn
> fixed package exports

- packages/auth/src/auth-store.ts
- packages/auth/src/browser-store.ts
Found a couple of sneaky bois 🐛  lurking in the auth lobby code
- A missing `await` when adding a ucan that caused the auth check to fail even though the token should've been there
- not persisting the key for the root device, so it was loading a new key when refreshing an already logged in root device
> Quick auth lobby fix

- packages/api/src/schemas.ts
- packages/api/src/types/todo/social/getFeed.ts
- packages/server/src/api/todo/social/getFeed.ts
- packages/server/src/lexicon/schemas.ts
- packages/server/src/lexicon/types/todo/social/getFeed.ts
- packages/server/tests/views.test.ts
- schemas/todo.social/getFeed.json
- Adds a `cursor` field to items returned by `todo.social.getFeed`
- Internally switches to ordering by indexedAt (needs to eventually be rtime probably)
This change basically makes it unambiguous what to pass into the `before` param when using getFeed. I'd suggest using this pattern or similar any time we need pagination in APIs.
> Add better cursor pagination behavior to getFeed

- packages/server/src/api/todo/social/getFeed.ts
- packages/server/tests/views.test.ts
Mainly fixes an issue where the `repostedBy` information would be incorrectly populated on non-reposts
> Feed bugfixes

- packages/server/src/db/records/post.ts
@dholms Probably would be good to have an fkey relationship or a secondary index to speed up joins, but I was getting some constraint failures and decided to punt that to you
> Fix: support multiple post entities per post

- packages/server/src/api/todo/social/getAuthorFeed.ts
- packages/server/src/api/todo/social/getHomeFeed.ts
- packages/server/src/api/todo/social/util.ts
- packages/server/src/db/util.ts
- packages/server/tests/views.test.ts
There are a few fixes in here to home and author feeds:
- A post and its repost are now distinguished from each other, and can appear together in the same feed.  This was fixed by adjusting the `groupBy()` clause.  This also repaired a flaky test, where `repostedBy` was sometimes not appearing when it should have.
- Reposts are are ordered in the feed based on their indexed time, rather than that of their post.  The FeedItem `cursor` values are updated to reflect this.
- Users' own posts (but not reposts) now appear in their feed. Resolves #201
> Fixes for handling of posts vs. reposts in feeds

- packages/crypto/src/p256/ecdsa.ts
- packages/crypto/tests/did.test.ts
Added tests to confirm we transform between NIST P-256 public keys & did:keys correctly. Based on test vectors from the w3c
> Tests for did conversion

- package.json
- packages/did-resolver/package.json
- packages/did-resolver/test.env
- packages/did-resolver/tests/resolver.test.ts
- packages/plc/build.js
- packages/plc/package.json
- packages/plc/src/lib/document.ts
- packages/plc/src/lib/operations.ts
- packages/plc/src/server/db.ts
- packages/plc/src/server/error.ts
- packages/plc/src/server/index.ts
- packages/plc/src/server/locals.ts
- packages/plc/src/server/logger.ts
- packages/plc/test.env
- packages/plc/tests/document.test.ts
- packages/plc/tests/server.test.ts
- packages/server/tests/_util.ts
Takes care of the tests from https://github.com/bluesky-social/adx/issues/211
- ensuring a valid did:key on key rotate ops (had to implement)
- a test around race conditions (& a bug that i sussed out on how we were returning ops)
- handling username/pds with or without a protocol handler (had to implement)
Adds logging with pino
Fixes some build issues around switching to keysely
- nohoist better-sqlite3 & mark it external in build script (I had to wipe out my node_modules & reinstall for this to work, you may have to do the same)
- fix up a couple of small things in tests for server/did-resolver to bring them up to date (mainly creating tables)
resolves https://github.com/bluesky-social/adx/issues/221
> Plc tests & cleanup

- packages/dev-env/build.js
- packages/dev-env/src/index.ts
- packages/plc/src/server/db.ts
- packages/server/tests/_util.ts
The dev-env wasn't working as of the recent introduction of better-sqlite3.  Included here are the fixes!
- Create the PLC tables when bootstrapping the PLC server in dev-env.
- Ensure better-sqlite3 bindings are external to the dev-env build.
> Fix PLC server usage in dev-env

- packages/dev-env/package.json
- packages/dev-env/tsconfig.build.json
- packages/server/package.json
- packages/server/tsconfig.build.json
Esbuild doesn't do typechecks which is preventing us from catching some build issues
Add a postbuild script to server & dev-env that builds types as well.
> Postbuild typecheck

- packages/repo/src/repo.ts
- packages/repo/src/types.ts
- packages/repo/tests/repo.test.ts
- packages/repo/tests/sync.test.ts
Split metadata out into a node off of the root.
```ts
// type
type RepoMeta = {
did: string
version: number
datastore: string
}
// currentValues
const meta = {
did: rootUserDid,
version: 1,
datastore: 'mst',
}
```
This is mainly to future-proof the repo. For now, we just enforce that a repo's metadata can't ever change.
> Repo metadata

- packages/dev-env/src/index.ts
- packages/did-resolver/tests/resolver.test.ts
- packages/plc/bin/migration-create.ts
- packages/plc/build.js
- packages/plc/package.json
- packages/plc/src/bin.ts
- packages/plc/src/server/db.ts
- packages/plc/src/server/migrations/20221020T204908820Z-operations-init.ts
- packages/plc/src/server/migrations/index.ts
- packages/plc/tests/server.test.ts
- packages/plc/tests/util.ts
- packages/server/tests/_util.ts
The PLC server now supports the postgres dialect.  Also sets-up a system for managing incremental db migrations.  Some of this will be a little easier to review while ignoring whitespace.
> Setup PLC server with postgres and migrations

- packages/server/package.json
- packages/server/src/api/com/atproto/account.ts
- packages/server/src/db/index.ts
- packages/server/src/db/tables/user.ts
- packages/server/src/db/util.ts
- packages/server/tests/account.test.ts
Picking-up from https://github.com/bluesky-social/atproto/pull/245#discussion_r1001288568, I wanted to throw out a couple options for avoiding a. double-spends of invite codes w/o a table lock and b. multiple users claiming the same username or email.
For the first one, I think we can replace the table lock for invite_code_use with a row lock on the invite_code itself.  That should be a bit more granular, allowing different invite codes to be used in parallel without blocking each other.  I did this using a `SELECT FOR UPDATE` on postgres.  On sqlite this isn't needed since the transactions are already serialized.
The test for races for username was relying on the invite_code_use table lock.  I changed the test to show what happens when the users trying to claim the same username aren't …
> Transactional invite code use, username/email creation

- packages/auth/package.json
- packages/dev-env/build.js
- packages/pds/build.js
- packages/pds/package.json
- packages/pds/src/config.ts
- packages/plc/build.js
- packages/repo/build.js
- packages/repo/package.json
Just a little of this and that:
- Changing the leveldb externals for builds to use the same convention we started using for sqlite in #249, which is a little simpler to configure and works equally well or better.
- Add a build script to the repo package in order to list leveldb externals.
- Add some missing dependencies to packages, e.g. auth depends on did-resolver, so did-resolver has been added to auth's package.json.
- Support config overrides when using pds's `ServerConfig.readEnv()`.
> Miscellaneous dep and build fixes

- package.json
- packages/dev-env/build.js
- packages/pds/src/bin.ts
Two things:
- external dependency issue in: https://github.com/bluesky-social/atproto/issues/274
- the problem here being that `dev-env` doesn't install `better-sqlite3` itself & so needs to reference the location where it is _actually_ installed
- we weren't supply the required env variables in server/bin. For this simple setup it just sets the recovery did to the signing key
> Fix a couple build issues

- packages/common/src/types.ts
- packages/pds/src/db/records/repost.ts
This is the correct type, but it's not the `multiformats` class & doesn't give static methods.
Tired of code completion assuming I wanted this type when I want the multiformats one
> Dont reexport CID type

- packages/pds/src/api/com/atproto/account.ts
- packages/pds/src/config.ts
- packages/pds/tests/_util.ts
- packages/pds/tests/account.test.ts
The PDS's `origin` is enough to locate the service relative to the machine/network it's running on, but for the purposes of setting service endpoints in a did doc, the PDS also needs to know its public URL if it has one.  This ensures the public URL makes its way into the did doc when present.
> Add public url config to pds for setting did service endpoint

- packages/pds/src/error.ts
- packages/pds/tests/crud.test.ts
- packages/pds/tests/server.test.ts
- packages/plc/src/server/error.ts
- packages/plc/src/server/routes.ts
- packages/xrpc-server/src/server.ts
- packages/xrpc-server/src/types.ts
A few little http fixes in here:
- Avoid double-decoding route params in PLC.
- Avoid including error details from unexpected errors.
- Do not reflect user input into HTML output on PLC, move to JSON error responses on PLC.
- Check if headers are already sent in http error handlers.
- Fix an issue where 404s were turning into 500s on the PDS, resolves #273.
> Misc HTTP error fixes

- packages/README.md
Fixes a link in the packages readme, directing server/ instead to pds/.  Resolves #284
> Fix PDS readme link

- lexicons/atproto.com/createAccount.json
- lexicons/atproto.com/deleteSession.json
- lexicons/atproto.com/refreshSession.json
- packages/api/src/index.ts
- packages/api/src/schemas.ts
- packages/api/src/types/app/bsky/getUsersSearch.ts
- packages/api/src/types/com/atproto/createAccount.ts
- packages/api/src/types/com/atproto/deleteSession.ts
- packages/api/src/types/com/atproto/refreshSession.ts
- packages/dev-env/src/mock/index.ts
- packages/pds/src/api/com/atproto/account.ts
- packages/pds/src/api/com/atproto/password-reset.ts
- packages/pds/src/api/com/atproto/session.ts
- packages/pds/src/api/com/atproto/util/auth.ts
- packages/pds/src/auth.ts
- packages/pds/src/db/database-schema.ts
- packages/pds/src/db/migrations/20221021T162202001Z-init.ts
- packages/pds/src/db/migrations/provider.ts
- packages/pds/src/db/tables/refresh-token.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/schemas.ts
- packages/pds/src/lexicon/types/com/atproto/createSession.ts
- packages/pds/src/lexicon/types/com/atproto/deleteSession.ts
- packages/pds/src/lexicon/types/com/atproto/refreshSession.ts
- packages/pds/tests/account.test.ts
- packages/pds/tests/auth.test.ts
- packages/pds/tests/crud.test.ts
- packages/pds/tests/seeds/client.ts
Here we implement refresh tokens for the PDS.  When the users obtains a session, they receive to tokens: a short-lived access token and a longer-lived refresh token.
The access token is not revocable but the refresh token is revocable, and the user may revoke their session using `com.atproto.deleteSession()` e.g. during logout.
When the access token expires, `com.atproto.refreshSession()` may be used to obtain a new session containing a fresh access token and refresh token.  The refresh token used to perform the session refresh is revoked.
The overall effect is that users can stay logged-in indefinitely without providing their username and password so long as they have some activity within the window of the long-lived duration of a refresh token.
> Session refresh token for PDS

- packages/plc/README.md
Reading through this doc today and I think this a typo, or at least does not seem to follow from the preceding paragraphs.
> Fix typo in PLC docs to point to correct key for recovery

- packages/pds/src/sql-blockstore.ts
- packages/pds/tests/sql-blockstore.test.ts
Fixes a bug where the `SqlBlockstore` would hit a uniqueness error inserting the same block multiple times for the same did.  Also added a test for prevent regression.
> Allow duplicate block by the same did w/ sql blockstore

- packages/pds/src/mailer/index.ts
The password reset email was missing a subject line— this adds one in!
> Add subject to password reset email

- lexicons/app/bsky/feed/post.json
- packages/api/src/client/schemas.ts
- packages/api/src/client/types/app/bsky/feed/post.ts
- packages/pds/src/db/records/post.ts
- packages/pds/src/lexicon/schemas.ts
- packages/pds/src/lexicon/types/app/bsky/feed/post.ts
- packages/pds/tests/seeds/basic.ts
- packages/pds/tests/views/__snapshots__/author-feed.test.ts.snap
- packages/pds/tests/views/__snapshots__/notifications.test.ts.snap
- packages/pds/tests/views/__snapshots__/timeline.test.ts.snap
Changes the text slices in posts to be objects instead of tuple-like arrays. This is to be more friendly to typed languages, and to generally improve clarity.
> Rework post text slices to be objects

- lexicons/app/bsky/actor/getProfile.json
- packages/api/src/client/schemas.ts
- packages/api/src/client/types/app/bsky/actor/getProfile.ts
- packages/dev-env/src/mock/index.ts
- packages/pds/src/api/app/bsky/actor/getProfile.ts
- packages/pds/src/lexicon/schemas.ts
- packages/pds/src/lexicon/types/app/bsky/actor/getProfile.ts
- packages/pds/tests/views/__snapshots__/profile.test.ts.snap
- packages/pds/tests/views/members.test.ts
- Adds `member` to the `myState` output of `getProfile`. The value is the URI of the confirmation record.
- Adds some scene mock data to the dev environment
> Add 'member' to getProfile state output, and add some dev-env mock data

- lexicons/app/bsky/graph/getAssertions.json
- packages/api/src/client/index.ts
- packages/api/src/client/schemas.ts
- packages/api/src/client/types/app/bsky/graph/getAssertions.ts
- packages/pds/src/api/app/bsky/graph/getAssertions.ts
- packages/pds/src/api/app/bsky/index.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/schemas.ts
- packages/pds/src/lexicon/types/app/bsky/graph/getAssertions.ts
- packages/pds/tests/views/__snapshots__/assertions.test.ts.snap
- packages/pds/tests/views/assertions.test.ts
- packages/pds/tests/views/members.test.ts
- Adds `app.bsky.graph.getAssertions()`
- Can select by author and/or subject
- Can filter by confirmation status and assertion type
I need this to check on pending invites. Built it to be fairly generic.
> Add app.bsky.graph.getAssertions()

- packages/pds/src/api/app/bsky/feed/getTimeline.ts
- packages/pds/tests/views/__snapshots__/timeline.test.ts.snap
- packages/pds/tests/views/timeline.test.ts
We intentionally excluded a user's own reposts from their timeline. However there's been confusion both internally & externally (https://github.com/bluesky-social/atproto/issues/346) about this decision.
This reworks a user's own reposts back into their timeline view (both firehose & reverse-chronological)
Closes https://github.com/bluesky-social/atproto/issues/346
> Show own reposts in timeline views

- packages/handle/src/index.ts
- packages/pds/src/api/app/bsky/actor/createScene.ts
- packages/pds/src/api/com/atproto/account.ts
- Updates handles package to include a reserved handle error
- Updates PDS to respond with HandleNotAvailable with this kind of error
Need this to give better error feedback in the client
> Give 'HandleNotAvailable' error on reserved handles

- packages/pds/src/api/com/atproto/invites.ts
- packages/pds/src/config.ts
- packages/pds/tests/account.test.ts
A fix to make invite codes a little more secure and a little prettier.
> Use public hostname in invite codes

- packages/pds/src/db/index.ts
- packages/pds/src/db/message-queue/index.ts
- packages/pds/src/db/types.ts
Message queue was getting behind because for each batch of messages added (could be 1 or multiple) we were only prompting the receiver to process 1.
This fixes that & prompts `processNext` for the number of messages sent.
We also add in a sanity check interval where we process any unprocessed messages every 3 min.
Closes https://github.com/bluesky-social/atproto/issues/350
> MessageQueue fix

- packages/pds/package.json
- packages/pds/tests/_util.ts
The open handles warning we were getting was actually from the callback from shutting down the server. We wrap that in a promise to get everything shutdown nicely & throw an error if encountered.
Also snuck in a chance to just tail the logs (defaults to 50 logs) instead of piping it all through pino-prettier
> Wait for servers to close at end of test suite

- packages/repo/src/mst/mst.ts
- packages/repo/tests/mst.test.ts
Failing deletes were actually caused by 2 issues:
One stemmed from the case where a delete leaves the root of the MST pointing to only one node which is a tree. This makes it impossible to tell the layer of the root without further recursing down the tree which breaks some of our logic.
This PR includes 2 fixes:
- on stage, trim the top of the MST if it is a tree pointing to only a tree
- on load, if you need the layer of a tree, recurse until you find it. This shouldn't ever need to be done after taking into account the first fix, but it's good to have around for completeness
The second issue was the case where a key is added that is 2 layers higher than the current highest key. We have to add some empty nodes to preserve the structure. These nodes weren't getting marked as having …
> Fix a few MST bugs

- lexicons/app/bsky/actor/getProfile.json
- lexicons/app/bsky/actor/getSuggestions.json
- lexicons/app/bsky/actor/search.json
- lexicons/app/bsky/actor/searchTypeahead.json
- lexicons/app/bsky/feed/getAuthorFeed.json
- lexicons/app/bsky/feed/getPostThread.json
- lexicons/app/bsky/feed/getRepostedBy.json
- lexicons/app/bsky/feed/getTimeline.json
- lexicons/app/bsky/feed/getVotes.json
- lexicons/app/bsky/feed/post.json
- lexicons/app/bsky/graph/getAssertions.json
- lexicons/app/bsky/graph/getFollowers.json
- lexicons/app/bsky/graph/getFollows.json
- lexicons/app/bsky/graph/getMembers.json
- lexicons/app/bsky/graph/getMemberships.json
- lexicons/app/bsky/notification/getCount.json
- lexicons/app/bsky/notification/list.json
- lexicons/com/atproto/account/createInviteCode.json
- lexicons/com/atproto/repo/listRecords.json
- packages/api/src/client/schemas.ts
- packages/pds/src/lexicon/schemas.ts
Includes a fix for lexicons that were using json schema `number` where `integer` would be more appropriate.
> Use integers in lexicons

- packages/pds/package.json
- packages/pds/src/api/app/bsky/actor/search.ts
- packages/pds/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/pds/src/api/app/bsky/feed/getRepostedBy.ts
- packages/pds/src/api/app/bsky/feed/getTimeline.ts
- packages/pds/src/api/app/bsky/feed/getVotes.ts
- packages/pds/src/api/app/bsky/graph/getAssertions.ts
- packages/pds/src/api/app/bsky/graph/getFollowers.ts
- packages/pds/src/api/app/bsky/graph/getFollows.ts
- packages/pds/src/api/app/bsky/graph/getMembers.ts
- packages/pds/src/api/app/bsky/graph/getMemberships.ts
- packages/pds/src/api/app/bsky/notification/list.ts
- packages/pds/src/api/app/bsky/util/feed.ts
- packages/pds/src/api/app/bsky/util/search.ts
- packages/pds/src/db/pagination.ts
- packages/pds/src/db/util.ts
- packages/pds/tests/_util.ts
- packages/pds/tests/views/__snapshots__/assertions.test.ts.snap
- packages/pds/tests/views/__snapshots__/follows.test.ts.snap
- packages/pds/tests/views/__snapshots__/members.test.ts.snap
- packages/pds/tests/views/__snapshots__/votes.test.ts.snap
- packages/pds/tests/views/assertions.test.ts
- packages/pds/tests/views/notifications.test.ts
- yarn.lock
Make keyset cursors a tuple in the PDS in order to avoid ambiguous pagination, e.g. when paginating by datetime when datetimes need not be unique.  In these cases, we now first order by a datetime, and then in the case of a tie order by some unique field such as a URI.
> Well-defined pagination in PDS

- lexicons/app/bsky/actor/getSuggestions.json
- lexicons/app/bsky/actor/search.json
- lexicons/app/bsky/actor/searchTypeahead.json
- lexicons/app/bsky/feed/getAuthorFeed.json
- lexicons/app/bsky/feed/getRepostedBy.json
- lexicons/app/bsky/feed/getTimeline.json
- lexicons/app/bsky/feed/getVotes.json
- lexicons/app/bsky/graph/getAssertions.json
- lexicons/app/bsky/graph/getFollowers.json
- lexicons/app/bsky/graph/getFollows.json
- lexicons/app/bsky/graph/getMembers.json
- lexicons/app/bsky/graph/getMemberships.json
- lexicons/app/bsky/notification/list.json
- lexicons/com/atproto/repo/listRecords.json
- packages/api/src/client/schemas.ts
- packages/api/src/client/types/com/atproto/repo/listRecords.ts
- packages/pds/src/lexicon/schemas.ts
- packages/pds/src/lexicon/types/com/atproto/repo/listRecords.ts
Most lexicons were missing a default value for limits used in pagination.  This standardizes all limits on min: 1, max: 100, default: 50.  We can tweak that, of course— just nabbed the values that were being used for the one query that already had a min/max/default.
Closes #370
> Standardize limit schema across lexicons

- lexicons/app/bsky/feed/getPostThread.json
- packages/api/src/client/schemas.ts
- packages/api/src/client/types/app/bsky/feed/getPostThread.ts
- packages/pds/src/api/app/bsky/feed/getPostThread.ts
- packages/pds/src/lexicon/schemas.ts
- packages/pds/src/lexicon/types/app/bsky/feed/getPostThread.ts
- packages/pds/tests/views/thread.test.ts
Adds an explicit NotFound error so I can handle it better in the client.
> Add NotFoundError to getPostThread

- lexicons/app/bsky/feed/getPostThread.json
- packages/api/src/client/schemas.ts
- packages/api/src/client/types/app/bsky/feed/getPostThread.ts
- packages/pds/src/api/app/bsky/feed/getPostThread.ts
- packages/pds/src/lexicon/schemas.ts
- packages/pds/src/lexicon/types/app/bsky/feed/getPostThread.ts
- packages/pds/tests/seeds/client.ts
- packages/pds/tests/views/__snapshots__/thread.test.ts.snap
- packages/pds/tests/views/thread.test.ts
- packages/pds/tests/views/votes.test.ts
- Add a variant to the `getPostThread` output for identifying when a post is not found
- Update `getPostThread` to emit the not-found variant for ancestors on 404
> Update getPostThread to handle missing parents

- lexicons/app/bsky/feed/embed.json
- lexicons/app/bsky/feed/getPostThread.json
- lexicons/com/atproto/repo/batchWrite.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/embed.ts
- packages/api/src/client/types/app/bsky/feed/getPostThread.ts
- packages/lex-cli/src/codegen/client.ts
- packages/lex-cli/src/codegen/lex-gen.ts
- packages/lex-cli/src/codegen/server.ts
- packages/lexicon/src/types.ts
- packages/lexicon/src/util.ts
- packages/lexicon/src/validation.ts
- packages/lexicon/src/validators/complex.ts
- packages/lexicon/tests/_scaffolds/lexicons.ts
- packages/lexicon/tests/general.test.ts
- packages/pds/src/api/app/bsky/feed/getPostThread.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/embed.ts
- packages/pds/src/lexicon/types/app/bsky/feed/getPostThread.ts
- packages/pds/tests/views/__snapshots__/thread.test.ts.snap
- packages/xrpc-server/src/util.ts
Two more Lexicon updates to accommodate stricter programming languages:
- LexXrpcBody `.encoding` is now always a `string`. If multiple encodings must be specified, use a comma-separated list.
- Union discriminators
- The `union` type now only supports object-values with a `$type` field.
- The `$type` field must specify the lexicon ID being used.
- The `union` def now has a `closed` field which, if true, will fail validation if a `$type` is provided which does not match the enumerated refs.
> Lexicon tweaks: encoding and union $type discriminators

- lexicons/com/atproto/server/getAccountsConfig.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/server/getAccountsConfig.ts
- packages/dev-env/src/index.ts
- packages/pds/src/api/com/atproto/account.ts
- packages/pds/src/config.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/server/getAccountsConfig.ts
- packages/pds/tests/account.test.ts
- Adds `TERMS_OF_SERVICE_URL` and `PRIVACY_POLICY_URL` to config/env-vars
- Adds `links` object to the output of `com.atproto.server.getAccountsConfig` with the values of the policy urls
> Add terms-of-service and privacy-policy links

- packages/pds/src/repo/blobs.ts
- packages/pds/tests/file-uploads.test.ts
When blobs are uploaded, we keep track of some metadata in a `blob` table.  When the same blob is uploaded multiple times, we were seeing a db constraint issue while attempting to insert into this table.  The fix here is to update the record in the table if it already exists.
With regards to the `tempKey`, I was careful here to update it only if it wasn't `null`.  When `tempKey` is `null` it indicates the blob has been moved into permanent storage, so we don't want to indicate that the blob needs to be moved from temp to permanent storage again.  If `tempKey` is not `null` then we do update it, since the old `tempKey` could be stale (i.e. the temp blob already purged from temp storage).
> Fix issue with duped blobs

- packages/aws/package.json
- packages/aws/src/s3.ts
- yarn.lock
I was seeing an issue with the `putObject()` calls within the S3 blob store.  The issue is that the client library needs to know the length of the stream in advance.  Sounds like the way to do this is to use `Upload` from `@aws-sdk/lib-storage`.
Refs https://github.com/aws/aws-sdk-js-v3/issues/2348 https://github.com/aws/aws-sdk-js-v3/issues/1382
Error was from `S3BlobStore.putTemp (/atproto/packages/aws/src/s3.ts:39:5)`:
```
NotImplemented: A header you provided implies functionality that is not implemented
```
> Fix S3 blob store, issue putting object from a stream

- lexicons/app/bsky/actor/updateProfile.json
- lexicons/com/atproto/blob/upload.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/updateProfile.ts
- packages/api/src/client/types/com/atproto/blob/upload.ts
- packages/api/tests/errors.test.ts
- packages/lex-cli/src/codegen/client.ts
- packages/pds/package.json
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/updateProfile.ts
- packages/pds/src/lexicon/types/com/atproto/blob/upload.ts
- packages/pds/src/repo/blobs.ts
- yarn.lock
- Fix the generated procedure call signature when an encoding is `*/*` (close #391)
- Fix the named error generation for `updateProfile()`
- Add a test for named error generation
EDIT:
- Add more named blob errors and make the blob error messages more human-friendly
- The "friendlier" descriptions are so that I can just display that error directly. The other option would be to make XRPC errors more sophisticated so that they can carry data like `blobSize` and `maxBlobSize`, enabling the client to render its own error message.
> A couple lexicon-related fixes

- packages/pds/package.json
- packages/pds/src/repo/blobs.ts
- yarn.lock
The file-type package has become ESM-only, which throws a wrench in the build.  I downgraded to the most recent non-ESM version of the package.  Need to take a closer look at why the build completes successfully despite technically being broken (i.e node wont be able to run it).
> Downgrade file-type dep version, fix build

- packages/pds/src/db/records/post.ts
- packages/pds/src/db/tables/post-embed-external.ts
Kysely returns nulls, so our table types should match that
> Patch external embed table type

- packages/pds/src/api/app/bsky/util/embeds.ts
Fix for the case of an empty array being passed in to `embedsForPost`
> embedsForPost fix

- packages/dev-env/src/index.ts
- packages/pds/src/bin.ts
- packages/pds/src/index.ts
- packages/pds/tests/_util.ts
Just a small change to simplify the API of `PDS.create()`, and make it long-term compatible with `ServerConfig.fromEnv()`.
> Create PDS with ServerConfig rather than ServerConfigValues

- .gitignore
- packages/api/build.js
- packages/api/package.json
- packages/api/tsconfig.json
- Updates the API package to properly publish
- Bumps `@atproto/api` to 0.0.2
We'll need to make these updates to all the packages but I'm leaving that for now.
> Api package fixes

- .eslintrc
- packages/api/build.js
- packages/api/package.json
- packages/api/update-pkg.js
It _looks_ like running build in prepublish caused the d.ts files to get stripped, so I went ahead and separated out the update-pkg script. We could probably move that script into the root of the package but it's safer here when it's working off __dirname (no risk of using cwd and getting the wrong package json).
Related to https://github.com/bluesky-social/atproto/issues/438
> Api package fixes 2

- packages/common/src/types.ts
- packages/pds/src/api/app/bsky/actor/updateProfile.ts
- packages/pds/src/api/com/atproto/repo.ts
- packages/pds/src/repo/prepare.ts
- packages/pds/src/repo/types.ts
- packages/pds/src/services/repo/blobs.ts
- packages/pds/src/services/repo/index.ts
- packages/pds/src/sql-repo-storage.ts
- packages/pds/tests/event-stream/sync.test.ts
- packages/pds/tests/sql-repo-storage.test.ts
- packages/repo/bench/mst.bench.ts
- packages/repo/bench/repo.bench.ts
- packages/repo/src/block-map.ts
- packages/repo/src/mst/mst.ts
- packages/repo/src/repo.ts
- packages/repo/src/storage/memory-blockstore.ts
- packages/repo/src/storage/repo-storage.ts
- packages/repo/src/sync.ts
- packages/repo/src/types.ts
- packages/repo/src/util.ts
- packages/repo/tests/_util.ts
- packages/repo/tests/mst.test.ts
- packages/repo/tests/repo.test.ts
- packages/repo/tests/sync.test.ts
This adjusts the repo storage abstraction so that it understands commits.
Instead of having a staging section that then get's persisted, the application code is in charge of collecting new blocks for a commit & storage "applies a commit", saving the blocks, and associating them with some commit CID
I also snuck a change in here to the sql repo store which does some optimistic caching of repo blocks that are likely to change. This removes at least 3 (but often more) round trips to the DB on each mutation.
> Repo mutation diffs

- lexicons/app/bsky/feed/post.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/post.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/post.ts
This was just some leftovers from development of #445 that can be removed.
> Remove unmapped post.viewer.muted property

- packages/pds/src/api/com/atproto/handles.ts
- packages/pds/src/config.ts
- packages/pds/tests/account.test.ts
This fixes two bugs with resolving the server's did from `com.atproto.handle.resolve`:
- The recovery did key was being served rather than the server's PLC did.
- Passing the public hostname of the PDS as `handle` would not resolve the server did, since it was expecting the private hostname.
> Fix resolution of server did in com.atproto.handle.resolve

- packages/pds/src/repo/prepare.ts
- packages/pds/tests/event-stream/sync.test.ts
- packages/pds/tests/sync.test.ts
- packages/repo/src/repo.ts
- packages/repo/src/sync.ts
- packages/repo/src/types.ts
- packages/repo/src/util.ts
- packages/repo/tests/_util.ts
- packages/repo/tests/repo.test.ts
- packages/repo/tests/sync.test.ts
Adds a new type similar to `RecordWriteOp`: `RecordWriteDescript` which includes relevant CIDs to the operation. 
Generally "ops" are used when _making_ a change. "descripts" are used when _syncing_ a change.
Alongside this, commit-aware sync methods now return a `WriteLog` which is `RecordWriteDescript[][]` which can then be collapsed down into a single array of all writes that occurred over that range
Motivated by https://github.com/bluesky-social/atproto/pull/444#discussion_r1061677134
> Record write descriptions

- lexicons/app/bsky/actor/search.json
- lexicons/app/bsky/actor/searchTypeahead.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/search.ts
- packages/api/src/client/types/app/bsky/actor/searchTypeahead.ts
- packages/lexicon/src/validators/complex.ts
- packages/lexicon/src/validators/xrpc.ts
- packages/lexicon/tests/general.test.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/search.ts
- packages/pds/src/lexicon/types/app/bsky/actor/searchTypeahead.ts
I saw `app.bsky.feed.getAuthorFeed` 500ing when passed the parameter `?author=`.  This parameter is considered missing, so it's mapped to `undefined`, and it turns out there's a little bug in the lexicon validation for catching these `undefined`s, so I pulled together this little fix.
> Fix lexicon validation, do not allow undefined when required

- packages/pds/tests/views/__snapshots__/thread.test.ts.snap
The work in #458 was missing the fix from #453, so it caused some tests to fail once merged.  The culprit was just some out-of-date test snapshots.
> Fix out-of-date test snapshots

- packages/xrpc/src/client.ts
As of node v18.13.0 a change to the fetch spec is now reflected in node's fetch implementation.  In short, for streaming request bodies the option `duplex: 'half'` must explicitly be passed to `fetch()`.  Part of the trickiness here is that this change to the spec is not reflected in docs such as MDN yet, nor in Typescript's lib.dom types.
Refs:
Issue as surfaced in node: https://github.com/nodejs/node/issues/46221
Spec discussion: https://github.com/whatwg/fetch/issues/1438
Implementation in node: https://github.com/nodejs/undici/pull/1681
Docs on `duplex`: https://fetch.spec.whatwg.org/#ref-for-dom-requestinit-duplex
Use node's types for fetch rather than typescript's lib.dom: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60924
> Fix XRPC fetch usage for newly required duplex option

- packages/lex-cli/src/codegen/lex-gen.ts
- packages/lexicon/src/types.ts
- packages/lexicon/src/validators/complex.ts
- packages/lexicon/src/validators/xrpc.ts
- packages/lexicon/tests/_scaffolds/lexicons.ts
- packages/lexicon/tests/general.test.ts
- packages/xrpc-server/src/types.ts
- packages/xrpc-server/src/util.ts
- packages/xrpc-server/tests/parameters.test.ts
- packages/xrpc/src/util.ts
TLDR: `?param=x&param=y` ↔️ `{ param: ['x', 'y'] }`
The XRPC query and procedure parameter lexicons are constrained by their encoding as a query string, so to date we only encode and validate primitives (i.e. strings, numbers, booleans) as params.  For example, query strings don't support nested objects as you could express using JSON.
However, query strings do have the ability to encode arrays of values.  For example, if you were to post an HTML form with a multi-select checkbox element in it named `param`, it might generate a query string of the format `?param=x&param=y`, which is intended to be interpreted as `{ param: ['x', 'y'] }`.  This is also illustrated by [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) support for multi-valued keys and use …
> Add xrpc and lexicon support for param arrays

- lexicons/com/atproto/admin/getModerationActions.json
- lexicons/com/atproto/admin/getModerationReports.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/admin/getModerationActions.ts
- packages/api/src/client/types/com/atproto/admin/getModerationReports.ts
- packages/pds/src/api/com/atproto/admin/getModerationActions.ts
- packages/pds/src/api/com/atproto/admin/getModerationReports.ts
- packages/pds/src/api/com/atproto/admin/index.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/admin/getModerationActions.ts
- packages/pds/src/lexicon/types/com/atproto/admin/getModerationReports.ts
- packages/pds/src/services/moderation/index.ts
- packages/pds/tests/seeds/client.ts
- packages/pds/tests/views/admin/__snapshots__/get-moderation-actions.test.ts.snap
- packages/pds/tests/views/admin/__snapshots__/get-moderation-reports.test.ts.snap
- packages/pds/tests/views/admin/get-moderation-action.test.ts
- packages/pds/tests/views/admin/get-moderation-actions.test.ts
- packages/pds/tests/views/admin/get-moderation-report.test.ts
- packages/pds/tests/views/admin/get-moderation-reports.test.ts
- packages/pds/tests/views/admin/get-record.test.ts
- packages/pds/tests/views/admin/get-repo.test.ts
- packages/pds/tests/views/admin/repo-search.test.ts
- packages/xrpc/src/client.ts
Implements `com.atproto.admin.getModerationActions` and `com.atproto.admin.getModerationReports`, for admins to be able to browse and sort through moderation-related history.  Each supports filtering by subject, and `getModerationReports` allows filtering by whether or not the report is resolved.
> Admin view of moderation action and report history

- packages/pds/src/api/app/bsky/actor/getSuggestions.ts
- packages/pds/src/db/pagination.ts
- packages/pds/tests/views/suggestions.test.ts
Closes https://github.com/bluesky-social/atproto/issues/476
> Sort "suggested follows" by number of posts

- lexicons/com/atproto/session/create.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/admin/getModerationActions.ts
- packages/api/src/client/types/com/atproto/admin/getModerationReports.ts
- packages/api/src/client/types/com/atproto/session/create.ts
- packages/pds/src/api/com/atproto/session.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/admin/getModerationActions.ts
- packages/pds/src/lexicon/types/com/atproto/admin/getModerationReports.ts
- packages/pds/src/lexicon/types/com/atproto/session/create.ts
- packages/pds/src/services/actor.ts
- packages/pds/tests/account.test.ts
- packages/pds/tests/auth.test.ts
This allow users to create a session using their email address (in addition to their handle).  I marked session.create's `handle` input as deprecated and added an optional `identifier` input— the PDS should be free to establish any identifier it wants with its users in addition to their handle.
> Allow login using email

- packages/pds/src/api/com/atproto/password-reset.ts
- packages/pds/src/mailer/index.ts
- packages/pds/src/mailer/templates/reset-password.hbs
- packages/pds/tests/account.test.ts
Small tweak: include the user's handle in the password reset email, since people tend to forget it. Closes #486
> Include the user's handle in the reset password email

- packages/pds/src/db/migrations/20230118T223059239Z-repo-sync-data.ts
- packages/pds/src/db/tables/repo-commit-block.ts
- packages/pds/src/db/tables/repo-commit-history.ts
- packages/pds/src/sql-repo-storage.ts
One more to sneak in here
It's useful to have the did that a given commit/block is associated with. This prevents us from having to do reference counts when doing deletes. I handled the case of putting `creator` on `ipld_block` itself in the upcoming account deletion branch, but I figured I should just get these in on this migration
> Partition commit-history & commit-blocks by user did

- packages/pds/src/image/uri.ts
- packages/pds/tests/event-stream/__snapshots__/sync.test.ts.snap
- packages/pds/tests/views/__snapshots__/author-feed.test.ts.snap
- packages/pds/tests/views/__snapshots__/thread.test.ts.snap
- packages/pds/tests/views/__snapshots__/timeline.test.ts.snap
Reverts part of https://github.com/bluesky-social/atproto/pull/495
We wanted to see if changing the sizing behavior solved our image resolution issues. While it did improve things, it forced an aspect ratio that isn't ideal (for instance, very wide posts lost their sides). We increase image resolutions instead, so this PR gets us back to maintaining aspect ratios.
> Revert the feed_thumbnail to fit:inside

- packages/common/src/async.ts
- packages/common/src/index.ts
- packages/pds/package.json
- packages/pds/src/db/index.ts
- packages/pds/tests/db-notify.test.ts
- yarn.lock
Adding NOTIFY / LISTEN support to our database wrapper.
There are two cases:
- sqlite: this is a database that _only one_ application will be interacting with at any point in time. Therefore we handle notify/listen with in-process callbacks
- postgres: this is a database that _one or more_ applications may be interacting with. Therefore we handle postgres' [NOTIFY](https://www.postgresql.org/docs/current/sql-notify.html) feature
> Database notify/listen

- lexicons/app/bsky/actor/getSuggestions.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/getSuggestions.ts
- packages/pds/src/api/app/bsky/actor/getSuggestions.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/getSuggestions.ts
- packages/pds/tests/views/suggestions.test.ts
Update `app.bsky.actor.getSuggestions` to not return the requesting user or any users that they already follow.
Also remove `myState` from the lexicon because it is no longer used (since the follow will always be `undefined`).
Closes https://github.com/bluesky-social/atproto/issues/497
> Filter out self & follows from suggestions

- packages/pds/src/api/app/bsky/actor/updateProfile.ts
- packages/pds/src/api/app/bsky/feed/setVote.ts
- packages/pds/src/api/com/atproto/account/create.ts
- packages/pds/src/api/com/atproto/repo.ts
- packages/pds/src/services/repo/index.ts
- packages/pds/tests/event-stream/sync.test.ts
- packages/pds/tests/migrations/repo-sync-data.test.ts
- packages/repo/src/repo.ts
- packages/repo/tests/_util.ts
- packages/repo/tests/repo.test.ts
This mostly just moves things around in the PDS's repo indexing in the hopes of avoiding a few footguns.
Using it in https://github.com/bluesky-social/atproto/pull/518 where I was adding another step to processing & realizing it could be very easily glossed over & cause some footguns
Also refigures the `@atproto/repo` package just a bit to knock out a `@TODO` that's been there for some time
> Refactor repo indexing

- packages/pg/with-test-db.sh
This one kept biting me so I decided to knock it out.
Basically intercept SIGINT, & stop docker before existing.
Output is a bit ugly, bash isn't my forte lol. But it at least stops old volumes from sticking around
> Handle SIGINT in postgres script

- lexicons/com/atproto/sync/getRepo.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/sync/getRepo.ts
- packages/pds/src/api/com/atproto/sync.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/sync/getRepo.ts
- packages/pds/tests/sync.test.ts
`com.atproto.sync.getRepo` now takes a commit range: `earliest` (exclusive) to `latest` (inclusive)
closes https://github.com/bluesky-social/atproto/issues/516
> Allow syncing a commit range

- packages/pds/src/db/migrations/20230208T081544325Z-post-hydrate-indices.ts
- packages/pds/src/db/migrations/index.ts
NOTE: the name of the migration might need to change, as there are other PRs in flight.
I wrote this pretty quickly and have no prior experience with `kysely`, should be reviewed carefully before pushing this out.
These are some high-priority indices that yielded around a 5x improvement on single-threaded query latency in my local (laptop) testing on a small database for important XRPC endpoints like "getTimeline", "getPostThread", "getProfile", and fetching notifications (list or count).
These endpoints still seem pretty slow to me (tens of millis SQL execution time), but the speedup is quite cheap (there aren't many indices on these tables yet, and index creation should be fairly fast). We may refactor the aggregation stuff in the near future, but until then I think these are helpful.
> pds sql: add indices for feed and post aggregations

- lexicons/com/atproto/admin/getModerationAction.json
- lexicons/com/atproto/admin/getModerationReport.json
- packages/api/src/client/lexicons.ts
- packages/pds/src/lexicon/lexicons.ts
The `id` parameter for getting a mod action and reports was spec'ed as a `number` when it should have been an `integer`.
> Mod action and report params as integers rather than floats

- .gitignore
- LICENSE
- Makefile
- packages/pds/example.dev.env
- packages/pds/package.json
- packages/pds/src/bin.ts
- packages/pds/src/env.ts
- packages/plc/example.dev.env
- packages/plc/src/bin.ts
- packages/plc/src/env.ts
A small grab-bag of edits from my working tree.
It took a while to get PLC and PDS running with log lines printing out as expected in my terminal. There were issues with dotenv and logging (due to library import priority), and needing to pipe the log JSON through `pino-pretty`.
Was getting a yellow warning line repeatedly about the missing `"license"` line in PDS.
I personally find it really helpful to have a language-agnostic `Makefile`, because I always forget what tool set is being used for what projects. It is kind of opinionated and old-fashioned.
I'm happy to cherry pick / rebase / whatever if only some of these should get merged to `main`.
> some small low-priority patches

- lexicons/app/bsky/actor/updateProfile.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/updateProfile.ts
- packages/lex-cli/src/codegen/lex-gen.ts
- packages/lexicon/src/types.ts
- packages/lexicon/src/validators/complex.ts
- packages/pds/src/api/app/bsky/actor/updateProfile.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/updateProfile.ts
- packages/pds/tests/views/__snapshots__/profile.test.ts.snap
- packages/pds/tests/views/profile.test.ts
A few steps here, in order to allow unsetting profile images and descriptions in the `app.bsky.actor.updateProfile` method.
- Add support for `nullable` on lexicon object types, spec'ed similarly to `required`.
- Add `nullable` to codegen.
- Alter lexicons and implementation of `updateProfile` to allow unsetting avatar, banner, and description.
> Allow unsetting profile images and description in updateProfile

- packages/common/tests/async.test.ts
Just widened the thresholds here. If we continue to hit these, we may need a diff approach to timing tests
Closes https://github.com/bluesky-social/atproto/issues/557
> Bugfix: Flaky readFromGenerator test

- packages/api/build.js
Now that the api package is used by the PDS, as of #555, the api package needs a little tweak to its build script.
> Fix PDS build, updating main to dist in api package

- packages/pds/tests/handles.test.ts
- packages/plc/src/server/routes.ts
- packages/plc/tests/server.test.ts
I'm currently refactoring the PLC data model.
Fortunately there are no currently existing operations on PLC apart from `create`s. 
We will no longer support the other currently implemented operations. 
This temporarily throws on every operation apart from a `create` until I wrap up the refactor.
> Temporarily disable PLC mutations

- packages/repo/src/mst/mst.ts
- packages/repo/tests/mst.test.ts
In particular, ports the older fanout=32 corner-case tests to fanout=16. I generated new paths with correct level and ordering, but haven't actually verified that the resulting structures have the shape of the ASCII diagrams in text.
Added a couple tests demonstrating the weirdness of "wide" (non-ASCII) characters in MST key paths. The "right thing to do" is probably to change the MST keys from "string" to "bytes", but that will change an IPLD field type, which changes encoding/serialization/deserialization, so would be tricky to roll out.
Many of these tests are being used as early interoperability tests cross-language. AKA, have implemented the exact same tests in golang (indigo) and rust (adenosine), and are working through inconsistencies.
(still work in progress as I confirm that …
> MST review and tests

- lexicons/com/atproto/sync/subscribeAllRepos.json
- packages/api/src/client/lexicons.ts
- packages/pds/src/api/com/atproto/sync/subscribeAllRepos.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/sync/subscribeAllRepos.ts
- packages/pds/tests/sync/subscribe-all-repos.test.ts
Couple tweaks
- `prev` is nullable instead of optional
- `cursor` can be set to `0`
Closes https://github.com/bluesky-social/atproto/issues/577
> Sync subscription tweaks

- packages/pds/src/db/leader.ts
- packages/pds/tests/db.test.ts
Adds some tooling to help coordinate multiple app views so that only one of them— i.e. the leader—runs a given task at a time.  This will be combined with #603 in order to ensure that there's only one consumer of events from the BGS at a time.
> Running a task as a leader in the app view

- lexicons/com/atproto/sync/notifyOfUpdate.json
- lexicons/com/atproto/sync/requestCrawl.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/sync/notifyOfUpdate.ts
- packages/api/src/client/types/com/atproto/sync/requestCrawl.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/sync/notifyOfUpdate.ts
- packages/pds/src/lexicon/types/com/atproto/sync/requestCrawl.ts
Two very simple sync routes:
- `requestCrawl` for a service to crawl you until further notice
- `notifyOfUpdate`: "dingdong". let a disconnected crawler know that you have an update waiting for them
> Crawler schemas

- packages/pds/src/sequencer/outbox.ts
Just some follow-on to #599 to ensure `subscribeAllRepos` behaves correctly when the `cursor` param is 0.
> Ensure subscribeAllRepos syncs from cursor 0

- lexicons/com/atproto/sync/subscribeAllRepos.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/sync/subscribeAllRepos.ts
- packages/pds/src/api/com/atproto/sync/subscribeAllRepos.ts
- packages/pds/src/db/database-schema.ts
- packages/pds/src/db/migrations/20230301T222603402Z-repo-ops.ts
- packages/pds/src/db/migrations/index.ts
- packages/pds/src/db/tables/repo-op.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/sync/subscribeAllRepos.ts
- packages/pds/src/sequencer/index.ts
- packages/pds/src/services/repo/index.ts
- packages/pds/tests/sync/subscribe-all-repos.test.ts
Adds repo ops to sync stream.
We track ops alongside writes.
We don't bother backfilling old ops, instead we just reset the sequenced history (by deleting old rows)
> Repo ops on sync stream

- packages/api/README.md
The correct required keys for `agent.api.com.atproto.repo.listRecords` are `user` and `collection`.
ref: https://atproto.com/lexicons/com-atproto-repo#comatprotorepolistrecords
> Fix README.md

- packages/pds/src/auth.ts
The refresh token lifetime can be much longer, particularly because they are rotated on each use.  This bumps their lifetime up from 7 to 90 days.
Our access token lifetimes were also quite conservative, and have been lengthened for more practical/everyday usage.  This bumps their lifetime up from 15 to 120 mins.
> Lengthen token lifetimes

- packages/pds/src/app-view/api/app/bsky/feed/getAuthorFeed.ts
- packages/pds/src/app-view/api/app/bsky/feed/getTimeline.ts
- packages/pds/src/services/util/search.ts
In the author feed, timeline feed, and user search there are cases where we're using UNION where we can be using UNION ALLs, which tells the database it doesn't need to do the work of deduping the result set.  Here's why we can switch them in each case:
- The timeline feed unions posts and reposts, and they each have a fixed `type` column which is either `'post'` or `'repost'`.  So we know ahead of time that there will not be duplicates across the result sets, as the `type` can't match.
- The author feed works the same as the timeline in this respect 👆 
- The user search queries union accounts and profiles, then chooses the best result from their combination.  In this case we are already deduping after the union using a `distinct on`, so we don't need to ask postgres to do the work of …
> Feed and search query perf tuning

- packages/handle/README.md
It seems that 4th example is meant to demonstrate  unhappy path of `ensureValid`, but not `isValid`.
> Fix README of handle package

- packages/pds/src/api/com/atproto/handle.ts
- packages/pds/tests/account.test.ts
- packages/pds/tests/handles.test.ts
We were being a bit aggressive with errors & they were getting returned as 500s.
This also changes it so that we do not resolve the domain of the PDS to a DID. We have not yet established whether services in the network should have handles.
> Handle fixes

- packages/pds/src/api/com/atproto/account/createInviteCode.ts
- packages/pds/tests/account.test.ts
Format invite codes with dashes instead of dots so that they are not mistaken for links:
`bsky.social-abc12 -> bsky-social-abc12`
> Format invite codes with dashes

- packages/pds/src/api/com/atproto/handle.ts
- packages/pds/tests/handles.test.ts
The server was not properly bailing out here & was recursively calling itself to try to resolve it's own handle
> Bugfix: resolving the root of an available domain

- packages/repo/src/data-diff.ts
- packages/repo/src/mst/diff.ts
- packages/repo/src/mst/mst.ts
Two fixes in here: 
- fixes the problem with finding records in proofs
- we were recursing into `walk` instead of `walkReachable` which was throwing
- fixes an issue with overeager diffs
- we were tracking "new cids" that weren't actually "new", they were just in a different location in the MST. so now we track "removed" cids as well & dedupe this in a similar way to how we handle adds + deletes
Closes https://github.com/bluesky-social/atproto/issues/543
> MST util bug fixes for sync

- lexicons/com/atproto/sync/notifyOfUpdate.json
- lexicons/com/atproto/sync/requestCrawl.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/sync/notifyOfUpdate.ts
- packages/api/src/client/types/com/atproto/sync/requestCrawl.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/sync/notifyOfUpdate.ts
- packages/pds/src/lexicon/types/com/atproto/sync/requestCrawl.ts
Small tweak that adds `hostname` param to `com.atproto.sync.notifyOfUpdate`
Also the `required` value on `requestCrawl` was different from the property value so I standardized that on `hostname` as well
> Add hostname param to notifyOfUpdate

- packages/pds/src/app-migrations/remove-declarations.ts
- packages/pds/src/app-migrations/update-follow-subjects.ts
Two app migrations contained here:
1. Remove declaration, assertion, and confirmation records.
2. Update follow records so that their `subject` is a did rather than an actor ref.  Invalid follow records are deleted.
In both we use the repo service, which takes care of updating repositories plus the generic `record` index.  If any app-view related changes are needed, those are handled at the end of the migrations— that would include updates to `duplicate_record` and `follow` tables.  A no-op `messageDispatcher` is used rather than a real one in order to avoid app-view indexing logic from kicking in.
> Lexicon: declaration, assertion/confirmation, follow app migration

- packages/pds/src/app-migrations/remove-declarations.ts
- packages/pds/src/app-migrations/update-follow-subjects.ts
- packages/pds/src/app-migrations/votes-to-likes.ts
Contains the app migration to turn votes into likes.
Using the repo service here similar to #664, which takes care of updating repositories plus the generic record index. App-view related changes are handled at the end of the migrations— that would include updates to `duplicate_record` and `like` tables, in particular updating uris and cids.  A no-op `messageDispatcher` is used rather than a real one in order to avoid app-view indexing logic from kicking in.  The rkeys of the vote records are preserved into the like records.
> Lexicon: votes to likes app migration

- lexicons/app/bsky/actor/defs.json
- lexicons/app/bsky/feed/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/defs.ts
- packages/api/src/client/types/app/bsky/feed/defs.ts
- packages/pds/src/app-view/services/actor/views.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
- packages/pds/src/lexicon/types/app/bsky/feed/defs.ts
- packages/pds/tests/__snapshots__/indexing.test.ts.snap
- packages/pds/tests/views/__snapshots__/author-feed.test.ts.snap
- packages/pds/tests/views/__snapshots__/profile.test.ts.snap
- packages/pds/tests/views/author-feed.test.ts
- packages/pds/tests/views/profile.test.ts
- packages/pds/tests/views/thread.test.ts
This makes the aggregated count fields on post and profile views (e.g. `post.likeCount`, `profile.followCount`) optional.   Also made `viewer` state optional on the post view, since it falls into a similar category and is already optional on other views.  Finally, I removed the deprecated `myState` field on the profile view.
Resolves #589
> Lexicon: optional aggregated fields on views

- packages/pds/src/sequencer/index.ts
We do an _inner join_ (instead of a left join) on repo history to ensure that we're only emitting events for commits that we still have around
> Bugfix: don't emit events lost commits

- lexicons/app/bsky/embed/external.json
- lexicons/app/bsky/embed/images.json
- lexicons/app/bsky/embed/record.json
- lexicons/app/bsky/feed/defs.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/embed/external.ts
- packages/api/src/client/types/app/bsky/embed/images.ts
- packages/api/src/client/types/app/bsky/embed/record.ts
- packages/api/src/client/types/app/bsky/feed/defs.ts
- packages/pds/src/app-view/services/feed/index.ts
- packages/pds/src/app-view/services/feed/types.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/embed/external.ts
- packages/pds/src/lexicon/types/app/bsky/embed/images.ts
- packages/pds/src/lexicon/types/app/bsky/embed/record.ts
- packages/pds/src/lexicon/types/app/bsky/feed/defs.ts
- packages/pds/tests/event-stream/__snapshots__/sync.test.ts.snap
- packages/pds/tests/seeds/basic.ts
- packages/pds/tests/views/__snapshots__/author-feed.test.ts.snap
- packages/pds/tests/views/__snapshots__/notifications.test.ts.snap
- packages/pds/tests/views/__snapshots__/thread.test.ts.snap
- packages/pds/tests/views/__snapshots__/timeline.test.ts.snap
A few changes to record embeds in here:
- Embed view lexicons are named as `#view` rather than `#presented`, for consistency.
- Embed views now have a standard wrapper shape `{ $type, value }`, whereas before we had different keys `{ $type, record }`, `{ $type, external }`, etc.  That wasn't necessary since `$type` acts as a discriminator for the wrapped value.  One small upside there is that the record under a record embed is now `(embed.value).record` rather than `(embed.record).record`, which feels a little nicer to write.
- Record embed views now contain `embeds` which can include one or more views of embeds found within the record.  If there are multiple, it would be up to the consumer to distinguish them by inspecting `embed.value.record`.  Embeds are only hydrated one level deep.
- …
> Lexicon: embeds in record embeds

- lexicons/app/bsky/notification/listNotifications.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/notification/listNotifications.ts
- packages/pds/src/app-view/services/indexing/plugins/post.ts
- packages/pds/src/event-stream/messages.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/notification/listNotifications.ts
- packages/pds/tests/views/__snapshots__/notifications.test.ts.snap
- packages/pds/tests/views/notifications.test.ts
When users are quoted via a record embed they receive a `quote` notification.
Resolves #619 in concert w/ #691
> Lexicon: notify users when they are quoted

- packages/identifier/README.md
Hi amazing developers,
I found a commit that was recently merged into main that has not had the README fixed.
In `identifier`, `isValid` and `ensureValid` are no longer used, so I replaced them with the handle and did functions instead.
> docs: fixed outdated usage

- packages/api/src/agent.ts
- packages/api/src/types.ts
Fixed a typo in the type name `AptAgentFetchHandler`, to `AtpAgentFetchHandler`.
> Fix typo: AptAgentFetchHandler

- .github/workflows/repo.yaml
The intent is to run basic CI against third-party PRs (aka, open source contributions).
This is helpful for us reviewing things, but raises security concerns, because it allows third party code to run under our CI context.
Quick background reading on the difference between `pull_request` and `pull_request_target`, and other PR security concerns:
- https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
- https://securitylab.github.com/research/github-actions-building-blocks/
I don't have admin on this repo (`atproto`), but the following changes should be checked (or updated) before merging this branch, under the "Settings > Actions" tab:
- "Fork pull request workflows from outside collaborators" -> Require approval for first time contributors. Seems like a good …
> CI: run on pull requests, not just pushes

- lexicons/com/atproto/repo/applyWrites.json
- lexicons/com/atproto/repo/createRecord.json
- lexicons/com/atproto/repo/deleteRecord.json
- lexicons/com/atproto/repo/putRecord.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/repo/applyWrites.ts
- packages/api/src/client/types/com/atproto/repo/createRecord.ts
- packages/api/src/client/types/com/atproto/repo/deleteRecord.ts
- packages/api/src/client/types/com/atproto/repo/putRecord.ts
- packages/dev-env/src/mock/index.ts
- packages/pds/src/api/com/atproto/repo/applyWrites.ts
- packages/pds/src/api/com/atproto/repo/createRecord.ts
- packages/pds/src/api/com/atproto/repo/deleteRecord.ts
- packages/pds/src/api/com/atproto/repo/getRecord.ts
- packages/pds/src/api/com/atproto/repo/putRecord.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/repo/applyWrites.ts
- packages/pds/src/lexicon/types/com/atproto/repo/createRecord.ts
- packages/pds/src/lexicon/types/com/atproto/repo/deleteRecord.ts
- packages/pds/src/lexicon/types/com/atproto/repo/putRecord.ts
- packages/pds/tests/crud.test.ts
- packages/pds/tests/file-uploads.test.ts
- packages/pds/tests/seeds/client.ts
- packages/pds/tests/subscription/repo.test.ts
- packages/pds/tests/sync/sync.test.ts
- packages/pds/tests/views/profile.test.ts
This unifies all the `com.atproto.repo.*` xrpc methods so that the repo to read/write to is specified with a `repo` field, which can be an at-identifier (i.e. did or handle). Previously the write endpoints instead took a `did` field as an input, while the read endpoints a `repo`.
> Lexicon: standardize record repo interfaces

- packages/api/README.md
- packages/api/docs/rn-fetch-handler.ts
- packages/api/src/index.ts
These exports are needed for writing a custom fetch handler and generally if you're manipulating blob refs. I also updated the api docs for the other ~poor saps~ engineers using react native.
> Add exports to api package: blobref & lex/json converters

- packages/common-web/src/async.ts
- packages/dev-env/src/mock/index.ts
- packages/pds/src/api/com/atproto/admin/reverseModerationAction.ts
- packages/pds/src/api/com/atproto/admin/takeModerationAction.ts
- packages/pds/src/api/com/atproto/moderation/util.ts
- packages/pds/src/app-migrations/update-db-nsids.ts
- packages/pds/src/db/tables/moderation.ts
- packages/pds/src/services/moderation/index.ts
- packages/pds/src/services/moderation/views.ts
- packages/pds/tests/crud.test.ts
- packages/pds/tests/moderation.test.ts
- packages/pds/tests/views/admin/get-moderation-action.test.ts
- packages/pds/tests/views/admin/get-moderation-actions.test.ts
- packages/pds/tests/views/admin/get-moderation-report.test.ts
- packages/pds/tests/views/admin/get-moderation-reports.test.ts
- packages/pds/tests/views/admin/get-record.test.ts
- packages/pds/tests/views/author-feed.test.ts
- packages/pds/tests/views/notifications.test.ts
- packages/pds/tests/views/thread.test.ts
- packages/pds/tests/views/timeline.test.ts
In the lex refactor's "big renaming" `com.atproto.repo.recordRef` was removed in favor of `strongRef`, but was still kicking around in the pds admin/moderation tooling.  This fixes that.  Also one tiny change to an unrelated utility to make some type checking happy.
> Lexicon: fix lingering references to recordRef

- packages/pds/src/app-migrations/remove-scenes.ts
This is an app migration for deleting the accounts of scenes.
We grab all scenes from the `did_handle` table & then call the delete methods on each relevant service - as we would in `com.atproto.account.delete`
This should be run _before_ deploying https://github.com/bluesky-social/atproto/pull/658
> Delete scenes app migration

- lexicons/app/bsky/richtext/facet.json
- packages/api/README.md
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/richtext/facet.ts
- packages/api/src/rich-text/detection.ts
- packages/api/src/rich-text/rich-text.ts
- packages/api/src/rich-text/unicode.ts
- packages/api/tests/rich-text-detection.test.ts
- packages/api/tests/rich-text-sanitization.test.ts
- packages/api/tests/rich-text.test.ts
- packages/pds/src/app-view/services/indexing/plugins/post.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/richtext/facet.ts
- packages/pds/tests/__snapshots__/indexing.test.ts.snap
- packages/pds/tests/event-stream/__snapshots__/sync.test.ts.snap
- packages/pds/tests/indexing.test.ts
- packages/pds/tests/seeds/basic.ts
- packages/pds/tests/seeds/client.ts
- packages/pds/tests/views/__snapshots__/author-feed.test.ts.snap
- packages/pds/tests/views/__snapshots__/notifications.test.ts.snap
- packages/pds/tests/views/__snapshots__/timeline.test.ts.snap
Two changes to richtext facets:
- Each facet can have multiple "features", rather than a single "value."
- The slice within the facet now more clearly deals with utf8 bytes rather than e.g. javascript string indexes.
> Lexicon: facet features

- packages/pds/src/services/moderation/views.ts
- packages/pds/tests/views/admin/__snapshots__/get-moderation-action.test.ts.snap
- packages/pds/tests/views/admin/__snapshots__/get-moderation-report.test.ts.snap
A lingering two NSIDs from the "big renaming" needed to be updated in the admin repo and record views.
> Lexicon: fix to presentation of admin repo/record views

- packages/common-web/src/ipld.ts
- packages/lexicon/src/serialize.ts
We were getting an unfriendly slowdown in the lex-refactor, and traced it down pretty exclusively to the new de/serialization processing.  By moving away from our `check.is()` system to simple checks wherever possible during de/serialization, we get a big speedup.
> Lexicon: optimize lex de/serialization

- packages/pds/src/app-migrations/like-follow-notifications.ts
The app migration from #733 was intended to update the notification `reason` in addition to the record uris, for like notifications.
> Lexicon: notification reason fix

- packages/crypto/src/p256/keypair.ts
- packages/crypto/src/p256/operations.ts
- packages/crypto/tests/keypairs.test.ts
The fundamental problem here that we were passing in an underlying ArrayBuffer from the cbor decoding library to webcrypto instead of the typed array.
For context: A TypedArray (Uint8Array or Buffer) in node is a _view_ into an underlying ArrayBuffer. The cbor encoding library must use ArrayBuffers under the hood & then pass back a slice of that ArrayBuffer as a Buffer. We then passed in the underlying ArrayBuffer which was larger than the actual data itself, thereby signing the wrong data.
The cbor decoding library would use an ArrayBuffer of size 128 as long as the data payload was <=128 & then 8kb if larger. A commit without a `prev` is <128 & a commit with a `prev` is > 128, thus why this was only happening on subsequent commits.
We were not running into this in the past because our …
> Use TypedArrays instead of ArrayBuffers with WebCrypto

- packages/pds/src/app-view/services/actor/views.ts
- packages/pds/src/app-view/services/feed/index.ts
The trailing replacement character was allowing the output in certain cases to remain over the desired truncated length.
> Remove trailing replacement character when utf8-truncating

- packages/pds/src/app-view/api/app/bsky/util/feed.ts
- packages/pds/tests/event-stream/__snapshots__/sync.test.ts.snap
- packages/pds/tests/views/__snapshots__/author-feed.test.ts.snap
- packages/pds/tests/views/__snapshots__/timeline.test.ts.snap
Missed a spot when refactoring feed definitions.
The old reference no longer exists.
> Update reason type in `feed.ts`

- packages/api/package.json
- packages/pds/package.json
Publishes new packages for https://github.com/bluesky-social/atproto/pull/756
- api@0.2.2
- pds@0.1.1
> Pkg bumps after #756

- lexicons/com/atproto/server/createSession.json
- packages/api/src/agent.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/server/createSession.ts
- packages/api/src/types.ts
- packages/api/tests/agent.test.ts
- packages/pds/src/api/com/atproto/server/createSession.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/server/createSession.ts
- packages/pds/tests/account.test.ts
This PR:
- Adds an optional `email` to `com.atproto.server.createSession` response
- Updates the api package to store email in the session data it tracks
> Add email to createSession

- lexicons/com/atproto/repo/listRecords.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/repo/listRecords.ts
- packages/pds/src/api/com/atproto/repo/listRecords.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/repo/listRecords.ts
- packages/pds/src/services/record/index.ts
- packages/pds/tests/crud.test.ts
Switches pagination in `listRecords` from `rkeyStart` & `rkeyEnd` to `cursor`.
This makes the semantics match other pagination routes. rkeyStart/End were not clear & leading to uncertainty. They would only be used for requesting some internal range of rkeys which just does not seem like a common usecase.
I've left those parameters around for now but marked them deprecated. I propose we switch the client over, wait a week or two & then actually remove them.
> Paginate listRecords based on cursor

- lexicons/com/atproto/admin/defs.json
- packages/pds/src/api/com/atproto/admin/searchRepos.ts
- packages/pds/src/services/account/index.ts
- packages/pds/src/services/moderation/views.ts
- packages/pds/src/services/util/search.ts
- packages/pds/tests/views/admin/__snapshots__/get-repo.test.ts.snap
- packages/pds/tests/views/admin/invites.test.ts
A few things:
- add filter by `invitedBy` on search
- this only works on a _blank_ term, otherwise we were having to jam a bunch of invite logic into our search functionality which didn't feel great. & also doesn't seem like a common usecase
- add some tests for admin views
- makes searchRepos only return `invitedBy` & getRepo return `invitedBy` & `invites`. since `invites` is a larger value, we may not want to run it on every search
> Improve admin invite code views

- packages/pds/src/app-view/api/app/bsky/unspecced.ts
Some SQL changes to speed up getPopular.
Does a count check in a where clause instead of joining on a count table. Some quick testing suggests a ~3-4x improvement.
> Improve getPopular

- packages/uri/package.json
- packages/uri/src/index.ts
- packages/uri/tests/uri.test.ts
Users with numbers in their handles are getting cryptic "Error: uri must be a valid at-uri" messages when the app tries to load their threads. Turns out I botched the grammar for hostnames here.
> Fix AtUri parse on hostnames that start with numbers

- packages/aws/src/cloudfront.ts
- packages/pds/service/index.js
- yarn.lock
The cloudfront CDN may serve images at a specific path prefix, depending on the deployment.  This accounts for that in the invalidation flow.
> Account for possible path prefix in cloudfront invalidation

- packages/bsky/tests/_util.ts
- packages/bsky/tests/indexing.test.ts
- packages/bsky/tests/server.test.ts
- packages/bsky/tests/subscription/repo.test.ts
- packages/bsky/tests/views/actor-search.test.ts
A few spots where CI did not spot about a possibly `undefined` var.
And fix up PDS in bsky test cfg with new invite code var
> Cleanup appview merge

- packages/bsky/src/config.ts
- packages/bsky/src/index.ts
- packages/pds/src/config.ts
- packages/pds/src/index.ts
Output validation generally isn't needed outside of debug mode.  We may want to consider validating a sample output in the future when not in debug mode.
> Disable output validation when not in debug mode

- lexicons/com/atproto/admin/updateAccountHandle.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/admin/updateAccountHandle.ts
- packages/pds/src/api/com/atproto/admin/index.ts
- packages/pds/src/api/com/atproto/admin/updateAccountHandle.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/admin/updateAccountHandle.ts
- packages/pds/tests/handles.test.ts
Admin route for updating a handle of an account on service. Note: this only allows you to update a handle _currently on the service_ to another handle _also on the service_
> Admin update handle

- packages/pds/src/app-view/services/indexing/index.ts
- packages/pds/src/services/index.ts
- packages/pds/src/services/repo/index.ts
Record was getting sent off to labeling before it had been moved to permanent blob storage.
We temporarily move labeling to the pds repo service so that we can run it after the blob is processed. This will quickly be moved to appview
> Fix race condition in labeling

- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/admin/updateAccountEmail.ts
- packages/bsky/src/lexicon/types/com/atproto/label/subscribeLabels.ts
- packages/bsky/src/lexicon/types/com/atproto/sync/subscribeRepos.ts
- packages/lex-cli/src/codegen/server.ts
- packages/pds/src/api/com/atproto/sync/subscribeRepos.ts
- packages/pds/src/lexicon/types/com/atproto/label/subscribeLabels.ts
- packages/pds/src/lexicon/types/com/atproto/sync/subscribeRepos.ts
- packages/pds/src/sequencer/outbox.ts
- packages/pds/tests/sync/subscribe-repos.test.ts
- packages/xrpc-server/src/server.ts
- packages/xrpc-server/src/stream/server.ts
- packages/xrpc-server/src/types.ts
When the xrpc subscription on `subscribeRepos` forcibly ends, we now stop the outbox's subscription to the event sequencer.
> Stop sequencer listener in outbox when subscription aborts

- packages/dev-env/src/test-env.ts
- packages/pds/src/api/com/atproto/repo/getRecord.ts
Remove `indexedAt` & `takedownId` from `getRecord`. These are returned by an internal service & were not being properly stripped out
closes https://github.com/bluesky-social/atproto/issues/831
> Remove extraneous info on getRecord

- packages/crypto/src/did.ts
The "BASE58_DID_PREFIX" constant in `const.ts` was unused, but the same constant value was declared twice in `did.ts`
> Fix duplication of constants in the crypto package

- packages/bsky/src/api/app/bsky/notification/listNotifications.ts
- packages/bsky/tests/views/notifications.test.ts
- packages/pds/src/api/app/bsky/notification/listNotifications.ts
- packages/pds/tests/views/notifications.test.ts
From chat in https://github.com/bluesky-social/atproto/pull/839
Let's do the general solution of just not returning any notifications for a deleted subject
> Do not give notifs for a deleted subject

- packages/bsky/package.json
- packages/dev-env/package.json
- packages/dev-env/tsconfig.json
- packages/pds/package.json
- yarn.lock
Bump node-postgres from 8.8.0 to 8.10.0
Specifically v8.10.0 includes a fix that has emits a "release" event when a client is returned to the pool:
https://github.com/brianc/node-postgres/pull/2845
> Bump node-postgres version

- packages/pds/src/sql-repo-storage.ts
- packages/pds/tests/crud.test.ts
- packages/pds/tests/sql-repo-storage.test.ts
- packages/pds/tests/sync/subscribe-repos.test.ts
- packages/pds/tests/views/profile.test.ts
We have to linearize writes to repos as they come in.
Right now we do that by taking out a row lock with SELECT FOR UPDATE.
However, many operations against the same repo can result in lock contention which spikes cpu & hogs connections in the pool.
Instead we:
- do a SELECT FOR UPDATE SKIP LOCKED
- if we skip over a locked row, then we wait 200ms, in the hopes that the previous operation will succeed & then try again
- if it fails again, we through a 400 error for attempting too many concurrent updates
Clients that have legitimate reasons for doing large writes can do so with `applyWrites` or serialize their write requests.
We can tweak this approach as we go. perhaps with more checks and/or a shorter wait period.
> Skip locked repos instead of waiting for lock

- packages/pds/src/app-view/api/app/bsky/unspecced.ts
- packages/pds/tests/views/popular.test.ts
> Increase getPopular likes to 8

- packages/bsky/tests/indexing.test.ts
- packages/pds/src/api/com/atproto/repo/applyWrites.ts
- packages/pds/src/api/com/atproto/repo/createRecord.ts
- packages/pds/src/api/com/atproto/repo/deleteRecord.ts
- packages/pds/src/api/com/atproto/repo/putRecord.ts
- packages/pds/src/db/index.ts
- packages/pds/src/services/repo/index.ts
- packages/pds/src/sql-repo-storage.ts
- packages/pds/tests/indexing.test.ts
- packages/pds/tests/races.test.ts
- packages/pds/tests/sql-repo-storage.test.ts
This moves formatting of commits outside of the write transactions so that they do not hold up connections from the pool.
For each write, we attempt up to 10 times with a 100ms delay between each. Each attempt only takes some short reprocessing where we replay the commit on top of the current state of the repo (if the lock is up). We use a persistent `SqlRepoStorage` instance between attempts so that already computed blocks can be cached & not re-fetched from storage
> Format commits outside of tx

- packages/pds/src/api/com/atproto/admin/getInviteCodes.ts
- packages/pds/src/api/com/atproto/admin/getModerationAction.ts
- packages/pds/src/api/com/atproto/admin/getModerationActions.ts
- packages/pds/src/api/com/atproto/admin/getModerationReport.ts
- packages/pds/src/api/com/atproto/admin/getModerationReports.ts
- packages/pds/src/api/com/atproto/admin/getRecord.ts
- packages/pds/src/api/com/atproto/admin/getRepo.ts
- packages/pds/src/api/com/atproto/admin/resolveModerationReports.ts
- packages/pds/src/api/com/atproto/admin/searchRepos.ts
- packages/pds/src/api/com/atproto/admin/takeModerationAction.ts
- packages/pds/src/auth.ts
- packages/pds/src/config.ts
- packages/pds/src/context.ts
- packages/pds/src/index.ts
- packages/pds/tests/_util.ts
- packages/pds/tests/account.test.ts
- packages/pds/tests/handles.test.ts
- packages/pds/tests/moderation.test.ts
- packages/pds/tests/views/admin/invites.test.ts
Simple extension to the PDS admin credentials, used for non-critical moderation tasks: primarily closing reports with flags or acknowledgements.  The following endpoints remain admin-only:
- `com.atproto.server.createInviteCodes`
- `com.atproto.server.createInviteCode`
- `com.atproto.admin.reverseModerationAction`
- `com.atproto.admin.updateAccountEmail`
- `com.atproto.admin.disableInviteCodes`
- `com.atproto.admin.updateAccountHandle`
Additionally, takedown actions and labeling is admin-only on `com.atproto.admin.takeModerationAction`.
Will likely port this to #840 as well.
> PDS moderator credentials

- packages/bsky/service/index.js
- packages/bsky/src/db/index.ts
- packages/pds/service/index.js
- packages/pds/src/db/index.ts
Followup to #867— also making config of an empty db schema more forgiving, i.e. handling unset versus empty string the same way.
> More forgiving config for empty db schema

- packages/pds/src/api/com/atproto/server/createAccount.ts
- packages/pds/src/services/account/index.ts
A few things here:
- move scrypt & plc op formatting outside of the db txn
- still verify availability of invite code before doing scrypto (outside of tx)
- remove row lock & replace with an integrity check at the end of the txn
> Better handle races in createAccount

- Makefile
low-priority, but indigo and PLC both have the `run-dev-*` format, and I keep typo-ing when doing integration tests.
> minor Makefile tweak: run-dev-pds, not run-pds

- packages/bsky/src/api/blob-resolver.ts
- packages/bsky/src/services/indexing/index.ts
- packages/crypto/src/sha.ts
- packages/dev-env/src/test-env.ts
- packages/did-resolver/package.json
- packages/did-resolver/src/atproto-data.ts
- packages/did-resolver/src/base-resolver.ts
- packages/did-resolver/src/did-cache.ts
- packages/did-resolver/src/errors.ts
- packages/did-resolver/src/index.ts
- packages/did-resolver/src/memory-cache.ts
- packages/did-resolver/src/plc-resolver.ts
- packages/did-resolver/src/resolver.ts
- packages/did-resolver/src/types.ts
- packages/did-resolver/src/web-resolver.ts
- packages/did-resolver/tests/cache.test.ts
- packages/did-resolver/tests/resolver.test.ts
- packages/pds/src/services/repo/blobs.ts
- packages/pds/tests/account.test.ts
- packages/pds/tests/handles.test.ts
- yarn.lock
A few things here:
- no longer use the published did-resolver library. We weren't getting anything from it & was adding complexity to the codebase
- default plc url to the production plc service (`https://plc.directory`)
- add in flexible caching ability to the did-resolver
- better error handling
- remove node dependencies 
- `@atproto/common` -> `@atproto/common-web`
- remove the one node dep in `@atproto/crypto` around streaming sha256
Closes https://github.com/bluesky-social/atproto/issues/823
Partially addresses https://github.com/bluesky-social/atproto/issues/824
> Clean up Did-resolver

- packages/pds/src/api/com/atproto/sync/getRepo.ts
- packages/pds/src/sql-repo-storage.ts
`sync.getRepo` is one of our longer running queries.
Here, we chunk it into 25 commits at a time. This keeps us from holding as many blocks in memory & should also help free up some connections in the connection pool
We can turn the knob of how big the chunks are. I opted to err on the side of smaller first for now
> Chunk getRepo query

- packages/bsky/src/db/index.ts
- packages/bsky/tests/db.test.ts
- packages/pds/src/db/index.ts
- packages/pds/src/services/repo/index.ts
- packages/pds/src/sql-repo-storage.ts
- packages/pds/tests/db.test.ts
We were having an issue with database transactions where statements were still being written to the connection after an error had thrown & the transaction had rolled back which was leading to inconsistent state in the database.
This fix uses kysely's plugin system. We add a check to the query executor such that if an error has been throwing during the transaction, every other statement on that transaction database will throw as well.
As far as I can tell, this is the last processing step before the statement is sent off to the database. The previous approach we discussed - of setting the underlying `DatabaseSchema` instance to null & throwing when you use it may still give a chance for a query to sneak in after the tx is dead
> Fix leaky database transactions

- packages/pds/src/app-view/proxied/index.ts
- packages/pds/src/services/account/index.ts
- packages/pds/tests/proxied/__snapshots__/posts.test.ts.snap
- packages/pds/tests/proxied/posts.test.ts
Two main ones here:
- proxy `feed.getPosts`
- when fetching mutes, handle the case of an empty array
> Appview proxying bugfixes

- packages/pds/src/sequencer/outbox.ts
If subscription has been aborted, return instead of continuing to yield event. Hopefully a fix for memory leak
> Return on subscription abort

- packages/pds/Dockerfile
- packages/xrpc-server/src/stream/server.ts
This adds some more aggressive backpressure on the websocket stream writer for xrpc subscriptions: we wait to drain each message before piling up additional messages, in case bad network causes a condition such as bad tcp buffering.
> More aggressive backpressure on websocket writer

- packages/bsky/src/services/label/index.ts
- packages/pds/src/app-view/api/app/bsky/unspecced.ts
- packages/pds/tests/views/popular.test.ts
This tweaks what's hot
- formalizes a hot fix that increased like threshold to 12
- filters out content from spicier labels (mostly porn & gore)
- filters out `!no-promote` content. Does not forward `!no-promote` labels to client since client does not handle it yet
> Tweak whats hot

- lexicons/app/bsky/unspecced/getPopular.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/unspecced/getPopular.ts
- packages/pds/src/app-view/api/app/bsky/unspecced.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/unspecced/getPopular.ts
Adds an optional (default false) flag to include nsfw in getPopular. Intended for use in alt clients
> Include nsfw flag for getPopular

- packages/bsky/src/util/identity.ts
- packages/identifier/src/resolve.ts
- packages/identifier/tests/resolve.test.ts
- packages/pds/src/api/com/atproto/identity/util.ts
DNS allows for multiple TXT records & is non-deterministic in it's return order.
If a user has two dids listed, we do not allow them to use either such that handle resolution is deterministic
Closes https://github.com/bluesky-social/atproto/issues/837
> Deterministic DNS handle resolution

- packages/pds/src/app-view/subscription/repo.ts
Somehow the output of this log line has been ending up in datadog under the wrong 'service' (with the 'service' being an "wss://"-prefixed URL, not "pds" or "bav" or whatever expected).
Tweaks the 'service' key, and some others that might have conflict.
> appview: tweak repo error log line to not clobber 'service'

- packages/common-web/src/tid.ts
Changes:
- Use `String.p.replaceAll` (available since `node.js >= 15`) instead `String.p.replace + regexp`
- Globalize validation constant to `TID_LEN`
- Simplify `TID.is` by avoiding try / catch and allocation
- Simplify `TID.p.equals` by using direct comparison
> Some improvements for tid.ts

- packages/nsid/src/index.ts
The name length limit is 128 not 127.
> Fix NSID name length error message typo

- packages/pds/src/api/com/atproto/server/deleteAccount.ts
- packages/pds/src/app-view/services/indexing/index.ts
- packages/pds/src/services/account/index.ts
- packages/pds/src/services/record/index.ts
- packages/pds/src/services/repo/blobs.ts
- packages/pds/src/services/repo/index.ts
- packages/pds/tests/account-deletion.test.ts
Account deletion is expensive to perform during the course of the request, so here we disable the account immediately while the hard-deletion process occurs in the background.  The deletion process has been updated to take place serially (e.g. no concurrent queries) to avoid contention, which works better now that the round-trip time is no longer in the critical path of the user's experience.
> Perform account deletion async

- packages/pds/src/services/index.ts
- packages/pds/src/services/repo/blobs.ts
- packages/pds/src/services/repo/index.ts
- packages/pds/src/storage/disk-blobstore.ts
- packages/pds/tests/blob-deletes.test.ts
- packages/pds/tests/rebase.test.ts
When a blob is dereferenced (no more records from that user pointing to it) during a commit, we remove the blob, delete it from the blobstore (if not shared with another user) & invalidate the blob in the cache.
You'll note that the rebase code as changed - we no longer need to do blob deletes in rebases because we do them proactively in deletes now.
This PR should be coupled with an app migration that deletes all existing dereferenced blobs
> Delete dereferenced blobs

- CONTRIBUTORS.md
Adding lily to contrib for a security disclosure.  I added a small amount of extra formatting (a comma) to help distinguish names of folks that aren't linked anywhere.
> Add lily to contributors for sec disclosure

- packages/pds/src/app-view/api/app/bsky/unspecced.ts
These are redacted labels that still have a row in the DB
> Do not filter on negative labels on getPopular

- packages/pds/src/app-view/services/indexing/plugins/post.ts
To protect against:
- hell threads
- bot bombing
We do not give notifs for posts >= 5 deep
> Do not give deeply nested notifs

- packages/api/package.json
- packages/aws/package.json
- packages/bsky/package.json
- packages/common-web/package.json
- packages/common/package.json
- packages/crypto/package.json
- packages/dev-env/package.json
- packages/did-resolver/package.json
- packages/identifier/package.json
- packages/lex-cli/package.json
- packages/lexicon/package.json
- packages/nsid/package.json
- packages/pds/package.json
- packages/repo/package.json
- packages/uri/package.json
- packages/xrpc-server/package.json
- packages/xrpc/package.json
Swapped in the format which allows for specifying a subdirectory in a monorepo. This should help the npm website link to the right place.
> fix: updated repository field for packages

- package.json
- yarn.lock
Add updated node-gyp dep.
This fixes better-sqlite3 from using an old version of node-gyp to build from source. better-sqlite3 does not specify a node-gyp version so it was using `v7.1.2` hosted from `@npmcli/run-script`.
```sh
~/WEBDEV/tmp/atproto main* 7s ❯ yarn why node-gyp
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "node-gyp"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "node-gyp@9.3.1"
info Has been hoisted to "node-gyp"
info Reasons this module exists
- "workspace-aggregator-a65d1e63-241b-4231-aa34-65c980ce7cbf" depends on it
- Specified in "devDependencies"
- Hoisted from "_project_#node-gyp"
info Disk size without dependencies: "2.92MB"
info Disk size with unique dependencies: "5.29MB"
info Disk …
```
> fix: macos install

- packages/pds/src/app-view/services/indexing/index.ts
- packages/pds/src/db/migrations/20230508T193807762Z-acct-deletion-indexes.ts
- packages/pds/src/db/migrations/index.ts
Just a headsup—going to land this temporarily skipping the index creation for _reasons_, then will re-enable it.
Here's the sql for the index creation:
```
create index "duplicate_record_duplicate_of_idx" on "duplicate_record" ("duplicateOf")
create index "like_creator_idx" on "like" ("creator")
create index "user_notification_author_idx" on "user_notification" ("author")
```
> Add indexes to support account deletion

- packages/bsky/src/services/label/index.ts
- packages/pds/src/app-view/api/app/bsky/unspecced.ts
- packages/pds/src/app-view/services/label/index.ts
- packages/pds/src/labeler/hive.ts
- packages/pds/tests/views/popular.test.ts
Generally trying to reduce nsfw & raunchy material in what's hot, we apply 3 fixes:
- no longer serve replies
- ensure we filter quote posts that don't pass our filters
- label underwear photos & strip underwear & nudity from what's hot
I also updated our labeling service to accurately return `!no-promote` labels
> Clean up what's hot

- lexicons/com/atproto/repo/rebaseRepo.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/repo/rebaseRepo.ts
- packages/pds/src/api/com/atproto/repo/index.ts
- packages/pds/src/api/com/atproto/repo/rebaseRepo.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/repo/rebaseRepo.ts
- packages/pds/src/services/repo/index.ts
- packages/pds/src/sql-repo-storage.ts
- packages/pds/tests/rebase.test.ts
- packages/pds/tests/sync/subscribe-repos.test.ts
Adds a route to perform rebases
Also:
- cleans up some rebase logic a bit (avoids join)
- avoids lock contention on rebases similarly to recent commit work
> Rebase route

- packages/identifier/src/handle.ts
- packages/identifier/tests/handle.test.ts
This is a "stop the bleeding" PR to halt creation and migration of new handles with `.arpa`, `.local`, and a couple other special "infrastructure" and "reserved" TLDs.
Rough plan would be to get this in, then ask existing `.arpa` tricksters to change handle (or better yet just delete those accounts), and then soon disallow at the protocol level (aka, even referencing such a domain would be invalid).
Also adds test coverage to ensure we don't allow "dotless" top-level handles, like "io". These are controversial and seem to be considered an anti-pattern by many IETF folk. I think they would be super duper cool but also super confusing for users, so we should continue to disallow at the protocol level.
cc: @devinivy @dholms for visibility
> disallow new registration of .arpa, .local, etc handles

- packages/lexicon/src/types.ts
By using `z.discriminatedUnion` instead of `z.union`
we can hint to zod at which field it should look when validating/parsing schemas.
You can read the docs on discriminated unions [here](https://github.com/colinhacks/zod#discriminated-unions)
This improves BskyAgent instantiation time around 4 times, when creating 10 agents using stuff from #1015,
the time went down from ~1200ms to 330ms
> Make BskyAgent instantiation 4 times faster

- packages/pds/src/api/index.ts
- packages/pds/src/basic-routes.ts
- packages/pds/src/index.ts
robots.txt: want to be explicit about allowing public crawling
/: a bit of dev-experience polish. in prod we already redirect this route, but may be helpful for self-hosting folks and people just exploring
> pds: place-holder robots.txt, and a text base-level route (/)

- packages/api/docs/rn-fetch-handler.ts
for non-textual response bodies, blob is the safest fallback that should work for everything
> use blob as fetch fallback

- lexicons/com/atproto/server/createAccount.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/server/createAccount.ts
- packages/pds/src/api/com/atproto/server/createAccount.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/server/createAccount.ts
- packages/pds/tests/account.test.ts
This allows you to bring your own DID document on account creation.
When you bring your own DID document, we attempt to resolve it & ensure that the data within matches up with the intended values. Namely:
- handle matches requested handle
- pds service endpoint matches the service endpoint you're attempting account creation on
- atproto key matches the server's repoSigningKey
- if it is a PLC DID, then we ensure the server's plcRotationKey is included in the documents rotation keys
Buyer beware: we _do not_ do that last check for did:web. If you are using a did:web DID, it is your obligation to keep your DID document up to date with the service you're using - otherwise your data may no longer be indexed.
In service of: https://github.com/bluesky-social/atproto/pull/1001
> Bring your own DID

- lexicons/com/atproto/admin/getModerationReports.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/admin/getModerationReports.ts
- packages/bsky/src/api/com/atproto/admin/getModerationReports.ts
- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/admin/defs.ts
- packages/bsky/src/lexicon/types/com/atproto/admin/disableAccountInvites.ts
- packages/bsky/src/lexicon/types/com/atproto/admin/enableAccountInvites.ts
- packages/bsky/src/lexicon/types/com/atproto/repo/rebaseRepo.ts
- packages/bsky/src/services/moderation/index.ts
- packages/pds/src/api/com/atproto/admin/getModerationReports.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/admin/getModerationReports.ts
- packages/pds/src/services/moderation/index.ts
- packages/pds/tests/views/admin/__snapshots__/get-moderation-reports.test.ts.snap
- packages/pds/tests/views/admin/get-moderation-reports.test.ts
Adds support for fetching moderation reports by active action type.  For example, if you filter reports by the action type "flag" then you will find all reports that were resolved with a flag action that hasn't been reversed.
> Reports by active action type

- packages/bsky/src/auth.ts
- packages/bsky/src/config.ts
- packages/bsky/src/context.ts
- packages/bsky/tests/_util.ts
- packages/dev-env/src/index.ts
- packages/dev-env/src/test-env.ts
- packages/pds/src/app-view/proxied/index.ts
- packages/pds/src/auth.ts
- packages/pds/src/config.ts
- packages/pds/src/index.ts
- packages/xrpc-server/package.json
- packages/xrpc-server/src/auth.ts
- packages/xrpc-server/src/index.ts
- packages/xrpc-server/tsconfig.json
This tidies & formalizes service <> service auth.
Three primary changes:
- moves creation & validation of service jwts to `@atproto/xrpc-server` for easier reuse
- adds `aud` to service jwt. this is security consideration to prevent MITM attacks
- formalizes the concept that services should have DIDs & gives both the appview & PDS real DIDs (in their cfg & in test envs)
> service <> service auth

- packages/api/tests/agent.test.ts
- packages/api/tests/bsky-agent.test.ts
- packages/common-web/tests/check.test.ts
- packages/common-web/tests/tid.test.ts
- packages/common-web/tests/util.test.ts
- packages/common/tests/streams.test.ts
just getting my head around the repo out of curiosity, so i filled in some test gaps while i was there
let me know if there's anything you want changing, and if you want this
fwiw too the agent tests could be better to purge the in-memory db between tests. you spin up a single db before the entire suite presumably to save time/resources. however, it means tests can pollute each others' state, and you end up with these ever-incrementing user IDs in your test cases to avoid conflicts.
would be much better if you could `afterEach(() => server.ctx.db.clear())` somehow
> test (api, common, common-web): add further tests

- .github/workflows/build-and-push-bsky-aws.yaml
- .github/workflows/build-and-push-bsky-ghcr.yaml
- .github/workflows/build-and-push-pds-aws.yaml
- .github/workflows/build-and-push-pds-ghcr.yaml
Updates github action docker/setup-buildx-action from v1 to v2 which
- [moves Node 12 to Node 16](https://github.com/docker/setup-buildx-action/pull/131)
- [stops using the setOutput workaround](https://github.com/docker/setup-buildx-action/pull/170)
which gets rid of some of these annoying annotation warnings during the build pipeline:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: docker/setup-buildx-action@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
```
&
```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: …
```
> chore: update docker/setup-buildx-action github action to v2

- packages/pds/src/labeler/hive.ts
The "sex toy" and "hanging" changes are pretty simple.
Flagging all "underwear" in to "sexually suggestive" is more disruptive. I did some spot checks and posted examples in slack if you want to review. The motivation is to improve overall "NSFW" filtering using the existing toggles/config, weighed against over-sexualizing simple/neutral photos.
> more labeling tweaks

- packages/dev-env/src/bin.ts
- packages/dev-env/src/pds.ts
I need this URL to be correct for images in the dev env
> Fix dev env public url

- packages/pds/src/labeler/hive.ts
Some auto-labeling categories were too sensitive. This gives us a way to require a higher threshold for some labels.
> auto-label: less sensitive for some classes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
Updated README to include rules/guidelines for contribution. Shamelessly stolen for the client repo.
Also included issue templates for bug reports & feature requests
> Update README + issue templates

- lexicons/app/bsky/graph/defs.json
- lexicons/com/atproto/repo/applyWrites.json
- packages/api/src/client/lexicons.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/lexicon/src/types.ts
- packages/lexicon/src/util.ts
- packages/lexicon/tests/general.test.ts
- packages/pds/src/lexicon/lexicons.ts
Opening as a draft as there are two lexicons with issues
Addresses: #1037 
Now schemas like the one below won't validate, I also had to rewrite `lexUserType` validator as `z.discriminatedUnion` can't take `ZodEffects` as an argument and using just a simple `z.union` would be quite slow on such big object.
```json
...
{
"type": "object",
"required": ["foo"],
"properties": {}
}
...
````
> Add lexicon LexXrpcParameters, Object required properties check

- packages/xrpc/src/client.ts
- packages/xrpc/src/util.ts
This isn't fully upto HTTP Spec, but it solves #1029. The `normalizeHeaders` function deduplicates HTTP headers, but it doesn't take into account the rules from [RFC9110 appendix A](https://www.rfc-editor.org/rfc/rfc9110#appendix-A)
When using `AtpAgent` the `authorization` header supplied to the xrpc call will take precedence over the internal one
> Normalize http headers before sending xrpc requests

- packages/bsky/src/lexicon/lexicons.ts
Lexicon required properties check wasn't rebased onto main before merge which introduced invalid lexicon(creator field was not defined despite being in the required fields list)
> Fix definitions in bsky

- packages/pds/src/app-view/api/app/bsky/feed/getFeed.ts
- packages/pds/src/feed-gen/with-friends.ts
- packages/pds/tests/algos/with-friends.test.ts
After testing out the with-friends algo, it felt a bit too similar to the regular following feed.  We'd also like it to be a little snappier.  The update here surfaces popular posts that have been liked by any of your most active mutuals.
This work is complete, but putting it up as a draft since the behavior itself is possibly not finalized.
> Tweaks to with-friends algo

- lexicons/app/bsky/feed/defs.json
- packages/api/src/client/lexicons.ts
- packages/pds/src/lexicon/lexicons.ts
my Python codegen failed on it. let me know pls if the lexicon has been changed and it's not a typo
> Fix lexicon. "format" instead of "ref" in type "string"

- packages/pds/src/feed-gen/whats-hot.ts
- packages/pds/tests/algos/whats-hot.test.ts
This is an iterative step to improve performance of the main query powering the `whats-hot` custom algo.  By reorganizing the query logic, we're able to get the query planner to sort the result set in parallel which gives us an order of magnitude improvement.  We also proactively exclude results with low like counts, since they are unlikely to land in the feed.
> Improve performance of whats-hot custom algo

- packages/dev-env/src/pds.ts
- packages/pds/src/api/com/atproto/repo/putRecord.ts
- packages/pds/src/app-view/api/app/bsky/feed/describeFeedGenerator.ts
- packages/pds/src/config.ts
- packages/pds/tests/_util.ts
- packages/pds/tests/feed-generation.test.ts
Two things here:
- We need a feed generator did provided to the server so that it can properly respond to `describeFeedGenerator`
- We allow `putRecord` for generator records
Note: before, deploy we should add the following DIDs to our service configs:
```
staging: did:plc:go3w5oz6pk4a56zaaprn3lyr
production: did:plc:5fllqkujj6kqp5izd5jg7gox
```
> Feed publishing tweaks

- packages/lexicon/src/util.ts
- packages/lexicon/tests/general.test.ts
Fixes lexicon validation so incorrect types like in #1089 don't validate.
Now when a request like in #1089 is sent a proper 400 is returned :)
> Fix incorrect union validation

- packages/pds/src/services/repo/index.ts
Ensure we're sending a record for labeling after the write occurs
> Label after write

- lexicons/app/bsky/feed/getPostThread.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/getPostThread.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/getPostThread.ts
- packages/pds/src/app-view/api/app/bsky/feed/getPostThread.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/getPostThread.ts
- packages/pds/tests/views/__snapshots__/thread.test.ts.snap
- packages/pds/tests/views/thread.test.ts
This PR implements the changes required for https://github.com/bluesky-social/social-app/pull/723
It limits recursion into parent posts, in exactly the same way as recursion into child posts was previously limited.
Right now it uses the same depth limit value, perhaps there should be a secondary limit if you want to configure a different maximum parent depth vs child depth.
If it's going to be merged, https://github.com/bluesky-social/social-app/pull/723 should be merged first.
> Limit getPostThread recursion into parents

- packages/pds/src/api/com/atproto/repo/rebaseRepo.ts
- packages/pds/src/services/repo/index.ts
- packages/pds/src/sql-repo-storage.ts
This is a small rework to rebases
The primary change is that instead of walking the repo from the top, we reconstruct it from the records at the bottom.
This does a couple things:
- reduces likelihood of a bug that deletes records
- allows recoverability from an unwalkable repo (ie, in a bad state) 
- prevents records from becoming orphaned if there was bad bookkeeping
This should also entail less back and forth with the database so should be more efficient as well
This also includes a dummy check that counts the number of record blocks before & after the tx and rolls the tx back if the numbers are not the same. This check may be deleted eventually, but is useful now because this is a potentially destructive operation. As long as record blocks are not deleted, we can always reconstruct a …
> Rebase rework

- packages/identity/src/handle/index.ts
Small bugfix. It was returning error content as a string instead of interpreting as an error
> Bugfix for well-known handle resolution

- packages/pds/service/index.js
- Added default values for the `username`, `password`, `host`, `port`, and `database` parameters of the `pgUrl` function.
- Added an optional `sslmode` parameter to the `pgUrl` function.
- These default values are intended to ensure that the `pgUrl` function can still connect to the PostgreSQL database even if not all the parameters are provided.
```json
{
"username": "myuser",
"password": "mypassword",
"host": "localhost",
"port": "5432"
}
```
Output:
```
postgresql://myuser:mypassword@localhost:5432/postgres
```
```json
{
"username": "myuser",
"password": "mypassword",
"host": "localhost",
"port": "5432",
"database": "mydb",
"sslmode": "require"
}
```
Output:
```
postgresql://myuser:mypassword@localhost:5432/mydb?sslmode=require
```
> Increase flexibility of paramaters accepted by DB_CREDS_JSON env var

- packages/bsky/src/db/index.ts
- packages/bsky/tests/db.test.ts
- packages/pds/src/db/index.ts
- packages/pds/tests/db.test.ts
There is a race condition on transaction execution that looks something like:
- transaction is begun
- query is formatted, passed to executor & through plugins
- error is thrown
- transaction is rolled back
- query is processed by postgres _outside of_ txn
The LeakyTx plugin was meant to catch these, but apparently that plugin is not the absolute last thing done before sending the query.
The fix I applied here feels just a lil bit hacky but I can't see a better approach. We wait for 10ms after receiving an error for any queries to get sent off before throwing the error which will all it to rollback. During that 10ms, we stop any new queries from being sent.
You can see another approach I tried in the commit log where I tracked in-flight queries, but this was failing on queries that would …
> Catch missed txn rollbacks

- packages/pds/src/app-view/api/app/bsky/feed/getAuthorFeed.ts
- packages/pds/src/app-view/api/app/bsky/feed/getFeed.ts
- packages/pds/src/app-view/api/app/bsky/feed/getTimeline.ts
- packages/pds/src/app-view/api/app/bsky/notification/getUnreadCount.ts
- packages/pds/src/app-view/api/app/bsky/notification/listNotifications.ts
- packages/pds/src/app-view/api/app/bsky/unspecced.ts
- packages/pds/src/feed-gen/bsky-team.ts
- packages/pds/src/feed-gen/hot-classic.ts
- packages/pds/src/feed-gen/whats-hot.ts
- packages/pds/src/feed-gen/with-friends.ts
- packages/pds/src/services/account/index.ts
Previously the query snippet we'd use for excluding a user's mutes was roughly:
```
where not exists ((direct mutes) union all (mutes from lists))
```
Breaking-up the checks for direct mutes and list mutes turns out to be more flexible for the query planner, allowing it to speed some queries up.  So now we roughly do this:
```
where (not exists (direct mutes) and not exists (mutes from lists))
```
> Implement quicker mute checks on pds

- packages/pds/service/index.js
This should fix the view maintainer execution: the one connection was getting caught-up holding the lock that chooses the view-maintainer leader 🙃
> Update pool size for view maintainer

- packages/bsky/src/api/app/bsky/feed/getTimeline.ts
- packages/pds/src/api/com/atproto/sync/getRepo.ts
- packages/pds/src/app-view/api/app/bsky/feed/getTimeline.ts
- Avoid scanning back further than two weeks on timeline, to avoid worst-case degenerate cases for building feeds.
- Increase commit chunk size when pulling blocks in `getRepo`, hoping for a positive tradeoff when halving the number of total queries.
> Minor perf tweaks for getTimeline and getRepo

- packages/pds/src/db/index.ts
We haven't seen this issue actually occur, but in theory if PDSes are spinning then the view refreshes could happen many times in a row.  This avoids that by scheduling the first refresh rather than running it immediately.
> Disallow scheduling repeated view refreshes

- packages/pds/src/feed-gen/with-friends.ts
This optimization didn't turn out to be beneficial for the with-friends algo, so reverting.
> Revert feed date threshold for with-friends

- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
- packages/bsky/src/api/app/bsky/feed/getPosts.ts
- packages/bsky/src/api/app/bsky/notification/listNotifications.ts
- packages/bsky/src/api/app/bsky/util/feed.ts
- packages/bsky/src/services/actor/views.ts
- packages/bsky/src/services/feed/index.ts
- packages/bsky/src/services/label/index.ts
- packages/bsky/src/services/types.ts
- packages/pds/src/app-view/api/app/bsky/feed/getPostThread.ts
- packages/pds/src/app-view/api/app/bsky/feed/getPosts.ts
- packages/pds/src/app-view/api/app/bsky/notification/listNotifications.ts
- packages/pds/src/app-view/services/actor/views.ts
- packages/pds/src/app-view/services/feed/index.ts
- packages/pds/src/app-view/services/feed/types.ts
- packages/pds/src/app-view/services/feed/views.ts
- packages/pds/src/app-view/services/label/index.ts
We don't have to land this, but this was a pretty quick/simple change I wanted to at least consider.
Since labels pervade the whole app.bsky API, the query to fetch labels is consistently the most trafficked in the entire application by around a factor of 2.  The idea here is to nearly halve the number of label queries needed to satisfy feed and thread views.
The implementation allows opting-in to this behavior.
- `getLabelsForSubjects()` now works for both aturis and dids, aggregating profile labels for dids.  It replaces `getLabelsForProfiles()`.
- `getLabelsForUris()` is now the lower-level method to query for labels without the special profile/did behavior.
- When you're hydrating posts and want this behavior:
1.  tell `getActorViews()` to skip fetching labels with the `skipLabels` …
> Batch fetching of labels across posts and actors

- packages/identity/src/handle/index.ts
We were being to aggressive in throwing these errors & were throwing on bad DNS records when the HTTP resolution was working fine
> Don't throw on dns lookup errors

- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
- packages/bsky/src/api/app/bsky/feed/getPosts.ts
- packages/bsky/src/api/app/bsky/util/feed.ts
- packages/bsky/src/services/feed/index.ts
- packages/pds/src/app-view/api/app/bsky/feed/getPostThread.ts
- packages/pds/src/app-view/api/app/bsky/feed/getPosts.ts
- packages/pds/src/app-view/services/feed/index.ts
- packages/pds/src/app-view/services/feed/views.ts
- packages/pds/src/feed-gen/mutuals.ts
- packages/pds/src/feed-gen/with-friends.ts
A few changes here:
- On with-friends algo I switched the filtering to use `originatorDid` rather than `post.creator`.  These are the same value, but the former comes from the base table rather than a joined table.  This seems to open up some options for the query planner, and based on my testing it lands in a much better place.
- With that change I figured it made sense to reintroduce the date threshold.
- Same with the mutuals algo.  Also constrained it only to posts, since it was including _all_ reposts of mutuals' posts.
- Applied more label batching to other places it could easily fit-in.
> Perf tweaks to with-friends, mutuals, label batching

- packages/identifier/src/did.ts
- packages/identifier/tests/did.test.ts
- packages/identifier/tests/handle.test.ts
- packages/identity/package.json
- packages/identity/src/did/web-resolver.ts
- packages/identity/src/errors.ts
- packages/identity/tests/did-resolver.test.ts
- packages/nsid/src/index.ts
- packages/nsid/tests/nsid.test.ts
- packages/xrpc-server/package.json
- packages/xrpc-server/tests/bodies.test.ts
- packages/xrpc-server/tests/procedures.test.ts
- packages/xrpc-server/tests/queries.test.ts
- packages/xrpc-server/tests/subscriptions.test.ts
The motivation was to take some of the small proposed changes from identifier specification work and put them in PR form for review here.
The NSID "name" component length change (from 128 to 63): i'm actually now kind of ambivalent after implementing this. One of the motivations was realizing huge names would bloat AT-URIs. But maybe it just doesn't matter!
NSID other restrictions: I think tracking handles to domains very closely has been a good move. I'm not sure the same needs to apply to NSIDs, but it is weird to have extra rules around NSID *domain authority* section other than "valid hostname in reverse order". I am in favor of locking down the "name" section very harshly (to just ASCII letters, either case). We can allow trailing digits or whatever later if we want, once we verify …
> identifier tweaks

- packages/pds/src/feed-gen/whats-hot.ts
Query planner started getting screwy
Switched it up to select from the whats hot materialized view & then join in posts instead of the other way around
> Fix up what's hot

- packages/bsky/src/api/com/atproto/admin/searchRepos.ts
- packages/bsky/src/services/actor/index.ts
- packages/bsky/tests/views/admin/repo-search.test.ts
- packages/dev-env/src/network.ts
- packages/pds/src/api/com/atproto/admin/searchRepos.ts
- packages/pds/src/services/account/index.ts
- packages/pds/tests/views/admin/repo-search.test.ts
This PR allows `admin.searchRepos` to take `did` as a search term along with handles.
> :sparkles: Allow searching repo by DID

- packages/pds/src/app-view/api/app/bsky/graph/getLists.ts
On `getLists` we were paginating over `indexedAt` but building the cursor based on `createdAt`, which was causing some bad pages to come through.  Now both are based on `createdAt`, which is consistent with how this is handled on similar endpoints such as `getFollows` and `getLikes`.
> Fix lists pagination, ensure paginating on correct column

- packages/bsky/src/api/app/bsky/feed/getTimeline.ts
- packages/bsky/src/db/pagination.ts
- packages/pds/src/app-view/api/app/bsky/feed/getTimeline.ts
- packages/pds/src/db/pagination.ts
The query snippet we use for keyset pagination wouldn't get picked-up by an index on `(primary-column, secondary-column)` due to its form using `or`.  We now use a "row value" comparison which is simpler to write and indexes know how to use it.  Currently just rolling out on `getTimeline`:  will eventually enable this other places once it's proven to work as intended, and hopefully remove the original implementation.
> Ensure keyset pagination makes use of indexes on timeline

- packages/pds/src/app-view/services/indexing/plugins/feed-generator.ts
- packages/pds/src/app-view/services/indexing/plugins/list-item.ts
- packages/pds/src/app-view/services/indexing/plugins/list.ts
Some records being indexed—lists, list items, and feedgens—weren't having their `createdAt` times normalized.  This sometimes threw-off pagination as in #1176.
Resolves #1176.
> Normalize creation times on list, list item, feedgen records

- packages/identity/src/handle/index.ts
- packages/pds/src/api/com/atproto/admin/updateAccountHandle.ts
- packages/pds/tests/handles.test.ts
Disables legacy allowance of xrpc handles.
We only allow registering a handle through DNS or .well-known now.
Also tweaks admin updates of handles so that we can deprecate handle violations
> Disable resolution of handles through xrpc

- packages/pds/src/config.ts
- packages/pds/src/context.ts
- packages/pds/src/crawlers.ts
- packages/pds/src/index.ts
- packages/pds/src/logger.ts
- packages/pds/src/services/index.ts
- packages/pds/src/services/repo/index.ts
Notify crawlers on write.
On write, ping all configured crawlers that a new write is available.
Only do this maximum once every 20 minutes.
> Notify crawlers on write

- lexicons/com/atproto/sync/getHead.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/sync/getHead.ts
- packages/bsky/src/db/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/sync/getHead.ts
- packages/bsky/src/services/indexing/index.ts
- packages/bsky/src/subscription/repo.ts
- packages/bsky/tests/duplicate-records.test.ts
- packages/bsky/tests/indexing.test.ts
- packages/pds/src/api/com/atproto/sync/getHead.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/sync/getHead.ts
Some more cleanup in the bsky appview:
- Now we process each record indexing transactionally, but other indexing operations are not necessarily transactional.  The goal here is to avoid prohibitively long transactions that could affect indexing of other repositories.  A handful of http requests that previously held-up a transaction now occur outside of one.
- The behavior for indexing tombstones is now loosened from "did doc no longer resolves" to "there is no pds hosting this user's content".
- The `sync.getHead` endpoint now has an error type to explicitly indicate that the head cannot be found.
I expect it will be easiest to review this [ignoring whitespace](https://github.com/bluesky-social/atproto/pull/1192/files?w=1).
> Bsky appview: resolve long transactions, tombstone behavior

- packages/pds/src/config.ts
> Fix epoch env

- packages/bsky/src/services/indexing/index.ts
- packages/bsky/src/subscription/repo.ts
- packages/bsky/tests/subscription/repo.test.ts
A couple improvements to indexing handles on the appview:
- On an unprocessable commit event, still attempt to index the handle.
- Attempt to revalidate each handle daily (i.e. in the absence of a handle update event).
- Improve error handling/reporting on commit events.
> Improve handle indexing on appview

- .github/workflows/build-and-push-bsky-aws.yaml
- .github/workflows/build-and-push-bsky-ghcr.yaml
- packages/bsky/src/api/com/atproto/repo/getRecord.ts
- packages/bsky/src/api/index.ts
- packages/pds/src/api/com/atproto/repo/getRecord.ts
- packages/pds/src/crawlers.ts
Porting some changes from https://github.com/bluesky-social/atproto/pull/1198/commits/a109e140134ac416cc7dd2f5e62b96c7c185df0f
- Implement `getRecord` on appview to support some usage by the client via @atproto/api.
- Fallback to appview in `getRecord` on the pds when applicable.
- Temporarily use `requestCrawl` rather than `notifyOfUpdate` for notifying crawlers.
- Misc tidying.
> Backport: fallback to getRecord on appview, misc fixes

- packages/bsky/src/api/com/atproto/moderation/createReport.ts
The bsky appview will temporarily allow anonymous reports to support early usage in sandbox.
> Allow optional auth for reporting on bsky appview

- lexicons/com/atproto/sync/notifyOfUpdate.json
- lexicons/com/atproto/sync/requestCrawl.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/sync/notifyOfUpdate.ts
- packages/api/src/client/types/com/atproto/sync/requestCrawl.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/sync/notifyOfUpdate.ts
- packages/bsky/src/lexicon/types/com/atproto/sync/requestCrawl.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/sync/notifyOfUpdate.ts
- packages/pds/src/lexicon/types/com/atproto/sync/requestCrawl.ts
re: https://github.com/bluesky-social/atproto/discussions/1214
Because these are intended to have side effects they really should be POSTs instead of GETs.
Rollout plan: we're intending to support both POSTs & GETs on BGS for some period - likely a week - as this change goes out, then we will be deprecating GETs
> Make requestCrawl & notifyOfUpdate procedures

- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
Just a small fix to limit thread recursion in parents in the appview. 
As was pointed out [here](https://github.com/bluesky-social/atproto/pull/1062#issuecomment-1601833585), we aren't limiting thread recursion in the appview.
> Appview limit thread recursion

- packages/pds/src/api/com/atproto/server/getAccountInviteCodes.ts
- packages/pds/src/services/account/index.ts
- packages/pds/tests/account.test.ts
- packages/pds/tests/invite-codes.test.ts
We no longer count admin-gifted invites against a user routine interval invites
I also took the time to split invites out into their own test suite & made it a bit more robust
> Improve invite code counting

- packages/bsky/src/api/app/bsky/actor/searchActorsTypeahead.ts
- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
- packages/bsky/src/api/app/bsky/util/feed.ts
- packages/bsky/src/db/pagination.ts
- packages/bsky/src/db/util.ts
- packages/bsky/src/feed-gen/best-of-follows.ts
- packages/bsky/src/feed-gen/bsky-team.ts
- packages/bsky/src/feed-gen/hot-classic.ts
- packages/bsky/src/feed-gen/mutuals.ts
- packages/bsky/src/feed-gen/whats-hot.ts
- packages/bsky/src/feed-gen/with-friends.ts
- packages/bsky/src/services/feed/index.ts
- packages/bsky/src/services/feed/views.ts
- packages/bsky/src/services/util/search.ts
- packages/pds/src/app-view/api/app/bsky/actor/searchActorsTypeahead.ts
- packages/pds/src/db/pagination.ts
- packages/pds/src/db/util.ts
- packages/pds/src/feed-gen/best-of-follows.ts
- packages/pds/src/feed-gen/with-friends.ts
- packages/pds/src/services/account/index.ts
- packages/pds/src/services/util/search.ts
Just some odds and ends!
- Sync-up the bsky package with changes from #1232.
- Sync-up the bsky package, applying blocks and mutes on custom algos.
- Paginate with-friends feed using a condition that hits the post order-by index.
- Update invite codes base query to be more performant (avoids materializing counts of all codes during the query).
- Use simpler approach for actor typeahead search query.
- For full actor search we need to fully support pagination by `(distance, handle)`.  But for the typeahead version we only need to produce one page of results.  That allows us to drop the need to sub-sort profile and account results by `handle`, which is quite a bit easier since it can be done during the trigram index scan.
- This one lead to a little refactor of the code for the search …
> Miscellaneous perf improvements and bsky sync-up

- packages/aws/package.json
- yarn.lock
A new version of uint8arrays snuck in in https://github.com/bluesky-social/atproto/pull/1218
We want to stay fixed at 3.0.0
> Fix uint8arrays version mismatch

- packages/bsky/src/services/feed/index.ts
- packages/bsky/src/services/feed/views.ts
- packages/bsky/src/services/graph/index.ts
- packages/pds/src/app-view/api/app/bsky/actor/getProfile.ts
Return `sortAt` in appview queries instead of `indexedAt`
This is a composite timestamp that is `min(createdAt, indexedAt)` & will stop a newly spun up appview service from naively returning the time it encountered a post
> Appview - use sortAt

- package.json
- packages/bsky/tests/algos/hot-classic.test.ts
- packages/bsky/tests/algos/whats-hot.test.ts
- packages/bsky/tests/algos/with-friends.test.ts
- packages/bsky/tests/feed-generation.test.ts
- packages/bsky/tests/labeler/labeler.test.ts
- packages/bsky/tests/moderation.test.ts
- packages/pds/tests/_util.ts
- packages/pg/with-test-db.sh
I believe the CI failures in https://github.com/bluesky-social/atproto/pull/1198 come from the following issue:
- Either the bsky or the pds test suite starts the test db
- Both test suites take advantage of it
- the first to finish closes it down
- the second test suite may not be finished with it yet
This moves startup & of the test suite to the monorepo root.
It also alters the pg script file to check if the container is already running. If not, then only the script in charge of starting up the container will tear it down.
Unrelated to this, but I also moved the `on_sigint` handler a bit higher up, so that we don't hit the awkward case where a sigint will kill the container but keep running all the tests.
---
I also noticed a merge conflict on `LOG_ENABLED=false`. Not sure which way we …
> Run test DB for full monorepo tests

- packages/repo/src/mst/mst.ts
- packages/repo/tests/sync/checkout.test.ts
We were sending some duplicate blocks in checkout.
This was because we were starting with a basecase of the root node & all it's subtrees before iterating. This small change ended up propagating down each layer of the tree
Closes https://github.com/bluesky-social/atproto/issues/1255
> Prevent duplicate blocks in checkout

- packages/pds/src/app-view/api/app/bsky/feed/getTimeline.ts
Skeleton handler didn't like passing through the algorithm param
> Only pass through known params on timeline skeleton

- packages/bsky/src/services/moderation/index.ts
- packages/pds/src/services/moderation/index.ts
- packages/pds/tests/views/admin/get-moderation-reports.test.ts
Due to the way postgres handles null values, when we try to ignore reports for a specific `subjectUri`, the previous query was also ignoring all reports with `subjectUri=null` (so basically, all account reports).
> :bug: Only ignore reports for specific at-uri when ignoreSubject contains at-uri

- packages/pds/src/app-view/api/app/bsky/feed/getTimeline.ts
no longer require proxy header
> Move timeline construction to appview

- packages/repo/src/util.ts
- packages/repo/tests/util.test.ts
- packages/xrpc-server/src/server.ts
- packages/xrpc-server/tests/responses.test.ts
Car writer was not properly handling errors, so we wrap it in a stream to better propagate them
xrpc-server was mishandling errors when serving a streaming req & making it the whole server's problem
> Better propagate errors on repo streams

- packages/pds/tests/db.test.ts
Fix a flaky db test by slightly increasing the timeout
In CI environments in particular, resources are a bit more constrained and the 1 ms timeout wasn't enough for the connection to be closed
> Fix flaky db test

- packages/bsky/src/subscription/repo.ts
The repo sub only needs a single indexing service to be instantiated, so we do a little tidying here to allow that.
> Tidy repo sub usage of indexing service

- packages/pds/src/api/com/atproto/identity/updateHandle.ts
- packages/pds/src/services/account/index.ts
Allows us to bail early for taken handles.
> Perform pessimistic handle check when updating handle

- packages/pds/src/api/com/atproto/repo/createRecord.ts
Heads up, this PR is completely untested, but this seems like the quickest way to return to sanity
> hotfix: prevent user-supplied rkey on posts with createRecord

- packages/bsky/src/api/com/atproto/admin/reverseModerationAction.ts
- packages/bsky/src/api/com/atproto/admin/takeModerationAction.ts
- packages/bsky/tests/moderation.test.ts
- packages/pds/src/api/com/atproto/admin/reverseModerationAction.ts
- packages/pds/src/api/com/atproto/admin/takeModerationAction.ts
- packages/pds/tests/moderation.test.ts
Just tweaking some of the role-based auth so that moderators can take and reverse actor takedowns.
> Allow moderators to take and reverse actor takedowns

- lexicons/com/atproto/admin/getModerationReports.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/admin/getModerationReports.ts
- packages/bsky/src/api/com/atproto/admin/getModerationReports.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/admin/getModerationReports.ts
- packages/bsky/src/services/moderation/index.ts
- packages/pds/src/api/com/atproto/admin/getModerationReports.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/admin/getModerationReports.ts
- packages/pds/src/services/moderation/index.ts
- packages/pds/tests/views/admin/__snapshots__/get-moderation-reports.test.ts.snap
- packages/pds/tests/views/admin/get-moderation-reports.test.ts
Allow fetching reports by a moderator did so that only reports that a certain moderator actioned are returned.
> :sparkles: Allow searching reports by moderator did

- packages/pg/with-test-db.sh
So, since Docker Desktop has licensing issues, some folks use colima for
running containers on their macOS machines (The licensing exempted
CLI-only version of Docker only exists on Linux).
Unfortunately, colima binds host ports only on the IPv4 localhost
address (`127.0.0.1`) while the atproto postgres clients will attempt to
connect to the IPv6 localhost address (`::1`) that macOS sets in
/etc/hosts.  See https://github.com/abiosoft/colima/issues/583 and
https://github.com/lima-vm/lima/issues/1330 for the tickets against
colima. (Docker Desktop binds to both IPv4 and IPv6 localhost addresses
and so doesn't have this issue.)
To workaround this silly issue, we can use `localhost` within the docker
containers and docker-compose, but need to set the `DB_POSTGRES_URL` env
var to use the IPv4 …
> use 127.0.0.1 in with-test-db.sh for colima

- packages/pds/src/sequencer/events.ts
- packages/pds/src/sequencer/sequencer-leader.ts
- packages/pds/tests/algos/whats-hot.test.ts
- packages/pds/tests/sequencer.test.ts
Sequence leader:
- this gets turned off on sqlite, but we weren't putting out any notifies for outgoing repo events so nothing was getting polled from the DB
Whats hot:
- we don't construct/refresh the materialized view in sqlite, so we just skip these tests for now
> Patch up a couple sqlite tests

- packages/bsky/src/index.ts
Increase keepalive to 90s to match PDS. Prevents 502s from load balancer idle timeout.
> Increase appview keepalive

- lexicons/app/bsky/unspecced/getPopularFeedGenerators.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/unspecced/getPopularFeedGenerators.ts
- packages/bsky/src/api/app/bsky/unspecced/getPopularFeedGenerators.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/unspecced/getPopularFeedGenerators.ts
- packages/pds/src/app-view/api/app/bsky/unspecced.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/unspecced/getPopularFeedGenerators.ts
- packages/pds/tests/feed-generation.test.ts
Adds an optional `query` query param to `getPopularFeedGenerators` in order to optionally apply an `ILIKE` operator on `displayName` and `description` to match Ansh's [current client-side search](https://github.com/bluesky-social/social-app/pull/1031/files#diff-b85a98a45a6674a667a38278b8fb39914d1c5316959c5dc5476d73c1d842ea81R89-R90).
> add optional `ILIKE` query to `getPopularFeedGenerators`

- packages/pds/src/handle/index.ts
tlds have not been appropriately checked since 6b51ecb due to what appears to be a typo/oversight (checking whether the function exists -- which is always true -- rather than calling it)
this pr fixes it so that tlds are once again validated
> pds: actually validate tlds

- lexicons/com/atproto/admin/defs.json
I'm writing a lexicon schema generator. As part of that I want to test whether I can round trip all lexicons from json to my structs that represent a lexicon, and back to json.
However, with this, when serializing, the current code doesn't emit a value here, due to the fact that when an array is empty,
I skip serializing the key, and when the key is absent in deserializing, I use an empty array.
This let's me have a schema like:
```rust
struct Object {
#[serde(default, skip_serializing_if = "Vec::is_empty")]
required: Vec<String>
...
}
```
which is much nicer to work with than
```rust
struct Object {
#[serde(skip_serializing_if = "Option::is_none")]
required: Option<Vec<String>,
...
}
```
To make tests pass locally, I've [patched the lexicon …
> lexicons: Remove empty array to make roundtriping work

- packages/pds/service/index.js
This came up in code review of https://github.com/bluesky-social/atproto/pull/974, but seems like the change wasn't actually made before merging.
This is a connection string, not binding, so `0.0.0.0` ("all addresses on all interfaces") doesn't make sense.
As a piece of standards nerdery, there are IETF/IANA efforts both to allow registrations under the `0.` class A IPv4 prefix (https://www.ietf.org/archive/id/draft-schoen-intarea-lowest-address-01.html), and I think also to enable communicating with IPv4 addresses terminating in (`.0`) (https://www.ietf.org/archive/id/draft-schoen-intarea-lowest-address-01.html). Both are controversial!
> pds: set default postgresql URL to localhost

- .github/workflows/build-and-push-bsky-aws.yaml
- .github/workflows/build-and-push-pds-aws.yaml
- lexicons/app/bsky/unspecced/applyLabels.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/unspecced/applyLabels.ts
- packages/api/src/client/types/com/atproto/moderation/defs.ts
- packages/bsky/src/auth.ts
- packages/bsky/src/indexer/config.ts
- packages/bsky/src/labeler/base.ts
- packages/bsky/src/labeler/hive.ts
- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/unspecced/applyLabels.ts
- packages/bsky/src/lexicon/types/com/atproto/moderation/defs.ts
- packages/pds/src/app-view/api/app/bsky/unspecced.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/unspecced/applyLabels.ts
- packages/pds/src/lexicon/types/com/atproto/admin/enableAccountInvites.ts
- packages/pds/src/lexicon/types/com/atproto/moderation/defs.ts
- packages/pds/tests/labeler/apply-labels.test.ts
Allows the appview to push labels to the PDS using an unspecced route, as a temporary measure.  Also adds an http retry to the hive labeler.
> Push labels to PDS

- packages/pds/src/api/com/atproto/admin/getModerationAction.ts
- packages/pds/src/api/com/atproto/admin/getModerationReport.ts
- packages/pds/tests/proxied/__snapshots__/admin.test.ts.snap
Resolves an issue where moderation report and action details were not reflecting PDS state (e.g. invites and email) when proxying to the appview.
> Include pds account info on mod report and action details

- packages/bsky/src/api/app/bsky/feed/getFeed.ts
- packages/bsky/src/api/app/bsky/feed/getTimeline.ts
- packages/bsky/src/api/app/bsky/unspecced/getTimelineSkeleton.ts
- packages/bsky/src/services/feed/index.ts
This strengthens the feed cleaning abstraction & adds it to the feed service.
We also rearrange the timeline skeleton code so that we don't write it twice & don't check for mutes/blocks in the main construction query
> Tighten feed filtering

- packages/dev-env/build.js
- packages/dev-env/package.json
- packages/dev-env/src/bin-network.ts
This creates a separate script `yarn start:network` for launching a dev-env with an appview, using Postgres & Redis.
Soon this will replace the old dev-env, but we'll need to discuss what exactly that looks like
> Add bin for launching dev-env with an appview

- lexicons/app/bsky/feed/getAuthorFeed.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/tests/views/author-feed.test.ts
- packages/pds/src/app-view/api/app/bsky/feed/getAuthorFeed.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/getAuthorFeed.ts
- packages/pds/tests/views/author-feed.test.ts
Adds a `filter` parameter to the `getAuthorFeed` query so that we can return `posts` (the default, includes replies), `posts_no_replies`, and only `posts_with_media`.
> add filter param to getAuthorFeed

- .github/workflows/build-and-push-bsky-aws.yaml
- .github/workflows/build-and-push-bsky-ghcr.yaml
- .github/workflows/build-and-push-pds-aws.yaml
- .github/workflows/build-and-push-pds-ghcr.yaml
The build and push images actions fail for forks which in turn create a lot of failure noise.
This PR runs the actions only for the original `bluesky-social/atproto` repository on the `main` branch.
Do not merge if you wish to build and push main branches from other repositories.
> Require bluesky-social/atproto for .github/workflows/build-and-push-*

- packages/bsky/src/db/db.ts
- packages/bsky/tests/db.test.ts
Avoids potential crash on certain kinds of connection errors on appview.
> Handle db client errors on appview

- packages/bsky/src/db/db.ts
- packages/bsky/tests/db.test.ts
Same as #1481 but for unhandled db pool errors 🙃
> Handle db pool errors on appview

- packages/bsky/src/config.ts
- packages/bsky/src/index.ts
- packages/bsky/src/indexer/config.ts
- packages/bsky/src/indexer/index.ts
- packages/bsky/src/services/indexing/index.ts
- packages/pds/src/api/com/atproto/admin/updateAccountHandle.ts
- packages/pds/src/api/com/atproto/identity/updateHandle.ts
- packages/pds/src/services/account/index.ts
- packages/pds/tests/handles.test.ts
- packages/pds/tests/sync/subscribe-repos.test.ts
Makes it easier to get back on track if your account has an "invalid handle"
- makes update handle idempotent - except for publishing a handle update event - as a way to prompt downstream services to revalidate your handle
- the same on the admin route so that we can aid users in getting back on track
- while we generally revalidate handles every 24hrs, revalidate "invalid" handles every hour to more quickly get users back on track
Closes https://github.com/bluesky-social/atproto/issues/1473
> Handle revalidation

- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/tests/views/author-feed.test.ts
- packages/pds/src/app-view/api/app/bsky/feed/getAuthorFeed.ts
- packages/pds/tests/views/author-feed.test.ts
Fixes https://github.com/bluesky-social/social-app/issues/1167
> only include media posts by post creator

- packages/bsky/tests/views/author-feed.test.ts
- packages/pds/tests/views/author-feed.test.ts
Just noticed I had missed these — tests were passing but we'd probably see some unexpected results here at some point.
> make sure to await rejected promise expectations

- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
The PDS passes through role auth to the appview, but the appview wasn't accepting it.  Now it does!
> Fix auth on bsky author feed

- packages/bsky/src/services/indexing/plugins/like.ts
- packages/bsky/src/services/indexing/plugins/repost.ts
- packages/bsky/tests/indexing.test.ts
- packages/pds/src/app-view/services/indexing/plugins/like.ts
- packages/pds/src/app-view/services/indexing/plugins/repost.ts
- packages/pds/tests/indexing.test.ts
Should fix https://github.com/bluesky-social/social-app/issues/1201
Filters out notifications for Likes and Reposts if the subject is the same as the content creator.
> Don't notify user of self-likes and self-reposts

- lexicons/com/atproto/sync/subscribeRepos.json
specifically, note that it's null for deletes. for https://github.com/bluesky-social/atproto/discussions/1252 , cc @DavidBuchanan314
thanks in advance!
> com.atproto.sync.subscribeRepos lexicon: add #repoOp description

- packages/bsky/package.json
- packages/bsky/src/services/indexing/util.ts
- packages/pds/package.json
- packages/pds/src/app-view/services/indexing/util.ts
Negative ISO years break lexical sorting, and are generally poorly behaved.  No records we're dealing with would reasonably have a negative year, so we avoid that case in appview indexing.
> Handle negative ISO year for indexing

- packages/crypto/src/const.ts
- packages/crypto/src/did.ts
- packages/identity/src/did/atproto-data.ts
- packages/identity/tests/did-document.test.ts
Adds support for parsing DID Documents with newer changes:
- `Multikey` `verificationMethod` type, in which case the key type is inferred from `publicKeyMultibase`, which includes multicodec prefix (like `did:key` does)
- support for `verificationMethod` `id` being bare `#atproto` or full DID URL plus fragement (eg, `did:plc:yk4dd2qkboz2yv6tpubpc6co#atproto`)
Implementation is a bit weird here, hacking in use of `did:key` for parsing. We might want to expose a raw "parseMulticodecMultibase" or something in the crypto library.
cc: @dholms
> identity: parse support for newer DID document format (Multikey)

- packages/identity/package.json
- packages/xrpc/package.json
- bump `@atproto-xrpc` -> 0.3.0
- bump `@atproto-identity` -> 0.2.0
- publish new `@atproto-syntax` at 0.1.0
Closes https://github.com/bluesky-social/atproto/issues/1495
> Bump pkg versions

- packages/api/src/bsky-agent.ts
- packages/api/src/types.ts
- packages/api/tests/bsky-agent.test.ts
Adds a set of helper functions to the SDK for controlling the preferences.
```typescript
getPreferences(): Promise<BskyPreferences>
setSavedFeeds(saved: string[], pinned: string[])
addSavedFeed(v: string)
removeSavedFeed(v: string)
addPinnedFeed(v: string)
removePinnedFeed(v: string)
setAdultContentEnabled(v: boolean)
setContentLabelPref(key: string, value: BskyLabelPreference)
```
> Add preferences helpers to SDK

- tsconfig.json
This disable [composite builds](https://www.typescriptlang.org/tsconfig#composite)
This may cause slightly slower builds (but only marginally in my quick test) but will stop the incremental build artifacts (`tsconfig.build.tsbuildinfo`) from sticking around which have been giving us footguns
> TS config: no composite

- packages/api/package.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/temp/upgradeRepoVersion.ts
There are two versions here because, oddly, the `*publish` hooks didn't run when I first ran `npm publish`, so `0.6.9` was pointing to `src/index.ts`. I've confirmed `0.6.10` is correct.
> @atproto/api@0.6.9

- .github/workflows/publish.yaml
Enables these perms only for this job. Based [on docs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) I think we only need these two, but I'll keep an eye on it and can open it up only as much as needed.
> enable granular perms for publish action

- lexicons/app/bsky/actor/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/defs.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
Replaces https://github.com/bluesky-social/atproto/pull/1533
For moderation purposes, we need to store the user's birth date and tell the application their age (in order to enable/disable adult content). When we introduce OAuth and permissioning to the system, we'll be able to control access to this set of preferences using its NSID. For now, it will be available to any app that the user signs into with a main password or app password.
> Add personal-details user preference with birth date

- packages/pds/src/api/com/atproto/sync/deprecated/getCheckout.ts
- packages/pds/src/api/com/atproto/sync/getRepo.ts
- packages/pds/src/sql-repo-storage.ts
We kept around the legacy repo sync impl while repos were migrating. But we can remove now that migration is done
> Remove legacy repo sync impl

- packages/dev-env/src/bin-network.ts
Proxy is behind runtime flags, so enable the proxying on all routes when using the full network in dev-env
> Enable appview proxy in dev-env full network

- packages/pds/src/services/account/index.ts
We were getting racing updates to the `putPreferences` route that would leave the table in an inconsistent state.
This applies a row lock on the user's row in the `user_account` table to ensure that these updates get linearized. This should be a short-held lock and will block other writes while it is held.
---
This seemed like the simplest implementation to prevent conflicting writes. Other options include:
- advisory lock (similar to repo writes)
- skipping on lock and returning an error instead of waiting & overwriting
- skipping the lock & retrying
- doing integrity checks at the end of the transaction to ensure we didn't leave it in a bad state & throwing if we did
- reworking the data modeling of the user-pref table so that it's a simple atomic `UPDATE`
> Prevent user pref races

- packages/pds/src/index.ts
- packages/xrpc-server/src/index.ts
- packages/xrpc-server/src/rate-limiter.ts
- packages/xrpc-server/src/util.ts
To get the ip of the client for rate limiting correctly we need to do 2 things:
- tell express to trust the proxy that it's receiving the req from (in this case the loadbalancer)
- grab the _leftmost_ (not _rightmost_) ip from the XFF header. `req.ip` does this
for reference: https://expressjs.com/en/guide/behind-proxies.html
> Get rate limit ip correctly

- packages/xrpc-server/src/rate-limiter.ts
- packages/xrpc-server/src/server.ts
- packages/xrpc-server/src/types.ts
Dynamically getting the stack for errors can be expensive.
Two changes:
- don't throw on rate limiter exceeded, instead return the error and just pass it to `next`
- don't log full error (included stack trace) for known xrpc errors. Instead, just log their status/message/name. Still log stack trace for internal server errors
> Improve xrpc server error handling

- packages/bsky/src/api/app/bsky/feed/getActorLikes.ts
- packages/pds/src/app-view/api/app/bsky/feed/getActorLikes.ts
Fixes #1574
Sort by `like.sortAt` instead of `feed_item.sortAt` **in app view only**.
> order by `like.indexedAt` in app view

- packages/bsky/src/db/migrations/20230906T222220386Z-thread-gating.ts
- packages/bsky/src/db/tables/post.ts
- packages/bsky/src/services/feed/index.ts
Creating new not null columns with a default locks the whole table. These columns serve us just as well being nullable
> Remove default value for post table invalid attrs

- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
Some clients are still publishing posts with an invalid reply root. Still track in db on indexing, but temporarily disable the check on serving views
> Temporarily disable filtering `invalidReplyRoot`s

- packages/pds/src/api/com/atproto/server/createSession.ts
Add IP into the mix to prevent an attacker from locking a user out of their account. Still prevents bruteforcing
> Tweak createSession rate limit key

- packages/xrpc-server/src/server.ts
When setting up a route with multiple ratelimits, we were storing all of them at one redis key. This ensure they each have a unique `keyPrefix`
Closes https://github.com/bluesky-social/atproto/issues/1616
> Tweak rate limit setup for multi rate limit routes

- packages/xrpc-server/src/types.ts
Zod can be fairly performance intensive when done iteratively with high load
Remove zod from the error handling check
> Remove zod from xrpc-server error handling

- lexicons/app/bsky/feed/threadgate.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/threadgate.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/threadgate.ts
- packages/lexicon/src/types.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/threadgate.ts
Re: https://github.com/bluesky-social/atproto/issues/1615
We should enforce the semantic that objects have a `properties` field declared
> Enforce properties field on lexicon object schemas

- .changeset/lazy-moons-relate.md
- packages/api/src/bsky-agent.ts
- packages/api/src/types.ts
The new preferences API for feed and thread view settings was dropping all the type information (see https://github.com/microsoft/TypeScript/issues/45367). This PR fixes that.
> Improve the types of the thread and feed preferences APIs

- packages/bsky/src/auto-moderator/abyss.ts
- packages/bsky/src/auto-moderator/index.ts
- packages/bsky/tests/auto-moderator/takedowns.test.ts
Some polish on the auto-takedown process:
- pass record URI along to abyss for easier tracking/reporting
- log that a hard takedown is happening ("warn" log level)
- create a report, in addition to the takedown itself, as a paper trail for mod team
> auto-moderator tweaks: pass along record URI, create report for takedown action

- packages/pds/src/sql-repo-storage.ts
We were streaming blocks oldest -> newest in `sync.getRepo`
For repos with a lot of churn, this meant that the root in the header would normally change by the time we got to the latest blocks.
Race conditions are still possible here, but this is a better. We can do a more comprehensive solution in PDS v2.
It has the added benefit of returning blocks higher in the MST earlier
---
We also tweak the logic of `getCarStream` such that we write each page of blocks in parallel with fetching the next page instead of doing them serially
> Reverse order of blocks from sync.getRepo

- .changeset/moody-wombats-live.md
- packages/api/src/rich-text/detection.ts
- packages/api/src/rich-text/rich-text.ts
- packages/api/tests/rich-text-detection.test.ts
Updates our rich text detection to include hashtags.
> Add hashtag detection to richtext

- packages/bsky/src/api/app/bsky/actor/searchActors.ts
- packages/bsky/src/api/app/bsky/actor/searchActorsTypeahead.ts
- packages/bsky/src/api/com/atproto/admin/searchRepos.ts
- packages/bsky/src/config.ts
- packages/bsky/src/context.ts
- packages/bsky/src/index.ts
- packages/bsky/src/services/actor/index.ts
- packages/bsky/src/services/util/search.ts
Proxy actor search queries to a skeleton service (palomar)
> Proxy search queries

- packages/bsky/src/api/app/bsky/graph/getSuggestedFollowsByActor.ts
When calculating suggested follows, do so off of recent likes.
Previously, we were not ordering, and my quick testing showed that it was grabbing old likes which is not representative of the account current interests
> Check recent likes for suggested follows

- packages/pds/src/api/com/atproto/server/updateEmail.ts
- packages/pds/tests/email-confirmation.test.ts
This is a stopgap to only allow updating email after confirmation until the app feature is out & users have had a chance to verify their email.
Otherwise their account would be briefly exposed to destructive actions by attackers without having had the chance to verify their email yet.
> Don't allow non-verified email updates until app feature is out

- packages/bsky/src/services/indexing/index.ts
There was an case in handle contention that we weren't correctly handling: a _new_ account is created that correctly uses a handle for a previously indexed account
> Bugfix: handle contention

- packages/pds/src/sql-repo-storage.ts
- packages/repo/src/util.ts
I think this was just a little hiccup from recent code shuffling around `getCarStream()`.  The blocks are written once from the call to `writeRows()` but were also getting written again inline.
> Fix writing duplicate blocks in sync.getRepo

- packages/identity/src/handle/index.ts
I had some issues when enabling a custom domain using the .well-known file method because of the EOL character – as the code currently stands, any `did` followed by an EOL character is passed for verification as:
```
"responseBody": {
"did": "<did>\n"
}
```
The presence of the trailing newline character leads to the user receiving the error "The server gave an invalid response and may be out of date". I solved the issue by removing the EOL character from my `did` file, but it would be neater if this was done for the user – especially as the EOL character is added by default by most Unix editors.
> Trim whitespace when processing dids

- packages/syntax/src/handle.ts
Alt is new and for non-DNS resolution: https://www.rfc-editor.org/rfc/rfc9476.txt
Example is for things like written docs and we shouldn't try to resolve them on the net.
> syntax: disallow .example and .alt TLDs

- packages/pds/src/api/com/atproto/server/updateEmail.ts
- packages/pds/tests/email-confirmation.test.ts
Now that the client feature is out, allow updating an account's email without a confirmation taken as long as the account has not verified their email yet.
For added security, we only allow this with a non-app-password credential
> Enable updateEmail with no token & no app password

- Makefile
Little ittybitty Makefile fix. This is a common gotcha (need to update PHONY and the actual command), not sure how to avoid the footgun though.
> makefile: fix 'logged' variant of run env

- packages/bsky/tests/views/__snapshots__/block-lists.test.ts.snap
- packages/bsky/tests/views/block-lists.test.ts
(Correct me if I'm wrong) The purpose of a blocklist should be `#modlist` so I think this test is just a typo. Doesn't affect behaviors but might be unclear to folks.
> Fix typo in bsky test: purpose is #modlist not #blocklist

- packages/pds/src/services/local/index.ts
- packages/pds/tests/proxied/read-after-write.test.ts
We weren't wrapping it in an `external` container.
Added some tests for external & image embeds
> Fix read after write on threads when posting a media embed

- .github/workflows/build-and-push-pds-aws.yaml
- packages/bsky/src/logger.ts
- packages/pds/src/logger.ts
Dumping stack trace for logs is expensive & we have tracing setup elsewhere. Instead we just log the error message & code.
> Dont dump stacktrace in http logger middleware

- packages/dev-env/src/bsky.ts
We got bday paradoxed 🙃 
Turns out both `appview_views_admin_get_moderation_reports` & `bsky_views_posts` hash to `5312`
I bumped this from 10k to 1m. Altho I'm curious if there's a reason that we require going to an int here instead of just using the string from dbPostgresSchema @devinivy?
> Prevent clashing redis namespaces in tests

- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/src/api/app/bsky/notification/listNotifications.ts
- packages/bsky/src/services/actor/index.ts
Three miscellaneous query optimizations here:
- On the author feed `posts_with_media` filter, we simplify the condition that ensures only the user's own posts are displayed (i.e. not media in their reposts).  By not referencing the `post` table here the query loosens, allowing it to do more filtering early in the query plan and make better use of the cursor index.  Hoping to see lower IO on this query.
- The query for notification skeleton was a bit bloated with joins and returned columns that went unused.  By fetching notification record contents separate from the skeleton, the intent is to make simpler queries that postgres is able to cache more efficiently.  Hoping to see lower IO on this query.
- Fetching a single actor by handle occurs on many routes, and was hitting a degenerate …
> Miscellaneous query optimizations on appview

- packages/bsky/src/did-cache.ts
- packages/pds/src/did-cache.ts
Rather than passing the whole did doc twice when upserting into the did cache, we update it using the excluded column.
> Insert to did cache using excluded column

- .changeset/new-snails-hope.md
- packages/bsky/src/did-cache.ts
- packages/identity/src/did/base-resolver.ts
- packages/identity/src/did/memory-cache.ts
- packages/identity/src/types.ts
- packages/pds/src/did-cache.ts
Update the did cache api so that prev cache results are passed into the refresh/cache methods. This enables the cache to prevent duplicate refresh writes
For similar reasons, we now return expired results with an `expired` flag instead of returning `null`.
> Dedupe did cache refreshes

- packages/pds/src/config/config.ts
- packages/pds/src/config/env.ts
- packages/pds/src/context.ts
As followup to #1729, also enabling configuration of S3-compatible credentials for the PDS blobstore.  This can be used with some services such as R2.
> Support S3-compatible credentials for pds blobstore

- packages/pds/package.json
- packages/pds/src/api/com/atproto/admin/updateAccountHandle.ts
- packages/pds/src/api/com/atproto/identity/updateHandle.ts
- packages/pds/src/api/com/atproto/server/createAccount.ts
- packages/pds/src/api/com/atproto/server/util.ts
- packages/pds/src/api/proxy.ts
- packages/pds/src/auth-verifier.ts
- packages/pds/src/context.ts
- packages/pds/src/pds-agents.ts
- packages/pds/src/services/account/index.ts
- packages/pds/src/services/index.ts
- packages/pds/src/services/moderation/index.ts
- packages/pds/src/services/moderation/views.ts
A few misc fixes, improvements, and tweaks to the entryway setup:
- Fix `getAccountByEmail()` which was giving a `null` for the user's did.
- Cache `getPds(did)` results which is in the hot path of proxying.
- Cache `AtpAgent`s for the entryway's pdses.
- Update entryway flow for updating account handles: should use pds's `admin.updateAccountHandle` endpoint to avoid entryway and pds `identity.updateHandle` routes depending on each other.
- Only include `didDoc` alongside credentials when the pds endpoint is one of the entryway's pdses.
> Entryway update handle flow, pds and agent caching

- packages/lex-cli/src/util.ts
- packages/lexicon/src/lexicons.ts
- packages/lexicon/src/types.ts
- packages/lexicon/tests/_scaffolds/lexicons.ts
- packages/lexicon/tests/general.test.ts
- packages/xrpc-server/src/server.ts
- packages/xrpc/src/client.ts
Here's what I'm seeing in the app's module initialization sequence with CPU throttling on:
It looks like we're spending client's CPU cycles validating that our own schemas are valid. I'm not sure it makes sense for a client to do that in production. From what I understand, these schemas are known at the build time, there's no way for them to have changed by any other way than deploying our code. So if they were valid when the app was built, it seems unnecessary to check whether they're valid on every end user's computer.
Without these lines, the init time shrinks considerably:
> Don't validate known lexicons at runtime

- lexicons/com/atproto/server/createAccount.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/server/createAccount.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/server/createAccount.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/server/createAccount.ts
Updates `plcOp` parameter on the `createAccount` lexicon to be `unknown` rather than `bytes`. The idea here is that we should be mirroring the PLC API more closely, while still leaving the value opaque relative to lexicon.
> Make plc op unknown object rather than bytes

- lexicons/com/atproto/server/createAccount.json
- lexicons/com/atproto/server/reserveSigningKey.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/server/createAccount.ts
- packages/api/src/client/types/com/atproto/server/reserveSigningKey.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/server/createAccount.ts
- packages/bsky/src/lexicon/types/com/atproto/server/reserveSigningKey.ts
- packages/pds/src/api/com/atproto/server/createAccount.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/server/createAccount.ts
- packages/pds/src/lexicon/types/com/atproto/server/reserveSigningKey.ts
- Add optional did on `server.reserveSigningKey` input
- Make password and email optional on `server.createAccount` (for the delegated usecase)
> Tweak schemas for entryway createAccount

- packages/pds/src/api/app/bsky/actor/getPreferences.ts
- packages/pds/src/api/app/bsky/actor/putPreferences.ts
- packages/pds/src/api/com/atproto/repo/getRecord.ts
- packages/pds/src/api/com/atproto/server/createAccount.ts
- packages/pds/src/api/com/atproto/sync/getBlob.ts
- packages/pds/tests/entryway.test.ts
- Proxy `getPreferences` and `putPreferences`
- Proxy `listRecords` to pds rather then appview when applicable.
- Do not send along email and password during account creation when acting as an entryway.
- Ensure to pass along a body with `reserveSigningKey`.
> Entryway tweaks to account creation and proxying

- packages/pds/src/auth-verifier.ts
Using the proper error code and name will allow the entryway to relate a missing account into an expired token (i.e. when an account migrates across pdses).
> Use proper error when authed account is not found

- .changeset/warm-lions-occur.md
- LICENSE-APACHE.txt
- LICENSE-MIT.txt
- LICENSE.txt
- README.md
- packages/api/README.md
- packages/bsky/README.md
- packages/common-web/README.md
- packages/common/README.md
- packages/crypto/README.md
- packages/dev-env/README.md
- packages/identity/README.md
- packages/lex-cli/README.md
- packages/lexicon/README.md
- packages/pds/README.md
- packages/repo/README.md
- packages/syntax/README.md
- packages/xrpc-server/README.md
- packages/xrpc/README.md
Had consensus on this from discussion a week or two back. Copied the license files and general structure from did-method-plc (which we updated months ago), with very minor grammar updates and link fixes.
Notified external contributors and getting sign-offs in this issue thread: https://github.com/bluesky-social/atproto/issues/1786
Will give that a couple days before merging (unless 💯 reply sooner).
> Update atproto source license to MIT/Apache2

- .changeset/dry-cameras-hang.md
I want to release https://github.com/bluesky-social/atproto/pull/1790 so we can update the client and get the perf win.
I tried to word the change from the perspective of someone updating (they might have to explicitly declare the type).
> Add changeset for #1790

- .changeset/thick-apples-invite.md
- lexicons/com/atproto/server/getSession.json
- packages/api/src/agent.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/server/getSession.ts
- packages/api/src/moderation/accumulator.ts
- packages/api/tests/agent.test.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/server/getSession.ts
- packages/pds/src/api/com/atproto/server/getSession.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/server/getSession.ts
I missed this one in #1727— we need a did doc hint in order for the client to start talking to the user's pds during session resumption.  So the `didDoc` field has been added to `getSession` output, bringing it in line with `createSession`, `refreshSession`, and `createAccount`.
> Add did doc output to getSession for session resumption

- packages/api/tests/rich-text-detection.test.ts
Noticed when debugging a ticket that we support `.php` links but didn't have a test.
> Add a test for links that end in .php

- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
Prevent self-referential loops in threads. 
This fix should prevent even multi-hop loops such as `A -> B -> C -> A...`
> Prevent thread loops

- packages/pds/src/account-manager/helpers/auth.ts
- packages/pds/src/account-manager/index.ts
- packages/pds/src/auth-verifier.ts
- packages/pds/src/config/config.ts
- packages/pds/src/config/env.ts
- packages/pds/src/context.ts
- packages/pds/tests/auth.test.ts
- packages/pds/tests/entryway.test.ts
Here we start setting and validating audience claims on access and refresh tokens on the pds.  This is particularly useful when using the pds with an entryway service, which sets the audience claim in the credentials that it generates.
> Set and validate token audiences on pds v2

- packages/api/tests/agent.test.ts
- packages/pds/src/api/com/atproto/repo/uploadBlob.ts
- packages/pds/src/api/com/atproto/server/createAccount.ts
- packages/pds/src/api/com/atproto/sync/getBlob.ts
- packages/pds/src/api/proxy.ts
- packages/pds/tests/entryway.test.ts
- Entryway allows streaming blob uploads to pds.
- Entryway redirects to backing pds on get-blobs.
- Entryway create account endpoint handling the pds-behind-entryway flow (did + plc op, no email + password) for testing purposes.  Re-enable entryway tests.
> Polish on entryway blob uploads and gets

- packages/bsky/src/api/com/atproto/admin/reverseModerationAction.ts
- packages/bsky/src/api/com/atproto/admin/takeModerationAction.ts
- packages/bsky/src/api/com/atproto/admin/util.ts
- packages/bsky/src/config.ts
- packages/bsky/src/context.ts
- packages/bsky/src/db/periodic-moderation-action-reversal.ts
- packages/dev-env/src/network.ts
The moderation functionality on the appview would fan out status changes to the affected user's pds.  We may want to do something like that eventually, but for now we simplify down to a single configured url.
> Simplify moderation fanout to configured url

- packages/aws/src/s3.ts
- packages/pds/src/actor-store/blob/transactor.ts
- packages/pds/src/disk-blobstore.ts
- packages/pds/tests/transfer-repo.test.ts
Update subject status should be idempotent, but right now we throw if you try to quarantine a blob that either does not exist or is already quarantined
> Handle quarantining/unquarantining a blob that does not exist

- lexicons/com/atproto/admin/deleteAccount.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/admin/deleteAccount.ts
- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/admin/deleteAccount.ts
- packages/pds/src/api/com/atproto/admin/deleteAccount.ts
- packages/pds/src/api/com/atproto/admin/index.ts
- packages/pds/src/api/com/atproto/admin/sendEmail.ts
- packages/pds/src/api/com/atproto/server/deleteAccount.ts
- packages/pds/src/api/com/atproto/server/requestAccountDelete.ts
- packages/pds/src/api/com/atproto/server/requestEmailUpdate.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/admin/deleteAccount.ts
- packages/pds/tests/account-deletion.test.ts
Implements a new `com.atproto.admin.deleteAccount` endpoint on pds v2.  This supports account deletion across a pds and its entryway.  The proposed flow for account deletion  across a pds and its entryway is:
```
pds(server.deleteAccount)            [dumb proxy to entryway]
-> entryway(server.deleteAccount)  [performs acct deletion on entryway then calls to pds]
-> pds(admin.deleteAccount)        [performs acct deletion on pds]
```
> PDS v2 entryway account deletion

- lexicons/com/atproto/admin/deleteAccount.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/admin/deleteAccount.ts
- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/admin/deleteAccount.ts
- packages/pds/src/api/app/bsky/actor/putPreferences.ts
- packages/pds/src/api/com/atproto/moderation/createReport.ts
- packages/pds/src/api/com/atproto/server/deleteAccount.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/admin/deleteAccount.ts
- packages/pds/src/services/account/index.ts
- packages/pds/src/util/retry.ts
- packages/pds/tests/sync/subscribe-repos.test.ts
Pairs with #1819 to implement the account deletion flow between the pds and its entryway.  This work contains the work done on the entryway.  Also contains a couple additional `ensureThisPds()` calls where possible to ensure all preferences and reports are being channeled to the pds properly right after a migration.
> Entryway-to-pds account deletion flow

- packages/common-web/src/async.ts
- packages/pds/src/api/com/atproto/temp/importRepo.ts
The connection for import may be getting aborted because the PDS is doing work and does not send data fast enough to keep the connection open.
This introduces a simple mechanism to send data on the connection at least every second to try to ensure that it stays alive
> Send ticks during import

- packages/bsky/src/api/app/bsky/actor/getSuggestions.ts
- packages/bsky/tests/views/suggestions.test.ts
- packages/pds/tests/proxied/__snapshots__/views.test.ts.snap
Return randomized suggestions instead of always in order.
However, always return the first two in order - bsky.app & atproto.com in our case
Since this breaks our previous pagination mechanism which relied on order, we prevent duplicate results by building a cursor out of all previously included ids concatenated together.
> Randomize suggestions

- packages/bsky/src/api/app/bsky/feed/searchPosts.ts
- packages/bsky/src/api/index.ts
- packages/pds/src/api/app/bsky/feed/index.ts
- packages/pds/src/api/app/bsky/feed/searchPosts.ts
This adds `app.bsky.feed.searchPosts` to the bluesky appview by proxying to a dedicated search skeleton service - Palomar in our case
> Add searchPosts api to appview

- README.md
You find that out when you try to run the command, but IMO an explicit mention in README always helps adjust expectations.
> Add a note to README about depending on jq and docker

- packages/bsky/src/api/app/bsky/feed/searchPosts.ts
We weren't passing along additional output data from `searchPostsSkeleton`
Closes https://github.com/bluesky-social/atproto/issues/1856
> Pass along hitsTotal and cursor from searchPostsSkeleton

- lexicons/com/atproto/temp/fetchLabels.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/temp/fetchLabels.ts
- packages/bsky/src/api/com/atproto/temp/fetchLabels.ts
- packages/bsky/src/api/index.ts
- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/temp/fetchLabels.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/temp/fetchLabels.ts
This is a temporary method for fetching all labels from a labeler based on time.
This is being introduced in lieu of [`com.atproto.label.subscribeLabels`](https://github.com/bluesky-social/atproto/blob/main/lexicons/com/atproto/label/subscribeLabels.json) to avoid implemented a new streaming interface on the current appview. However, the expectation is that it will be used in a similar manner - to stay up to date with a given labeler's entire label set.
> Add temp.fetchLabels method

- packages/bsky/src/api/com/atproto/temp/fetchLabels.ts
- packages/xrpc-server/src/util.ts
- packages/xrpc/src/client.ts
Two issues: 
- we weren't correctly formatting undefined cids on method output
- for large integer query params were getting messed up by an xrpc util - we were using the bitwise OR operator (`|`) instead of the logical OR operator (`||`) to recover from unparseable numbers
> Bugfix: fetchLabels

- packages/pds/src/api/com/atproto/temp/importRepo.ts
- packages/repo/src/util.ts
`CarReader` reads and parses the whole car file before iterating over blocks. This reading and parsing, though async, does not leave room for event loop scheduling, so we break it up with `setImmediate`.
As well, we undo a change that I made that buffered the whole car file before parsing and instead just pass the car stream into the reader
> Async car reader

- packages/pds/src/api/com/atproto/sync/getBlob.ts
- packages/pds/src/auth-verifier.ts
- packages/pds/tests/moderation.test.ts
Two fixes here on pds v2:
- Ensure the access-or-role auth verifier works with non-admin roles.
- Ensure taken down actors can fetch their own blobs, admins can fetch their blobs, and others cannot fetch their blobs.
> Fix role auth for access-or-role verifier, getBlob check on actor takedowns

- .changeset/modern-planets-change.md
- interop-test-files/crypto/signature-fixtures.json
- packages/crypto/src/p256/operations.ts
- packages/crypto/src/secp256k1/operations.ts
- packages/crypto/src/types.ts
- packages/crypto/tests/signatures.test.ts
- packages/xrpc-server/src/auth.ts
We want a canonical representation for every signature. Otherwise a commit or a plc operation can be deterministically transformed such that it has a different CID (without possession of the private key).
The crypto library that we use allows signatures to be encoded as compact bytes or DER-encoded.
This leads to similar consequences as allowing high-s signatures (which we disallow for repo commits & plc operations).
As a fix, we alter the signature verification logic to first parse the signature from compact bytes before passing to the verify function.
In some cases where distributed consensus is not necessary, such as JWT signatures, we allow DER signatures as well as high-s signatures.
---
Reference:
https://github.com/did-method-plc/did-method-plc/issues/53 …
> Prevent signature malleability

- packages/common-web/src/retry.ts
- packages/common-web/tests/retry.test.ts
- packages/pds/src/account-manager/helpers/account.ts
- packages/pds/src/account-manager/helpers/auth.ts
- packages/pds/src/account-manager/helpers/email-token.ts
- packages/pds/src/account-manager/helpers/invite.ts
- packages/pds/src/account-manager/helpers/password.ts
- packages/pds/src/account-manager/helpers/repo.ts
- packages/pds/src/account-manager/index.ts
- packages/pds/src/actor-store/index.ts
- packages/pds/src/actor-store/record/transactor.ts
- packages/pds/src/db/db.ts
- packages/pds/src/db/util.ts
- packages/pds/src/did-cache/index.ts
- packages/pds/src/sequencer/sequencer.ts
The issue with sqlite's busy timeout is that it may cause unnecessary blocking in the node process.  This moves sqlite's busy timeout handling up into the application, using the same backoff/retry approach that sqlite itself employs.
- Run transactions with busy handling.
- Run writes outside of transactions with busy handling.
- Move WAL mode outside of db opening, into the db creation/migration process.  This avoids a "long" (sub-millisecond) block that occurs every time a db is opened.
- Refactor retry helper to allow different backoff strategies including max timeouts, add tests.
Some portions of this will be easier to review [ignoring whitespace changes](https://github.com/bluesky-social/atproto/pull/1871/files?w=1).
> App-level retries for sqlite on pds

- packages/pds/src/api/com/atproto/server/updateEmail.ts
- packages/pds/src/db/util.ts
- packages/pds/src/services/account/index.ts
- packages/pds/tests/email-confirmation.test.ts
Previously users would receive a 500 when attempting to change their email to one that is already in use.  With this change they should receive a 400 with an actionable error message.
> Provide proper error for updating to an email that's already in use

- packages/bsky/src/api/app/bsky/feed/getFeed.ts
- packages/bsky/src/auth.ts
- packages/bsky/src/context.ts
- packages/bsky/src/feed-gen/best-of-follows.ts
- packages/bsky/src/feed-gen/bsky-team.ts
- packages/bsky/src/feed-gen/hot-classic.ts
- packages/bsky/src/feed-gen/mutuals.ts
- packages/bsky/src/feed-gen/types.ts
- packages/bsky/src/feed-gen/whats-hot.ts
- packages/bsky/src/feed-gen/with-friends.ts
- packages/bsky/tests/__snapshots__/feed-generation.test.ts.snap
- packages/bsky/tests/feed-generation.test.ts
By making auth optional on `app.bsky.feed.getFeed`, we open the door to public usage of feeds via the appview if the feed chooses to support it.
> Support unauthed usage of feeds

- packages/pds/src/services/local/index.ts
- packages/pds/tests/proxied/read-after-write.test.ts
- adds missing `aspectRatio` property when providing read-sticky posts
- adds missing test case for alt text
> fix(pds): include aspectRatio on read-sticky posts

- .changeset/brave-swans-kiss.md
- packages/syntax/src/aturi_validation.ts
Creating error objects is not super cheap because it requires the runtime to capture a stack trace. Currently we're creating a lot of error objects every time we handle a response because of this logic.
This logic tries to validate that something is *either* a DID or a handle by trying to validate one option in a try, and falling back to validating another option in a catch. However, DIDs and handles are mutually exclusive, and we can always tell early which validation function to use. So let's do that so that we don't create throwaway error objects on non-exceptional situations.
I enabled "pause on caught exceptions" and tried to paginate Notifications.
https://github.com/bluesky-social/atproto/assets/810438/dc62fbc8-c773-44b1-a5de-7b816e81a069 …
> Don't create unnecessary error objects

- .changeset/spotty-guests-taste.md
> Contains breaking lexicon changes: removing legacy com.atproto admin endpoints, making uri field required on app.bsky list views.
> Additional @atproto/api 0.6.24 changeset

- services/bsky/api.js
In prod/staging, we run migrations manually, but in other environments (for instance sandbox) we run them automatically
> Add flag for running db migrations on appview

- packages/bsky/src/daemon/config.ts
- packages/bsky/src/daemon/context.ts
- packages/bsky/src/daemon/index.ts
- packages/bsky/src/daemon/logger.ts
- packages/bsky/src/daemon/notifications.ts
- packages/bsky/src/daemon/services.ts
- packages/bsky/src/index.ts
- packages/bsky/src/services/actor/index.ts
- packages/bsky/src/services/indexing/index.ts
- packages/bsky/src/services/util/notification.ts
- packages/bsky/tests/daemon.test.ts
- packages/bsky/tests/views/profile.test.ts
- services/bsky/daemon.js
This adds a daemon to the appview that cleans-up outdated notifications.  The daemon has its own service entrypoint.  We might consider moving the materialized view maintainer into this service as well.
The rules for removing old notifications are based on three thresholds: "days-before-last-seen", "days-before-latest-unread", and an "unread-kept-count".  Read notifications are removed when they are older than "days-before-last-seen" as compared to the last time the user saw their notifications.  Unread notifications are only removed when the user has more notifications than than the "unread-kept-count".  Once that threshold is hit, notifications are removed if they are older than "days-before-latest-unread" as compared to their most recent notification.
> Cleanup outdated notifications in appview, add daemon for similar tasks

- packages/pds/src/db/util.ts
There were some subclasses of `SQLITE_BUSY` that we weren't retrying on, and there's no reason not to be comprehensive here.
> Retry on all SQLITE_BUSY error codes

- packages/lex-cli/src/codegen/client.ts
- packages/lex-cli/src/codegen/lex-gen.ts
- packages/lex-cli/src/codegen/server.ts
- packages/lexicon/src/lexicons.ts
This change ensures that:
1) the `types` argument contains only correct value types (no typo)
2) the returned value type is properly narrowed when a `types` argument is provided, removing the need to type cast the returned value.
> feat: infer definition type from "types" argument in getDefOrThrow

- services/bsky/api.js
We no longer use the `algo_whats_hot_view` in production, so we can stop running the view maintainer there.
> Stop running what's hot view maintainer on appview

- lexicons/app/bsky/notification/listNotifications.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/notification/listNotifications.ts
- packages/bsky/src/api/app/bsky/notification/listNotifications.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/notification/listNotifications.ts
- packages/bsky/tests/views/notifications.test.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/notification/listNotifications.ts
Adds the optional field `seenAt` to `listNotifications` which allows a service to inform the client of their currently tracked last seen time.
> Add seenAt time to listNotifications

- packages/bsky/src/api/app/bsky/actor/getProfile.ts
- packages/bsky/src/services/moderation/index.ts
- packages/bsky/tests/views/profile.test.ts
When accessing a takendown profile, check if the takedown is a temporary suspension or permanent
> Report separate error on getProfile for account suspension

- .github/workflows/build-and-push-bsky-aws.yaml
- packages/bsky/src/api/app/bsky/feed/getTimeline.ts
- packages/bsky/tests/views/timeline.test.ts
On `getTimeline`, the `limit=1` case is used commonly to check if there are new items at the top of the timeline. Since it's so common, this is a shot at optimizing it.  The most common strategy that postgres takes to build a timeline is to grab all recent content from each of the user's follow, then paginate it. The downside here is that it requires grabbing all recent content from all follows, even if you only want a single result.  The approach here instead takes the single most recent post from each of the user's follows, then sorts only those and takes the top item.
> Optimize timeline for limit=1

- packages/bsky/src/api/health.ts
These provide helpful context (instead of just a generic 404). We might *also* want to set up load-balancer redirects, but having some default HTTP 200 has been helpful for, eg, local dev.
The robots.txt in particular will show up for public.api.bsky.app
Mostly copied these from the PDS equivalents.
> bsky: add top-level and robots.txt endpoints

- .github/workflows/build-and-push-bsky-aws.yaml
- services/bsky/api.js
Enables the ability to cluster on the bsky api frontends.  Configured on by setting `CLUSTER_WORKER_COUNT` to a value (should generally be between 2 and the number of cpus on the machine).
> Experimental node clustering for bsky frontends

- .github/workflows/build-and-push-bsky-ghcr.yaml
- packages/bsky/src/config.ts
- packages/bsky/src/data-plane/client.ts
- packages/bsky/src/index.ts
- packages/dev-env/src/bsky.ts
Support using http2 to talk to the dataplane.  Also supports an option to ignore tls for testing and local usage.
> Support http2 client for appview dataplane

- .github/workflows/build-and-push-bsky-ghcr.yaml
- packages/bsky/src/config.ts
- packages/bsky/src/data-plane/client.ts
- packages/bsky/src/index.ts
- packages/dev-env/src/bsky.ts
This allows this appview to support multiple dataplane urls.  When a response indicates that one dataplane server is unavailable, it immediately retries on another one.
> Support multiple dataplane urls for appview

- services/pds/Dockerfile
There's an incompatibility between sharp and the version of alpine linux used in the pds's docker build.  It started surfacing when the the node docker image updated their version of alpine. This pins alpine linux to the most recent working version.
The longer-term fix will likely be to upgrade sharp and alpine linux at the same time.  I tried to get this going, but transitive dependencies with the entryway got in the way.
Ref: https://github.com/nodejs/docker-node/issues/2009
> Pin alpine version temporarily for pds docker build

- .changeset/odd-kids-warn.md
- lexicons/app/bsky/embed/external.json
- lexicons/app/bsky/embed/images.json
- packages/api/src/client/lexicons.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/lexicons.ts
The most sensitive thing here is putting a (very long!) length limit on alt text. I believe this is long enough to not cause accessibility issues, but can update if needed.
The motivation is that an issue with very long embed image descriptions came up that has been causing records to be discarded by golang code. We'll separately work around that by bumping limits in the CBOR library (cborgen), but I think communicating some reasonable limit on these fields is helpful. This isn't intended to be antagonistic; the current problematic records seem to have huge values *by mistake* not intentionally.
While I was at it I did an informal review of all the "string" fields in records (I might have missed a couple, this was an informal scan).
These are technically violations of Lexicon stability, …
> lexicons: more string limits

- .changeset/chilled-ghosts-enjoy.md
- packages/api/src/agent.ts
- packages/api/src/types.ts
- packages/api/tests/agent.test.ts
- packages/pds/src/account-manager/helpers/auth.ts
**Motivation:** flaky networks currently result in the app nuking JWTs, effectively logging the user out. We want to log out the user if the session is invalid, but for other unknowns, we can keep it around on-device until we get a legit response from our server that says otherwise.
This PR adds an additional `AtpSessionEvent` event, `network-error`, and emits that event from `resumeSession` if we catch an unexpected exception.
> Improve handling of `resumeSession` failures

- .github/workflows/build-and-push-bsky-aws.yaml
- packages/bsky/src/auto-moderator/index.ts
Use `emitModerationAction` to create a report from automod rather than `createReport`. This simplifies the possible communication/auth flows between automod & ozone
> Automod: create reports using emitModerationAction

- packages/bsky/src/config.ts
- packages/bsky/src/data-plane/server/routes/labels.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/src/hydration/label.ts
- packages/bsky/src/index.ts
- packages/dev-env/src/bsky.ts
- packages/dev-env/src/seed/basic.ts
When talking to the dataplane, the appview may want to specify one or more labelers from which it always receives labels.  This adds a configuration `BSKY_LABELS_FROM_ISSUER_DIDS` which may be a comma-separated list of labeler dids.
> Support label issuer tied to appview v2

- packages/bsky/src/api/app/bsky/feed/getFeed.ts
- packages/pds/src/api/app/bsky/feed/getFeed.ts
Forwards headers from getFeed req to the feed generator. In light of [this PR adding an Accept-Language header to requests from the frontend](https://github.com/bluesky-social/social-app/pull/2457), this will enable feed generators to respect the user's language preferences.
> Pass headers to feed generator

- packages/bsky/src/api/app/bsky/feed/getFeed.ts
- packages/bsky/src/feed-gen/types.ts
- packages/common-web/src/util.ts
- packages/pds/src/api/app/bsky/feed/getFeed.ts
- packages/xrpc-server/src/util.ts
Building on https://github.com/bluesky-social/atproto/pull/2030
Tidy code a bit to bring it in line with our style & forward `content-language` header on responses to make the negotiation symmetrical
> Tidy feed generator language headers

- packages/bsky/proto/bsky.proto
- packages/bsky/src/api/app/bsky/feed/getActorLikes.ts
- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/src/api/app/bsky/feed/getFeed.ts
- packages/bsky/src/api/app/bsky/feed/getListFeed.ts
- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
- packages/bsky/src/api/app/bsky/feed/getPosts.ts
- packages/bsky/src/api/app/bsky/feed/getTimeline.ts
- packages/bsky/src/api/app/bsky/feed/searchPosts.ts
- packages/bsky/src/api/app/bsky/unspecced/getTimelineSkeleton.ts
- packages/bsky/src/api/feed-gen/types.ts
- packages/bsky/src/data-plane/gen/bsky_pb.ts
- packages/bsky/src/data-plane/server/routes/feeds.ts
- packages/bsky/src/hydration/actor.ts
- packages/bsky/src/hydration/feed.ts
- packages/bsky/src/hydration/graph.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/src/hydration/label.ts
- packages/bsky/src/hydration/util.ts
- packages/bsky/src/views/index.ts
A few improvements here to the appview:
- take advantage of feed items containing both post and repost uris.
- plumb uris+cids together through to dataplane methods where applicable (mostly for interaction counts and post viewer state).
- avoid calling into dataplane with empty lists.
> Plumb feed items and cids to dataplane, avoid empty calls

- packages/bsky/src/api/app/bsky/actor/searchActors.ts
- packages/bsky/src/api/app/bsky/actor/searchActorsTypeahead.ts
- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
- packages/bsky/src/api/app/bsky/feed/searchPosts.ts
- packages/bsky/src/api/app/bsky/notification/registerPush.ts
- packages/bsky/src/api/app/bsky/unspecced/getPopularFeedGenerators.ts
- packages/bsky/src/config.ts
- packages/bsky/src/context.ts
- packages/bsky/src/data-plane/client.ts
- packages/bsky/src/data-plane/server/routes/search.ts
- packages/bsky/src/index.ts
- packages/pds/tests/proxied/views.test.ts
A small smattering of changes:
- using the search service for now to handle search skeletons, rather than the dataplane.
- support receiving not-found error from dataplane thread skeleton.
- make some endpoints fail that are not implemented on v2.
> Appview v2 search, post threads fix, todos

- packages/bsky/src/api/app/bsky/notification/listNotifications.ts
Appview v2 needs to handle empty cursors coming from the dataplane, looks like this one on `listNotifications` was just missed.
> Appview v2: handle empty cursor on list notifications

- packages/bsky/src/api/app/bsky/feed/getLikes.ts
- packages/bsky/src/api/com/atproto/admin/getAccountInfos.ts
- packages/bsky/src/data-plane/server/routes/records.ts
- packages/bsky/src/hydration/actor.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/src/hydration/util.ts
- packages/bsky/src/views/index.ts
- packages/bsky/src/views/util.ts
We can defer to the bsky dataplane for sorted-at times on records.  This is generally a composite of the record's creation and indexed times.
> Appview v2: utilize sorted-at field in bsky protos

- .github/workflows/build-and-push-bsync-aws.yaml
- .github/workflows/build-and-push-bsync-ghcr.yaml
- packages/bsync/proto/bsync.proto
- packages/bsync/src/config.ts
- packages/bsync/src/gen/bsync_pb.ts
- packages/bsync/src/routes/add-mute-operation.ts
- services/bsync/Dockerfile
- services/bsync/index.js
This gets docker builds going on bsync.  Made a couple misc fixes along the way:
- dockerfile needed some tweaks.
- updated the protos to fit grpc conventions.
- support optional db migration on start.
- setup github workflows, will build on `services/bsync` branch rather than `main` for now.
> Prepare docker builds of bsync

- packages/pds/src/api/com/atproto/repo/uploadBlob.ts
Add a rate limit of 1000 blobs/day to `uploadBlob`. This should be high enough for nearly all current accounts/bots, but prevents some bots doing obvious resource abuse.
> Add uploadBlob rate limit

- packages/bsky/src/api/app/bsky/unspecced/getPopularFeedGenerators.ts
For the time being just going to piggyback off of the `GetSuggestedFeeds` dataplane endpoint to support `getPopularFeedGenerators` in appview v2.  In the future we may have a separate one to support this use case.
> Appview v2 initial implementation for getPopularFeedGenerators

- lexicons/app/bsky/unspecced/getTaggedSuggestions.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/unspecced/getTaggedSuggestions.ts
- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/unspecced/getTaggedSuggestions.ts
- packages/pds/src/api/app/bsky/unspecced/getTaggedSuggestions.ts
- packages/pds/src/api/app/bsky/unspecced/index.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/unspecced/getTaggedSuggestions.ts
Sister PR to https://github.com/bluesky-social/atproto/pull/2077 adding functionality to entryway
> Entryway: tagged suggestions

- lexicons/app/bsky/graph/defs.json
- lexicons/app/bsky/graph/getRelationships.json
This proposes the endpoint schema for a public (not auth'd) endpoint for fetching the public bsky social graph relationships (follows and blocks) between one actor and a list of "other" actors.
The initial motivation is to use this metadata from automod, for example in the context of a reply (wanting to know the relationships with the "root" and "parent" post authors.
If this looks good, would pass off to one of the backend folks to wire up and implement. v2 implementation should be simple, re-using an existing dataplane helper.
> lexicons: new app.bsky.graph.getRelationships endpoint

- packages/bsky/src/data-plane/client.ts
Tweaks the dataplane retry logic so that we don't retry on a host when it's down.
> Appview v2 dataplane retries based on client host

- packages/bsky/src/api/app/bsky/actor/getSuggestions.ts
- packages/bsky/src/api/app/bsky/actor/searchActors.ts
- packages/bsky/src/api/app/bsky/feed/getActorFeeds.ts
- packages/bsky/src/api/app/bsky/feed/getActorLikes.ts
- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/src/api/app/bsky/feed/getFeed.ts
- packages/bsky/src/api/app/bsky/feed/getLikes.ts
- packages/bsky/src/api/app/bsky/feed/getListFeed.ts
- packages/bsky/src/api/app/bsky/feed/getRepostedBy.ts
- packages/bsky/src/api/app/bsky/feed/getSuggestedFeeds.ts
- packages/bsky/src/api/app/bsky/feed/getTimeline.ts
- packages/bsky/src/api/app/bsky/feed/searchPosts.ts
- packages/bsky/src/api/app/bsky/graph/getBlocks.ts
- packages/bsky/src/api/app/bsky/graph/getFollowers.ts
- packages/bsky/src/api/app/bsky/graph/getFollows.ts
- packages/bsky/src/api/app/bsky/graph/getList.ts
- packages/bsky/src/api/app/bsky/graph/getListBlocks.ts
- packages/bsky/src/api/app/bsky/graph/getListMutes.ts
- packages/bsky/src/api/app/bsky/graph/getLists.ts
- packages/bsky/src/api/app/bsky/graph/getMutes.ts
- packages/bsky/src/api/app/bsky/notification/listNotifications.ts
- packages/bsky/src/api/app/bsky/unspecced/getPopularFeedGenerators.ts
- packages/bsky/src/api/app/bsky/unspecced/getTimelineSkeleton.ts
- packages/bsky/src/db/pagination.ts
- packages/bsky/tests/views/notifications.test.ts
- packages/bsky/tests/views/timeline.test.ts
This adjusts the appview so that clearly mismatching cursors return an empty result set rather than failing with an error.  Cursors that are close to the format but "not quite" there may still produce an error since it indicates some ambiguity.  This should facilitate a potential change in the cursor format without significantly affecting consumers.
> Appview v1 handling clearly bad cursors

- packages/ozone/src/api/temp/fetchLabels.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/src/mod-service/types.ts
- packages/ozone/tests/__snapshots__/get-record.test.ts.snap
- packages/ozone/tests/__snapshots__/get-repo.test.ts.snap
- packages/ozone/tests/moderation.test.ts
While the names/semantics of these labels get nailed down, move to a clearly unspecced label for relating takedowns.  Based on top of #2069.
> Temporary unspecced labels relating takedowns in ozone

- packages/ozone/src/api/admin/emitModerationEvent.ts
- packages/ozone/src/api/temp/fetchLabels.ts
- packages/ozone/src/context.ts
- packages/ozone/src/daemon/context.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/src/mod-service/types.ts
- packages/ozone/tests/__snapshots__/get-record.test.ts.snap
- packages/ozone/tests/__snapshots__/get-repo.test.ts.snap
- packages/ozone/tests/moderation-appeals.test.ts
- packages/ozone/tests/moderation.test.ts
Adds two new labels to Ozone: `!takedown` and `!takedown-blobs`. These are imperative labels that instruct downstream services to remove the labels content from their indices entirely. `!takedown-blobs` has a subject of a record, and the semantic is to purge all blobs referenced by that record.
These labels are automatically applied when performing a takedown on either a repo or record.
> Ozone !takedown labels

- packages/bsky/src/api/app/bsky/actor/getProfile.ts
- packages/bsky/src/api/app/bsky/actor/getProfiles.ts
- packages/bsky/src/api/app/bsky/feed/getActorLikes.ts
- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/src/api/app/bsky/feed/getListFeed.ts
- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
- packages/bsky/src/api/app/bsky/feed/getTimeline.ts
Repo rev is processed last on record ingestion but is being grabbed first on view construction.
Change the order of fetching repoRev to the last thing we do before sending the response out. 
This will cause read-after-write behavior to err on the side of not showing the post rather than showing duplicates
> Fix timing on appview v2 repo rev header

- packages/bsky/src/hydration/graph.ts
Users aren't able to block themselves: now enforcing that in the logic for 3p blocks.
> Appview v2 don't apply 3p self blocks

- packages/bsky/proto/bsky.proto
- packages/bsky/src/api/app/bsky/unspecced/getPopularFeedGenerators.ts
- packages/bsky/src/data-plane/server/routes/feed-gens.ts
- packages/bsky/src/proto/bsky_connect.ts
- packages/bsky/src/proto/bsky_pb.ts
- packages/bsky/tests/__snapshots__/feed-generation.test.ts.snap
- packages/bsky/tests/feed-generation.test.ts
Uses new dataplane endpoint to search feed generators on `getPopularFeedGenerators`.
> Appview v2 search for feed generators

- packages/pds/src/api/com/atproto/server/createAccount.ts
- packages/pds/src/config/config.ts
- packages/pds/src/config/env.ts
Add a specially configured phone number that allows you to bypass required phone verification on `createAccount`
> Phone verification bypass number

- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/src/api/app/bsky/graph/getRelationships.ts
- packages/bsky/src/data-plane/server/routes/relationships.ts
- packages/bsky/src/hydration/actor.ts
- packages/bsky/src/hydration/hydrator.ts
When hydrating a profile basic, check to ensure that relevant mod lists both exist & are have a purpose of being modlists. If the list does not exist as a modlist, then remove it from profile viewer state so that it does not affect filtering & views
> Appview v2: don't apply missing modlists

- packages/bsky/src/views/index.ts
- packages/bsky/tests/views/thread.test.ts
The idea here is to ensure all posts in a given thread view have the same root as the anchor post.  During hydration we were looking-up each post in the thread's root, and as a result even bad roots would ended-up presented inside the thread if they were referenced somewhere.  When posts are well-behaved and set the parent/root as intended it's not an issue, so this is a bit of an edge case.
> Appview v2 enforce post thread root boundary

- packages/pds/src/api/com/atproto/server/requestAccountDelete.ts
- packages/pds/src/api/com/atproto/server/requestEmailConfirmation.ts
- packages/pds/src/api/com/atproto/server/requestEmailUpdate.ts
- packages/pds/src/api/com/atproto/server/requestPasswordReset.ts
Add email & ip based rate limits to email routes to prevent abuse
> Add rate limits to email routes

- packages/pds/src/account-manager/helpers/email-token.ts
- packages/pds/src/account-manager/index.ts
https://github.com/bluesky-social/atproto/pull/2130
> Clear email tokens on email update

- README.md
This PR updates the two links in README.md that point to `blueskyweb.xyz` to the equivalent `bsky.social` URLs.
On a related note: does this email address need updating or is it still valid?
https://github.com/bluesky-social/atproto/blob/9579bec720d30e40c995d09772040212c261d6fb/package.json#L5
> Update `blueskyweb.xyz` links in README.md to `bsky.social`

- .changeset/angry-chicken-float.md
- packages/repo/src/types.ts
To match spec change: https://github.com/bluesky-social/atproto-website/pull/291
Decided not to bite of subscription event schema changes in this PR. The fields are already marked as deprecated there.
> repo: commit prev as nullable, but non-optional

- .changeset/silly-ligers-poke.md
- lexicons/app/bsky/actor/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/defs.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/actor/defs.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
Adds an optional pref to `savedFeedsPref` for storing the index of the basic timeline so that it doesn't always need to be the first feed.
> Timeline index pref

- lexicons/com/atproto/sync/subscribeRepos.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/post.ts
- packages/api/src/client/types/com/atproto/sync/subscribeRepos.ts
- packages/bsky/src/indexer/subscription.ts
- packages/bsky/src/ingester/subscription.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/post.ts
- packages/bsky/src/lexicon/types/com/atproto/sync/subscribeRepos.ts
- packages/dev-env/src/network.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/feed/post.ts
- packages/ozone/src/lexicon/types/com/atproto/sync/subscribeRepos.ts
- packages/pds/src/api/com/atproto/server/activateAccount.ts
- packages/pds/src/api/com/atproto/server/createAccount.ts
- packages/pds/src/api/com/atproto/server/deleteAccount.ts
- packages/pds/src/api/com/atproto/sync/subscribeRepos.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/post.ts
- packages/pds/src/lexicon/types/com/atproto/sync/subscribeRepos.ts
- packages/pds/src/sequencer/db/schema.ts
- packages/pds/src/sequencer/events.ts
- packages/pds/src/sequencer/sequencer.ts
- packages/pds/tests/sequencer.test.ts
Adds a new `#identity` to the firehose that prompts all downstream services to refresh their identity cache for the given DID.
This is implemented in lieu of the `#migrate` event and will eventually replace the `#handle` event as well.
In a future iteration, more information may be attached to the event such as the DID document.
> Firehose Identity event

- packages/pds/src/api/com/atproto/repo/applyWrites.ts
- packages/pds/src/api/com/atproto/repo/createRecord.ts
- packages/pds/src/api/com/atproto/repo/putRecord.ts
- packages/pds/src/repo/prepare.ts
- packages/pds/tests/crud.test.ts
Enables the creation/update of records of unknown lexicon.
By default, a write is still "validated" which requires the existence of the lexicon. However, if the request to the pds is set to `validated: false`, then the write will be let through. This is higher friction than we want it to be long term, however we don't have any form of dynamic schema resolution yet and I think the extra bit of friction is worth it such that the lack of guardrails is better surfaced to developers.
We generically walk the record to find and associate any blobrefs, even for records that we do not know the schema for. 
Some other generic behavior is enforced as well:
- rkey syntax
- record `$type` matching collection name
- `createdAt` adheres to the proper date format
- ensuring that blob-refs are not in the …
> Enable creation of unknown record types

- .changeset/lovely-dogs-run.md
- packages/api/src/bsky-agent.ts
- packages/api/tests/bsky-agent.test.ts
Missed a sanitization and the test didn't catch due to the order the calls were made. Sanitized, updated test: should only insert one entry for `hashtag`.
> Fix sanitization, improve test to catch

- lexicons/com/atproto/temp/fetchLabels.json
- packages/api/src/client/lexicons.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/lexicons.ts
The motivation with this is that the docs site hides deprecated endpoint, and the behavior was updated to only do this when "deprecation" is the first word of the description (to avoid hiding some endpoints which just talk about deprecation).
> lex: tweak deprecation note

- packages/ozone/src/mod-service/status.ts
- packages/ozone/tests/moderation-appeals.test.ts
Since we want appealed subjects to only show up on escalation queue, this PR sets the `reviewState` to `reviewEscalated`.
> :sparkles: Move appealed subject's review state to escalated

- .changeset/dull-hotels-beam.md
- .changeset/short-suits-destroy.md
- packages/api/src/rich-text/detection.ts
- packages/api/tests/rich-text-detection.test.ts
Closes #2243
Fixes the issue where #️⃣ is being parsed as an emoji because it starts with the same char code as regular hashtag, as the emoji is composed of 0x23 (#) 0xfe0f (variation selector) 0x20e3 (keycap)
Fixes length calculation as well
> Do not parse hashtag emoji as tag

- packages/ozone/src/api/label/subscribeLabels.ts
- packages/ozone/src/mod-service/util.ts
- packages/ozone/tests/query-labels.test.ts
Just a few little `subscribeLabels` fixes here:
- ensure we don't ask our dag-cbor library to serialize `undefined`.
- ensure the messages are tagged with `$type`.
- added a test to catch these kinds of issues.
> Fix misc issues with subscribeLabels stream output

- .changeset/rotten-actors-dance.md
- .changeset/sour-gorillas-unite.md
- packages/api/src/bsky-agent.ts
- packages/api/tests/bsky-agent.test.ts
`##hashtag` is a valid tag based on the parsing we shipped ~5 months ago. Today, [users noticed](https://bsky.app/profile/josiah.lol/post/3kmjejr4fux26) that muting `##` added a muted word to their prefs (`#`), great, but they then could not remove.
This is because `##` was being truncated down to `#` by this sanitization. Then, when trying to remove, it was further being truncated down to an empty string, hence no match, hence no removal.
So this PR fixes support for tags like `##hashtag` AND allows removal of existing muted words only containing `#` **by only sanitizing on insert.** On update/remove, we expect an exact match.
I re-split these CRUD actions out and updated some naming for clarity.
Update: because it was closely related, I added `#️⃣` and `##️⃣` handling as well.
> Fix muted word sanitization

- services/bsky/Dockerfile
Installing the `runit` package in the services/bsky Dockerfile in order to enable the use of `svlogd` for high performance logging rather than Docker daemon logging.
*Note:* This won't affect anyone that doesn't explicitly override the container's default command.
> Add runit to the services/bsky Dockerfile

- lexicons/com/atproto/admin/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/admin/defs.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/admin/defs.ts
- packages/dev-env/src/ozone.ts
- packages/ozone/src/api/admin/emitModerationEvent.ts
- packages/ozone/src/config/config.ts
- packages/ozone/src/config/env.ts
- packages/ozone/src/context.ts
- packages/ozone/src/daemon/context.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/com/atproto/admin/defs.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/src/mod-service/views.ts
- packages/ozone/tests/moderation-events.test.ts
- packages/pds/src/api/com/atproto/admin/sendEmail.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/admin/defs.ts
When an email event is sent to `emitModerationEvent` on ozone and the input includes `meta.content`, ozone attempts to prompt the user's pds to send an email.  Since `meta.content` is not typically included, this change is backwards compatible.  Pals with #2271.
> Ozone delegates email sending to actor's pds

- packages/bsky/src/api/blob-resolver.ts
- packages/bsky/src/config.ts
When configured, a rate limit bypass key can be included in blob resolution requests to specific hostnames.
> Appview: support rate limit bypass key for blob resolution

- .github/workflows/build-and-push-bsky-aws.yaml
- packages/bsky/src/auth-verifier.ts
- packages/bsky/tests/admin/admin-auth.test.ts
- packages/common-web/src/did-doc.ts
- packages/identity/src/did/atproto-data.ts
Give appview v1 understanding of service auth signed by `atproto_labeler`
> Appview v1 ozone auth

- .changeset/ten-tools-exercise.md
- lexicons/app/bsky/actor/defs.json
- packages/api/src/bsky-agent.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/defs.ts
- packages/api/tests/bsky-agent.test.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/actor/defs.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
It has been a pretty common complaint that the Following feed becomes unusable when someone you follow goes on a reply spree because we're showing every single reply by default. This changes so that *by default* (if you haven't expressed a preference), we're going to show a reply if you follow *both* people in the conversation.
People who *have* expressed a particular preference will keep it.
Create a new user or take an existing one who hasn’t changed this setting. Observe that their default preferences have the "Reply Filters" toggle on whereas previously they wouldn’t.
> Show only replies from people you follow in Following by default

- packages/dev-env/src/network.ts
- packages/ozone/src/config/config.ts
- packages/ozone/src/config/env.ts
- packages/ozone/src/context.ts
- packages/ozone/src/daemon/context.ts
- packages/ozone/src/daemon/event-pusher.ts
- packages/ozone/src/mod-service/index.ts
Allows ozone to be run in such a way that it doesn't actually push takedowns out to the configured appview.  Note that this is the new default functionality.  Also allows configuring ozone without a pds.
> Ozone: configure to fetch but not pull from appview

- packages/api/src/bsky-agent.ts
- packages/api/tests/moderation-prefs.test.ts
During this transition to new label names, some clients may not update immediately. This PR ensures basic backwards compat *for global label settings only* between old/new clients.
Old clients of course behave the same. Updated clients with this new SDK (once published) will double-write new labels to old labels in an effort to keep them in sync. So changes to new label settings will be reflected in the old clients.
If a user edits a setting in an older client (without the double-write), and subsequently loads their account in an updated client, this PR remaps old values to new values. This will result in the updated client showing the correct values in label settings. If the user then updates label settings in the updated, client, the double write will take effect, and the old setting …
> Handle sync legacy labels

- packages/bsky/src/api/com/atproto/admin/getAccountInfos.ts
This is a route for bulk resolving handles & profile records. We currently have it behind moderation auth, but instead we put it behind standard auth with a special moderation check for viewing takedowns (just like `getProfile`)
> Allow 3p labelers to query appview account infos

- packages/pds/src/api/com/atproto/identity/submitPlcOperation.ts
- packages/pds/tests/plc-operations.test.ts
Set of fixes for PLC op submission:
- check against entryway plc rotation key when running PDS in entryway mode
- emit an `#identity` event on firehose after submitting operation
- bust DID cache for requester after submitting operation
Closes https://github.com/bluesky-social/atproto/issues/2265
> Clean up PLC op submission

- packages/ozone/src/mod-service/index.ts
When overwriting an existing label, we weren't updating the cached sig
> Ozone update sig on label overwrite

- packages/pds/src/api/proxy.ts
Ensuring that the entryway respects atproto-proxy and atproto-accept-labeler headers.
> Pass proxy header along with auth passthrough

- packages/ozone/src/api/label/fetchLabels.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/src/mod-service/types.ts
- packages/ozone/src/mod-service/views.ts
- packages/ozone/tests/__snapshots__/get-record.test.ts.snap
- packages/ozone/tests/__snapshots__/get-repo.test.ts.snap
- packages/ozone/tests/moderation.test.ts
- packages/pds/tests/proxied/admin.test.ts
- remove current unspecced takedown labels
- emit `!takedown` labels for records & repos and `!suspend` labels for repos when applicable
- no longer push out record takedown events (as these are to be actioned with `!takedown` labels)
Note: pair this with a database migration that adjusts existing unspecced takedowns to specced takedown labels
> Add specced takedown labels

- .changeset/plenty-poets-reply.md
- packages/api/src/agent.ts
> Fix agent.clone() - copy the pdsUrl config

- lexicons/com/atproto/server/describeServer.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/server/describeServer.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/server/describeServer.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/com/atproto/server/describeServer.ts
- packages/pds/src/api/com/atproto/server/describeServer.ts
- packages/pds/src/config/config.ts
- packages/pds/src/config/env.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/server/describeServer.ts
- packages/pds/tests/account.test.ts
Allow PDS operators to configure their server with a public contact email address, e.g. for receiving abuse reports.
> PDS contact email address

- packages/ozone/src/mod-service/index.ts
- packages/ozone/src/mod-service/util.ts
Follow up to https://github.com/bluesky-social/atproto/pull/2310
Missed a spot + put in an extra failsafe directly before signing
> Second pass on no false negs in labels

- packages/bsky/src/data-plane/server/routes/labels.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/src/hydration/label.ts
- packages/bsky/src/hydration/util.ts
- packages/bsky/src/views/index.ts
- packages/bsky/tests/label-hydration.test.ts
We were seeing some duplicate labels come through, this should ensure they are deduped during the course of the appview's hydration steps.
> Dedupe labels during appview hydration

- packages/bsky/src/hydration/hydrator.ts
Just fixing a little issue here affecting the ability to lookup a labeler service record from the appview via `com.atproto.repo.getRecord`.
> Appview: fix lookup for labeler via repo.getRecord

- .changeset/quiet-papayas-accept.md
- packages/api/src/moderation/subjects/post.ts
The current `moderatePost()` function isnt checking quote posts for `#viewBlocked` responses, which is causing it to not correctly filter posts that quote blocked users. This PR fixes that.
> Fix: correctly detect blocked QPs when moderating posts

- lexicons/app/bsky/actor/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/defs.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts
- packages/bsky/src/views/index.ts
- packages/bsky/tests/views/__snapshots__/labeler-service.test.ts.snap
- packages/bsky/tests/views/labeler-service.test.ts
- packages/dev-env/package.json
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/actor/defs.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
- pnpm-lock.yaml
Adds the `associated` property to profile and profile-basic views, bringing them in line with profile-detailed views.  In practice only the `associated.labeler` property need be set on these views when the profile is for a labeler.  On profile-detailed views you may find additional info within `associated` related to feeds and lists.
> Appview: add associated.labeler info to all profile views

- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/tests/views/author-feed.test.ts
When viewing `getAuthorFeed` with the `posts_and_author_threads` filter, previously the appview would serve any reply that the author posted in their own thread in reply to one of their own posts.  This could end-up including posts that were not part of a self-thread, even if they appeared to be "locally" by inspecting their root and parent.
With this change, when we encounter a reply we ensure that the full reply chain up to the root is included in the author feed.  Otherwise we filter it out—this should ensure that only proper self-threads are served when using the `posts_and_author_threads` filter.
> Exclude posts from author feed when they don't fit into a self-thread

- lexicons/com/atproto/sync/getRecord.json
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/sync/getRecord.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/com/atproto/sync/getRecord.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/sync/getRecord.ts
This is a low-stakes description-only change.
TBH, we could and will probably just entirely delete this parameter, but loudly marking it as deprecated is an easy first step.
> lex: deprecate getRecord commit param

- lexicons/app/bsky/actor/defs.json
- lexicons/app/bsky/embed/external.json
- lexicons/app/bsky/embed/images.json
- lexicons/app/bsky/feed/defs.json
- lexicons/app/bsky/graph/defs.json
- lexicons/com/atproto/server/describeServer.json
- packages/api/src/client/lexicons.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/lexicons.ts
Mentioned in https://github.com/bluesky-social/atproto/issues/2111
This is technically a Lexicon evolution rules-breaking change, because it is adding a non-optional restriction on an existing field. This is part of final cleanup of existing Lexicons trying to hit all such final "breaking" changes.
In practice, I think this is basically a no-op as we aren't validating `uri` fields against any format or regex in the typescript implementation (I probably will require them to be URIs of some sort in the golang Lexicon validator).
Some of these changes appeared earlier in https://github.com/bluesky-social/atproto/pull/1994, which was mostly about string length limits, and we needed to revert. I'm trying to both be more complete here, and to break up these changes in to more focused chunks.
> lexicon nits: use string format `uri` in more places

- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/tests/views/author-feed.test.ts
- packages/dev-env/src/seed/author-feed.ts
In #2347 I introduced a bug, where reposted content was being excluded from author feeds under the `posts_and_author_threads` filter.  This fixes it!
> Fix inclusion for reposts on author feed w/ posts_and_author_threads

- lexicons/com/atproto/moderation/createReport.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/sync/getRecord.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/lexicons.ts
This has actually be limited on the *output* for a long time, apparently as a mistake/typo when locking down string length fields earlier.
Going with the existing length there (2000 graphemes). 1200 might also be good; a longer description could be a future additional field or out-of-band or something.
Includes codegen. Looks like codegen of a recent branch (of mine) didn't merge cleanly, or I had forgot to include in the PR.
> lex: limit createReport size

- .changeset/lovely-parrots-talk.md
- packages/xrpc-server/src/server.ts
- packages/xrpc-server/src/types.ts
Add an option to xrpc-server for configuring the catchall logic for unspecified xrpc endpoints.
> Configurable catchall on xrpc-server

- packages/bsky/src/views/index.ts
- packages/pds/src/read-after-write/viewer.ts
Ensure counts are set in all post and profile views, even when aggregations are missing.  Apply the same to read-after-write logic in the PDS, and tidy some `$type` typos found along the way.
> Always include counts on post and profile views

- packages/lexicon/src/types.ts
- packages/lexicon/src/validators/formats.ts
- packages/lexicon/src/validators/primitives.ts
Pretty simple? Doesn't seem like there is any support needed in `lex-cli`.
Will add the actual formats to lexicons in a separate PR.
See also specs PR: https://github.com/bluesky-social/atproto-website/pull/248
> lexicon: add support for TID and record-key string formats

- packages/bsky/src/views/index.ts
- packages/bsky/tests/views/__snapshots__/timeline.test.ts.snap
- packages/bsky/tests/views/blocks.test.ts
Feed item views served from the appview include a `post` and a `reply` field.  The `reply` field contains views for the post's reply root and reply parent.  Historically if the reply root/parent were missing or were blocked posts, we would simply omit the `reply` field entirely.  With this change we will start to include it, and use the `app.bsky.feed.defs#notFoundPost` or `app.bsky.feed.defs#blockedPost` if the root/parent are missing or blocked respectively.  This aligns the implementation with how the feed view lexicons were intended to be used.
> Use blocked and not-found unions in post reply refs

- lexicons/app/bsky/embed/record.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/embed/record.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/embed/record.ts
- packages/bsky/src/views/index.ts
- packages/bsky/tests/__snapshots__/feed-generation.test.ts.snap
- packages/bsky/tests/data-plane/__snapshots__/indexing.test.ts.snap
- packages/bsky/tests/views/__snapshots__/author-feed.test.ts.snap
- packages/bsky/tests/views/__snapshots__/block-lists.test.ts.snap
- packages/bsky/tests/views/__snapshots__/blocks.test.ts.snap
- packages/bsky/tests/views/__snapshots__/list-feed.test.ts.snap
- packages/bsky/tests/views/__snapshots__/posts.test.ts.snap
- packages/bsky/tests/views/__snapshots__/timeline.test.ts.snap
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/embed/record.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/embed/record.ts
- packages/pds/tests/proxied/__snapshots__/feedgen.test.ts.snap
- packages/pds/tests/proxied/__snapshots__/views.test.ts.snap
This adds the `likeCount`, `repostCount`, `replyCount` fields to the `#viewRecord` embed type.  We may continue to cater the `#viewRecord` lexicon to post embeds, bringing it more in line with list, feedgen, and labeler embed views.
> Appview: include like/repost/reply counts on post embed

- lexicons/app/bsky/actor/searchActors.json
- lexicons/app/bsky/actor/searchActorsTypeahead.json
- lexicons/app/bsky/feed/searchPosts.json
- lexicons/app/bsky/unspecced/searchActorsSkeleton.json
- lexicons/app/bsky/unspecced/searchPostsSkeleton.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/searchActorsTypeahead.ts
- packages/api/src/client/types/app/bsky/feed/searchPosts.ts
- packages/api/src/client/types/app/bsky/unspecced/searchActorsSkeleton.ts
- packages/api/src/client/types/app/bsky/unspecced/searchPostsSkeleton.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/actor/searchActorsTypeahead.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/searchPosts.ts
- packages/bsky/src/lexicon/types/app/bsky/unspecced/searchActorsSkeleton.ts
- packages/bsky/src/lexicon/types/app/bsky/unspecced/searchPostsSkeleton.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/actor/searchActorsTypeahead.ts
- packages/ozone/src/lexicon/types/app/bsky/feed/searchPosts.ts
- packages/ozone/src/lexicon/types/app/bsky/unspecced/searchActorsSkeleton.ts
- packages/ozone/src/lexicon/types/app/bsky/unspecced/searchPostsSkeleton.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/searchActorsTypeahead.ts
- packages/pds/src/lexicon/types/app/bsky/feed/searchPosts.ts
- packages/pds/src/lexicon/types/app/bsky/unspecced/searchActorsSkeleton.ts
- packages/pds/src/lexicon/types/app/bsky/unspecced/searchPostsSkeleton.ts
Let's get agreement on the params/lexicon structure, then might need to hand this off to dan/devin to implement the query param pass-through in the appview typescript code (or I can try to bite that off).
Lexicon style notes:
- using full tokens/refs for things like sort-order felt a bit heavy? on the other hand would feel more lexicon-idiomatic
- I didn't specify `default` even for fields which have a clear default. I don't think we've used default much? and i'm not sure if that would result in the query-param always getting set by client, or only interpreted on backend. I guess writing this now I would lean towards making the defaults explicit
- in theory, more of these params could be arrays instead of single string values. that would help things like bots and analysis tools, but could …
> lexicons: add more search parameters

- .changeset/tiny-hornets-vanish.md
- lexicons/app/bsky/actor/searchActorsTypeahead.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/searchActorsTypeahead.ts
- packages/bsky/src/api/app/bsky/actor/searchActors.ts
- packages/bsky/src/api/app/bsky/actor/searchActorsTypeahead.ts
- packages/bsky/src/api/app/bsky/feed/searchPosts.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/actor/searchActorsTypeahead.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/actor/searchActorsTypeahead.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/searchActorsTypeahead.ts
Three changes here in followup to #2396:
- removes the unreleased `viewer` parameter from `app.bsky.actor.searchActorsTypeahead`.
- passes through upcoming post search parameters to search service.
- passes through viewer context to search service.
> Appview: support new post search params, viewer context in search

- .changeset/afraid-starfishes-sneeze.md
- lexicons/com/atproto/server/createSession.json
- lexicons/com/atproto/server/getSession.json
- lexicons/com/atproto/server/updateEmail.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/server/createSession.ts
- packages/api/src/client/types/com/atproto/server/getSession.ts
- packages/api/src/client/types/com/atproto/server/updateEmail.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/server/createSession.ts
- packages/bsky/src/lexicon/types/com/atproto/server/getSession.ts
- packages/bsky/src/lexicon/types/com/atproto/server/updateEmail.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/com/atproto/server/createSession.ts
- packages/ozone/src/lexicon/types/com/atproto/server/getSession.ts
- packages/ozone/src/lexicon/types/com/atproto/server/updateEmail.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/server/createSession.ts
- packages/pds/src/lexicon/types/com/atproto/server/getSession.ts
- packages/pds/src/lexicon/types/com/atproto/server/updateEmail.ts
This contains lexicons for supporting an email auth factor within the current authentication system.  The PDS will eventually support other factors as a more long-term solution via OAuth (see #1958 #2408).  These lexicons will be used as a stand-in for now, at minimum for use with the entryway service (bsky.social) which will support them.
> Lexicons: email auth factor

- packages/bsky/src/hydration/hydrator.ts
Service refs (e.g. `did:plc:example#service_id`) were getting preserved into the hydration and dataplane layer, where we really just want to work with the relevant DIDs (e.g. `did:plc:example`).
> Appview: ensure hydration context tracks viewer did and not full service ref

- packages/bsky/src/api/app/bsky/actor/getSuggestions.ts
This ensures that when a service is used to provide suggestions on `actor.getSuggestions`, language information associated with the request is preserved.
> Appview: maintain language info when going out to a suggestions service

- packages/aws/src/s3.ts
- packages/pds/src/api/com/atproto/repo/uploadBlob.ts
- packages/pds/src/config/config.ts
- packages/pds/src/config/env.ts
- packages/pds/src/context.ts
This makes upload timeouts to S3 handled a bit more consistently, and surfaces them to the user in a more legible way.
- Support a config on `S3BlobStore` for upload timeouts.
- Apply  `S3BlobStore` timeouts to  both `putTemp()` and `putPermanent()`.
- Clear upload timeouts more reliably (e.g. in cases where upload fails for some reason other that the timeout).
- Add PDS config `PDS_BLOBSTORE_S3_UPLOAD_TIMEOUT_MS`, defaulting to `20000`.  The previous timeout was 10sec which was too short in enough cases that it was worth increasing to 20sec.
- Surface better error to user when `repo.uploadBlob` endpoint fails due to a timeout.
> PDS: handle S3 upload timeout more gracefully

- packages/bsky/src/api/app/bsky/feed/getFeed.ts
- packages/bsky/src/api/app/bsky/feed/getListFeed.ts
- packages/bsky/src/api/app/bsky/feed/getTimeline.ts
- packages/bsky/src/views/index.ts
- packages/bsky/tests/views/blocks.test.ts
Remove any replies appearing in a feed or timeline that are in response to a blocked post.  Before we would serve the reply and signal that the parent is blocked using a `#blockedPost`, which remains the behavior on author feeds.
> Appview: remove replies to blocked posts from feeds

- .changeset/five-planes-know.md
- lexicons/app/bsky/actor/defs.json
- packages/api/src/bsky-agent.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/defs.ts
- packages/api/src/types.ts
- packages/api/src/util.ts
- packages/api/tests/bsky-agent.test.ts
- packages/api/tests/moderation-prefs.test.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/actor/defs.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
I explored a different approach in #2411, but after implementing in the app, we decided that introducing a new UX pattern (primary algo) wasn't the right move.
So we fell back on the original plan: a movable following feed. This PR does that.
To do so, we needed some new preference that would be unset on the first read only, so that we could migrate the following feed into the user's saved feeds array. I could have done this using something as simple as `isFeedsMigrated` or `timelineIndex` (from previous work here), but I decided to do a full v2 revision for a few reasons:
- the following feed isn't an `AtUri`, and v1 prefs enforced that formatting
- I wanted to treat the following feed as much like any other feed as possible e.g. not manually inject it on the client side, or have to …
> Add `savedFeedsPrefV2` and new methods

- packages/lexicon/src/validators/complex.ts
Creating a thousand error objects (as observed [in this post](https://bsky.app/profile/bencollins.bsky.social/post/3kr2kcufdxf2t)) is not good. Let's not do that.
The costs are shown with 6x throttling but can be higher on lower-end Android.
> Add fast path for validating non-required undefined fields

- lexicons/tools/ozone/moderation/emitEvent.json
This PR fixes duplicate ref in the Lexicon of "tools.ozone.moderation.emitEvent".
> Resolve duplicate refs in lexicon of ozone

- packages/bsky/src/auth-verifier.ts
- packages/bsky/src/config.ts
- packages/bsky/src/index.ts
- packages/dev-env/src/bsky.ts
This will allow trusted supporting services to make service requests to the appview on behalf of users.  I expect in the future we'll have a more explicit form of delegation/attenuation which would support the same use case.
> Appview: support alternate audiences on standard auth

- packages/xrpc-server/package.json
- pnpm-lock.yaml
`ResponseTypeNames`, `ResponseTypeStrings` and `ResponseType` are used as runtime values. Because of this, `@atproto/xrpc` is a production dependency of `@atproto/xrpc-server`.
https://github.com/bluesky-social/atproto/blob/16208b7b92c925ad5d6d295d2ef60564beb31886/packages/xrpc-server/src/types.ts#L189
https://github.com/bluesky-social/atproto/blob/16208b7b92c925ad5d6d295d2ef60564beb31886/packages/xrpc-server/src/types.ts#L196
https://github.com/bluesky-social/atproto/blob/16208b7b92c925ad5d6d295d2ef60564beb31886/packages/xrpc-server/src/types.ts#L200
> fix(xrpc-server): add missing runtime dependency

- lexicons/app/bsky/feed/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/defs.ts
- packages/api/src/client/types/tools/ozone/moderation/emitEvent.ts
- packages/bsky/src/api/app/bsky/feed/getFeed.ts
- packages/bsky/src/api/app/bsky/feed/getListFeed.ts
- packages/bsky/src/api/app/bsky/feed/getTimeline.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/defs.ts
- packages/bsky/src/views/index.ts
- packages/bsky/tests/data-plane/__snapshots__/indexing.test.ts.snap
- packages/bsky/tests/views/__snapshots__/author-feed.test.ts.snap
- packages/bsky/tests/views/__snapshots__/blocks.test.ts.snap
- packages/bsky/tests/views/__snapshots__/list-feed.test.ts.snap
- packages/bsky/tests/views/__snapshots__/timeline.test.ts.snap
- packages/bsky/tests/views/author-feed.test.ts
- packages/bsky/tests/views/blocks.test.ts
- packages/bsky/tests/views/list-feed.test.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/feed/defs.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/emitEvent.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/defs.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/emitEvent.ts
- packages/pds/tests/proxied/__snapshots__/views.test.ts.snap
Two changes here:
- introduces a new field on feed items `item.reply.grandparentAuthor` which contains a basic profile for the grandparent (i.e. parent's parent) reply of a post.
- ensures that in feed settings (e.g. timeline), posts whose reply grandparent author is blocked do not appear.  This essentially applies the block rule to `item.reply.parent` that #2430 applied to `item.post`, if that makes sense.
Replaces #2229.
> Appview: add grandparent author to reply ref, ensure no replies to blocked grandparent in feeds

- .changeset/clever-trainers-own.md
- packages/api/src/moderation/decision.ts
- packages/api/tests/moderation-behaviors.test.ts
Fixes: https://github.com/bluesky-social/social-app/issues/3871
This is one part of adjusting the difficulty in seeing whether your post is actually labeled or not whenever you apply a self label to the post. Take this scenario:
- You post an image and add the self-label `nudity`
- The post gets upgraded to the `porn` label immediately. To the user, this Bluesky upgraded label appears to be _their_ self label
- If the user realizes that the label was upgraded, they appeal the upgrade
- Bluesky moderation accepts the appeal, and downgrades it back to `nudity`
- To the poster, the UI makes it look like _all_ labels were removed from their post, even though they were not.
Another, simpler scenario where this is problematic:
- You post an image and add the self-label `nudity`
- Your …
> api: Always apply self labels even if post is your own, downgrade `hide` moderation preference to `blur` when the post is your own

- packages/bsky/proto/bsky.proto
- packages/bsky/src/api/app/bsky/feed/getLikes.ts
- packages/bsky/src/data-plane/server/indexing/index.ts
- packages/bsky/src/data-plane/server/indexing/plugins/chat-declaration.ts
- packages/bsky/src/data-plane/server/routes/follows.ts
- packages/bsky/src/data-plane/server/routes/labels.ts
- packages/bsky/src/data-plane/server/routes/likes.ts
- packages/bsky/src/data-plane/server/routes/profile.ts
- packages/bsky/src/data-plane/server/routes/records.ts
- packages/bsky/src/hydration/actor.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/src/proto/bsky_connect.ts
- packages/bsky/src/proto/bsky_pb.ts
- packages/bsky/src/views/index.ts
- packages/bsky/tests/__snapshots__/feed-generation.test.ts.snap
- packages/bsky/tests/data-plane/__snapshots__/indexing.test.ts.snap
- packages/bsky/tests/views/__snapshots__/author-feed.test.ts.snap
- packages/bsky/tests/views/__snapshots__/block-lists.test.ts.snap
- packages/bsky/tests/views/__snapshots__/blocks.test.ts.snap
- packages/bsky/tests/views/__snapshots__/likes.test.ts.snap
- packages/bsky/tests/views/__snapshots__/list-feed.test.ts.snap
- packages/bsky/tests/views/__snapshots__/mute-lists.test.ts.snap
- packages/bsky/tests/views/__snapshots__/notifications.test.ts.snap
- packages/bsky/tests/views/__snapshots__/posts.test.ts.snap
- packages/bsky/tests/views/__snapshots__/profile.test.ts.snap
- packages/bsky/tests/views/__snapshots__/reposts.test.ts.snap
- packages/bsky/tests/views/__snapshots__/timeline.test.ts.snap
- packages/dev-env/src/seed/users.ts
Updating the appview dataplane protobufs with support for chat details and time-sorted likers.
- Add `profile.associated.chat.allowIncoming` to profile views.
- Update `getLikes` to be ordered reverse-chronologically.
> Appview: add chat details to profile views, chronological likes

- packages/bsky/src/api/app/bsky/feed/getLikes.ts
- packages/bsky/src/data-plane/server/routes/likes.ts
Followup to #2471, more useful error message when using an out of date cursor with `getLikes`.
> Appview: handle out-of-date cursor with feed.getLikes

- packages/xrpc-server/src/server.ts
- packages/xrpc-server/tests/rate-limiter.test.ts
Two fixes:
- better error handling. Specifically the limit consume fn _returns_ an error rather than throwing so we need to handle that correctly
- fix the scope on the consume function
> Bugfixes for generic proxy rate limiting

- packages/ozone/src/api/util.ts
This was causing the `queryEvents` endpoint to fail at times.
> :bug: Add divert event to the list of event types

- packages/dev-infra/_common.sh
We refactored dev-infra in https://github.com/bluesky-social/atproto/pull/1825 to allow running tests against a local Postgres without docker. Part of that work was to make the script exit if any command fails.
However, when running with docker, we actually don't want the script to exit if the test command fails. We want to intercept the error code and tear down docker before exiting. We can do this by just adding a `set +e` right before calling the supplied command
> Tear down docker when tests fail

- packages/pds/src/actor-store/blob/reader.ts
- packages/pds/src/api/com/atproto/repo/putRecord.ts
- packages/pds/tests/crud.test.ts
This is a relatively crude/ham-fisted fix intended to help with the fact that some accounts still have legacy blob refs in their profile records which is preventing them from updating their profile record.
Ended up landing this in `putRecord` instead of the `prepareWrite` functions because we need access to the actor store to find the `size` of the blob. We only implement it in `putRecord` when updating specifically a profile record in order to both reduce the number of checks we're required to do, but also because this issue is mostly isolated to historical profile records.
This is a stopgap until we have time to run a proper migration that updates all legacy blob refs.
> Update legacy blob refs in profile records

- packages/pds/src/index.ts
- packages/pds/tests/server.test.ts
Simple fix that bumps json size limit on pds from 100kb -> 150kb
In the future we should:
- make size limits configurable generally (like blobs)
- make size limits configurable by route
> Bump json size limit on pds

- .changeset/heavy-pears-sip.md
- lexicons/chat/bsky/convo/defs.json
- lexicons/chat/bsky/convo/sendMessage.json
- lexicons/chat/bsky/convo/sendMessageBatch.json
- lexicons/chat/bsky/moderation/getMessageContext.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/chat/bsky/convo/defs.ts
- packages/api/src/client/types/chat/bsky/convo/sendMessage.ts
- packages/api/src/client/types/chat/bsky/convo/sendMessageBatch.ts
- packages/api/src/client/types/chat/bsky/moderation/getMessageContext.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/chat/bsky/convo/defs.ts
- packages/bsky/src/lexicon/types/chat/bsky/convo/sendMessage.ts
- packages/bsky/src/lexicon/types/chat/bsky/convo/sendMessageBatch.ts
- packages/bsky/src/lexicon/types/chat/bsky/moderation/getMessageContext.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/chat/bsky/convo/defs.ts
- packages/ozone/src/lexicon/types/chat/bsky/convo/sendMessage.ts
- packages/ozone/src/lexicon/types/chat/bsky/convo/sendMessageBatch.ts
- packages/ozone/src/lexicon/types/chat/bsky/moderation/getMessageContext.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/src/mod-service/subject.ts
- packages/ozone/tests/__snapshots__/moderation.test.ts.snap
- packages/ozone/tests/moderation.test.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/chat/bsky/convo/defs.ts
- packages/pds/src/lexicon/types/chat/bsky/convo/sendMessage.ts
- packages/pds/src/lexicon/types/chat/bsky/convo/sendMessageBatch.ts
- packages/pds/src/lexicon/types/chat/bsky/moderation/getMessageContext.ts
A few small `chat.bsky` lexicon tweaks in here:
- Add temporarily optional `convoId` to `getMessageContext`.  Looking to be consistent about always qualifying `messageId` within a given `convoId`.
- Rename `#message` to `#messageInput` and remove its optional `id` field.
- Add a limit to the number of messages in `sendMessageBatch`.
- Add required `convoId` to `#messageRef` used by ozone, make requisite ozone changes.
> Lexicon: misc fixes to chat lexicons

- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
- packages/bsky/src/views/index.ts
- packages/bsky/tests/views/__snapshots__/thread.test.ts.snap
- packages/bsky/tests/views/thread.test.ts
Two changes here to`app.bsky.feed.getPostThread` in the appview:
- support handles in the `uri` parameter (no longer just DIDs), e.g. `at://handle.bsky.social/app.bsky.feed.post/22222222222`.
- Do not serve `#notFoundPost` placeholders in thread replies.  There were appearing from posts by takendown/suspended accounts.
> Appview: support handles in post threads, remove deleted reply placeholders

- packages/bsky/src/api/app/bsky/graph/getLists.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/dev-env/src/mock/index.ts
- packages/ozone/src/api/proxied.ts
- packages/ozone/tests/get-lists.test.ts
This PR allows ozone to proxy `api.app.bsky.graph.getLists` request to appview.
Additionally, it also seeds a couple of lists in the dev-env mock data.
> :sparkles: Add getLists endpoint to proxied routes via ozone

- packages/ozone/src/mod-service/subject.ts
- packages/ozone/src/mod-service/views.ts
- packages/ozone/tests/__snapshots__/moderation.test.ts.snap
- packages/ozone/tests/moderation.test.ts
The app currently does not send `convoId` with reported chat messages, as is required by the `#messageRef` lexicon, likely an artifact of the old version of the chat lexicons.  This introduces a workaround so that the field is temporarily optional, which we'll use until the vast majority of clients start sending `convoId`.  Also added a defensive try/catch around ozone's call to the appview for labels, so that we would not deny service if labels are unavailable for any reason.
> Ozone: temporary workaround for message refs on createReport

- .changeset/twelve-monkeys-switch.md
- packages/bsky/src/index.ts
- packages/ozone/src/index.ts
- packages/pds/src/index.ts
This sets the CORS max-age header to the maximum practical value on pds, ozone, and bsky.  Should significantly reduce the number of preflights web users encounter.  Kudos to @matthieusieben for calling this out.
> Set CORS max-age header

- .changeset/big-birds-drum.md
- lexicons/chat/bsky/convo/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/chat/bsky/convo/defs.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/chat/bsky/convo/defs.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/chat/bsky/convo/defs.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/chat/bsky/convo/defs.ts
Minor lexicon update to reflect that embeds on chat messages may be record embed views (specifically for post records).
> Lexicon: support for post embeds on chat messages

- packages/dev-env/src/network.ts
- packages/ozone/tests/lang.test.ts
Found a couple small issues that are probably contributing to test flakiness:
- `network.processAll()` should ensure to process ozone before appview in order for hosting status changes to propagate.
- minor issue with two tests using same backing pg schema.
> Fix flaky tests surrounding ozone/pds

- packages/pds/src/actor-store/preference/reader.ts
- packages/pds/src/actor-store/preference/transactor.ts
- packages/pds/src/actor-store/preference/util.ts
- packages/pds/src/api/app/bsky/actor/getPreferences.ts
- packages/pds/src/api/app/bsky/actor/putPreferences.ts
- packages/pds/tests/preferences.test.ts
We don't let app passwords read `personalDetailsPref`. This prevents app passwords from writing or deleting the preferences as well
Closes https://github.com/bluesky-social/atproto/issues/2555
> Scope put prefs by AuthScope

- .changeset/good-taxis-move.md
- packages/api/src/agent.ts
Removes the enforcement of a labeler limit in the client SDK so that it's easier to tune this behavior in the future.
There are still limits which may be enforced on the server. I believe we're bumping it to 25.
> Remove SDK enforcement of max labelers (NOTE: still enforced server side)

- .changeset/strange-camels-float.md
- lexicons/app/bsky/actor/defs.json
- packages/api/package.json
- packages/api/src/bsky-agent.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/defs.ts
- packages/api/src/types.ts
- packages/api/tests/bsky-agent.test.ts
- packages/api/tests/moderation-prefs.test.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/actor/defs.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
- pnpm-lock.yaml
- Adds `#bskyAppStatePref` preference
- Adds `bskyAppQueueNudges(nudges: string|string[])`
- Adds `bskyAppDismissNudges(nudges: string|string[])`
- Adds `bskyAppSetActiveProgressGuide(guide: {guide: string, ...})`
- Wraps `updatePreferences` in a lock region to avoid transaction clobbering in the future
To be used by the bsky app to track nudges that the user can dismiss (things like "Introducing DMs!") and to run progress guides. Not meant to be used by other clients, so explicitly namespaced with `bksyApp` within the API.
> Add new preference and api for bsky app state; also put preference updates within transactional lock regions

- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/src/hydration/util.ts
- packages/bsky/src/views/index.ts
- packages/bsky/tests/hydration/util.test.ts
- packages/bsky/tests/seed/known-followers.ts
- packages/bsky/tests/views/blocks.test.ts
- packages/bsky/tests/views/known-followers.test.ts
- packages/bsky/tests/views/profile.test.ts
This PR ensures that if I follow Daniel, and Daniel follows Devin, but Devin blocks Daniel, when I view Devin's profile I do not see Daniel as part of `knownFollowers`.
I also extracted some utils and added a few tests + added a new seed specifically for `knownFollowers` testing to handle these 2nd-party blocks more clearly/easily.
> Social proof blocks

- packages/bsky/src/api/app/bsky/feed/getLikes.ts
- packages/bsky/src/api/app/bsky/feed/getRepostedBy.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/dev-env/src/seed/basic.ts
- packages/ozone/src/api/proxied.ts
This helps mod view the likers and reposters of posts from within ozone. Especially helpful for takendown content.
> ✨ Add ozone proxy for getLikes and getRepostedBy

- lexicons/tools/ozone/moderation/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/tools/ozone/moderation/defs.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/defs.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/defs.ts
A bit unfortunate that these need to be manually edited.
Might also be good to consistently sort the union lists so it is visually easier to notice differences; didn't want to bite off a larger codegen in this PR though.
> lexicons: add missing ozone Tag event type to unions

- packages/bsky/src/api/app/bsky/graph/getLists.ts
- packages/bsky/tests/views/__snapshots__/lists.test.ts.snap
- packages/bsky/tests/views/lists.test.ts
These lists are not used for anything other than little tools for starter packs. They shouldn't show up in responses for `getLists`. Our client is already filtering them out, but this will ensure other clients don't need to implement that logic themselves.
> Filter out reference lists from `getLists`

- .changeset/six-teachers-tie.md
- packages/api/src/moderation/mutewords.ts
- packages/api/tests/moderation-mutewords.test.ts
The `hasMutedWord` function used in moderation uses the value of the tag in the facets passed as an argument as `tags` for judging. The current implementation was to “add the 0th of the features to the `tags` if a feature corresponding to `isTag` is found”.
This is incorrect, `features` is an array that can contain multiple elements, and those of type `#tag` can be included after the first. The 0th element can be hidden by a tag that is not the target word of the mute, or it can be a completely unrelated type.
Actually, it is possible to create such a post (e.g. https://bsky.app/profile/sugyan.pds.shigepon.net/post/3kukmykhshk2l), and an error will occur if a user with `mutedWords` set tries to view it.
Fixed it so all `#tag` types in `features` are subject to the decision, and added a …
> fix(api): `hasMutedWord` for facets with multiple features

- packages/bsky/src/feature-gates.ts
We were getting errors like `Cannot read properties of undefined (reading 'initialize')`. I was able to repro this locally using `localMode` settings. When using the default export, the error went away.
> Use default Statsig export

- .changeset/hot-cycles-punch.md
- lexicons/app/bsky/feed/detach.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/detach.ts
- packages/bsky/proto/bsky.proto
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/detach.ts
- packages/bsky/src/proto/bsky_connect.ts
- packages/bsky/src/proto/bsky_pb.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/feed/detach.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/detach.ts
Adds a `app.bsky.feed.detach` lexicon and codegens. `targets` limit set to 1k for now.
> [Detach] Lexicons

- packages/bsky/package.json
- packages/pds/package.json
Small thing that bothers me every time I need to do this, would be nice for the `updateSnapshot` script to run with the test env, unless there's a reason for us not to.
> Run test env with `updateSnapshot`

- packages/oauth/oauth-client-browser/README.md
Just some nits while I was reading through the docs. Solid documentation for getting set up though!!
> Tweak some wording in `oauth-client-browser` readme

- packages/api/OAUTH.md
- packages/oauth/oauth-client-browser/README.md
- packages/oauth/oauth-client-node/README.md
- make docs more "atproto" oriented, less "Bluesky API" specific
- clarification that `client_name` *does* get shown in approval flow (even if URI and logo don't)
- some capitalization and wording
- re-word privacy warning
- "SPA" not "PWA"
> OAuth docs tweaks

- Makefile
Noticed logging wasn't actually working.
Another suggestion: add `| tee logs.txt` so they're easier to browse. Idk about y'all but my tmux setup only persists like 2k lines lol.
> Fix run-dev-env-logged command

- .changeset/curvy-jeans-dream.md
- packages/pds/src/auth-verifier.ts
Inspect bearer tokens to check if they are access tokens or service auth tokens so that we can report the correct error.
We use the presence of the `lxm` claim to determine if they are service auth tokens.
> PDS - inspect bearer tokens

- lexicons/app/bsky/feed/postgate.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/postgate.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/postgate.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/feed/postgate.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/postgate.ts
Adds `quotePostRules[]` array to the `postgate` record. It re-uses the rulesets and naming conventions from `threadgate`. Absence of the `quotePostRules` array denotes the default state where everyone is allowed QP the post.
It also adds an additional rule called `disableRule` so that the disabled state is explicit, as opposed to inferred via an empty `allow` array on `threadgate` records. This makes it easier to maintain this record, now that they contain multiple properties managed separately.
> Add quote gate props to postgate

- .changeset/purple-fishes-search.md
- packages/api/src/index.ts
This gives us proper support for extending `AtpAgent`, as described in the changelog for v0.13.0.
> Export `AtpAgentOptions` type from @atproto/api

- .changeset/giant-starfishes-fry.md
- .changeset/happy-eggs-swim.md
- packages/pds/src/auth-verifier.ts
- packages/pds/src/pipethrough.ts
- packages/xrpc-server/src/types.ts
In order to work with DPoP, the `AuthVerifier` class needs to be able to set response headers ([here](https://github.com/bluesky-social/atproto/blob/6da2fa0fa76fefed959fad02859da9c0453e1781/packages/pds/src/auth-verifier.ts#L468-L474) and [here](https://github.com/bluesky-social/atproto/blob/6da2fa0fa76fefed959fad02859da9c0453e1781/packages/pds/src/auth-verifier.ts#L501-L506)).
The current catch all handler does not provide the response object to the verifier context, preventing it from setting the headers.
This PRs ensures that the `AuthVerifier`'s `accessStandard` authentication strategy indeed receives the `res` object.
> Ensure presence of DPoP related response headers

- .changeset/hot-cows-scream.md
- packages/oauth/oauth-client/src/util.ts
Node < 20 requires a runtime flag to make `CustomEvent` globally available (`--experimental-global-customevent`).
This change uses a local implementation of `CustomEvent` if a global one is not available.
The choice was made to use a local ponyfill instead of a polyfill in `oauth-client-node` for the following reasons:
- Defining a global variable can have side effects
- The ponyfill might be useful in other environments that do not have a `CustomEvent` implementation globally available.
- The footprint on the minified output is only a few bytes
> Provide a ponyfill for CustomEvent

- lexicons/app/bsky/feed/getActorLikes.json
You can only view your own likes and this fixes the documentation to note that auth is required and that the actor must be the requesting account
https://github.com/bluesky-social/atproto/pull/1440#issuecomment-1700193127
It looks like `getActorLikes` got marked as "Does not require auth" when it does require auth.
> Fix getActorLikes documentation to reflect auth required

- .changeset/wild-beans-dress.md
- .github/workflows/build-and-push-pds-ghcr.yaml
- packages/pds/src/api/com/atproto/server/activateAccount.ts
- packages/pds/src/api/com/atproto/server/deleteSession.ts
These bad calls from PDS to entryway were failing within xrpc, which was catching that we were setting a content-type but not sending a body.
> Fix calls from pds containing content-type but no body

- .changeset/cool-moose-argue.md
- .changeset/eight-poems-pump.md
- .changeset/hungry-queens-walk.md
- .changeset/modern-pears-camp.md
- packages/oauth/oauth-client/src/oauth-server-agent.ts
- packages/oauth/oauth-client/src/validate-client-metadata.ts
- packages/oauth/oauth-provider/src/client/client-manager.ts
- packages/oauth/oauth-provider/src/client/client.ts
- packages/oauth/oauth-provider/src/metadata/build-metadata.ts
- packages/oauth/oauth-provider/src/oauth-provider.ts
- packages/oauth/oauth-types/src/constants.ts
- packages/oauth/oauth-types/src/oauth-authorization-server-metadata.ts
- packages/oauth/oauth-types/src/oauth-client-metadata.ts
- packages/oauth/oauth-types/src/oauth-endpoint-name.ts
The use of `<name>_endpoint_auth_method` was inspired by https://github.com/panva/node-oidc-provider. This is however non-standard behavior that was removed in `node-oidc-provider`.
This PR removes that code from our oauth implementation
> Remove non-standard *_endpoint_auth_method

- .changeset/plenty-turtles-shop.md
- lexicons/app/bsky/feed/getPostThread.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/getPostThread.ts
- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/getPostThread.ts
- packages/bsky/tests/views/threadgating.test.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/feed/getPostThread.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/getPostThread.ts
Adds `threadgate: ThreadgateView` on the response from `getPostThread`.
The reason for this is: we need the threadgate record on thread views in the client in order to sort replies. We can't reliably get this from the root `PostView` bc that post could have been deleted, or detached via a block. We may also not have it due to the default `height` of 80 posts.
However, when constructing a feed response, we always load the threadgate, and we have a reference to the root post of the thread on the `ReplyRef`. So this PR checks if there's a threadgate hydrated for this root post, and returns it if so.
> Return `ThreadgateView` on response from `getPostThread`

- packages/bsky/src/api/app/bsky/feed/getQuotes.ts
- packages/bsky/tests/views/quotes.test.ts
- packages/dev-env/src/seed/quotes.ts
Follow up to quote listing. We don't want to show quotes that are made by people the original author has blocked (i.e., where the quoted post would show up as a blocked view in the post).
> filter posts with an embed block

- packages/bsky/src/api/app/bsky/feed/getPostThread.ts
The issue here was that `params.uri` is the "unresolved" thread anchor URI, which may contain a handle as the authority.  By switching to `skeleton.anchor` we use the fully resolved URI instead.
> Appview: fix uri used to place threadgate in getPostThread response

- .changeset/quiet-rice-design.md
- packages/oauth/oauth-provider/src/assets/app/components/url-viewer.tsx
Fixes a client-side issue when attempting to display the client id during the authorize flow.
> OAuth: fix client-side crash on authorize page

- lexicons/com/atproto/repo/applyWrites.json
- lexicons/com/atproto/repo/createRecord.json
- lexicons/com/atproto/repo/putRecord.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/repo/applyWrites.ts
- packages/api/src/client/types/com/atproto/repo/createRecord.ts
- packages/api/src/client/types/com/atproto/repo/putRecord.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/repo/applyWrites.ts
- packages/bsky/src/lexicon/types/com/atproto/repo/createRecord.ts
- packages/bsky/src/lexicon/types/com/atproto/repo/putRecord.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/com/atproto/repo/applyWrites.ts
- packages/ozone/src/lexicon/types/com/atproto/repo/createRecord.ts
- packages/ozone/src/lexicon/types/com/atproto/repo/putRecord.ts
- packages/pds/src/api/com/atproto/repo/applyWrites.ts
- packages/pds/src/api/com/atproto/repo/createRecord.ts
- packages/pds/src/api/com/atproto/repo/putRecord.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/repo/applyWrites.ts
- packages/pds/src/lexicon/types/com/atproto/repo/createRecord.ts
- packages/pds/src/lexicon/types/com/atproto/repo/putRecord.ts
- packages/pds/src/repo/prepare.ts
- packages/pds/src/repo/types.ts
- packages/pds/tests/crud.test.ts
To date when using `com.atproto.repo.{createRecord,putRecord,applyWrites}` to write to a repository, by the default the PDS will reject any writes into a collection with a Lexicon unknown to the PDS.  This behavior is controlled by the `validate` input.  We would like to change this behavior in order to be forward looking into a world where a PDS may have a dynamic set of Lexicons that are either resolved on the fly or otherwise loaded at runtime.
Record validation by the PDS is a driver of coherent/compatible data across the network, but network participants can't rely on all data in the network adhering to a given Lexicon: ultimately each party (e.g. an appview, feed generator, or client app) needs to validate repo records themselves.  So while validation within the PDS is very useful …
> Revise repo write validation for unknown Lexicons

- packages/ozone/src/mod-service/index.ts
Since the appealed param is sent via GET request, expecting it to be null is not reliable so this fix expects it to be either boolean or undefined. This allows the callers to either see only appeals or no appeals or make the response indifferent of appealed status.
> :bug: Fix appealed param's usage

- packages/bsky/src/data-plane/client.ts
In the appview we properly retry requests when the dataplane is partially offline, but have been failing to retry in-flight requests that have been aborted.
> Appview: retry dataplane requests on abort

- packages/pds/src/actor-store/repo/sql-repo-reader.ts
Somewhat hacky solution to add a `wait` in `getCarStream` for `sync.getRepo`. Current hypothesis is that we're not correctly applying back pressure to the stream and we're filling up our outgoing buffers
> Slow down get repos

- lexicons/tools/ozone/moderation/defs.json
- lexicons/tools/ozone/moderation/queryStatuses.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/tools/ozone/moderation/defs.ts
- packages/api/src/client/types/tools/ozone/moderation/queryStatuses.ts
- packages/dev-env/src/moderator-client.ts
- packages/ozone/src/api/moderation/emitEvent.ts
- packages/ozone/src/api/moderation/queryStatuses.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/defs.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/queryStatuses.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/src/mod-service/views.ts
- packages/ozone/tests/ack-all-subjects-of-account.test.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/defs.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/queryStatuses.ts
This PR adds a `acknowledgeAllSubjectsOfAccount` flag to takedown event which allows moderators to acknowledge all subjects in reviewOpen/reviewEscalated/Appealed state from the account being takendown.
This helps clean up moderation queue of unnecessary subjects that won't require individual reviews if the author's account is already taken down permanently.
An additional but unrelated feature in this PR is a `forAccount` param in `tools.ozone.moderation.queryStatuses` which allows moderators to view all subject statuses for a specific account.
> :sparkles: Optionally ack all open subjects from the author with takedown event

- lexicons/app/bsky/graph/getSuggestedFollowsByActor.json
- lexicons/app/bsky/unspecced/getSuggestionsSkeleton.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/graph/getSuggestedFollowsByActor.ts
- packages/api/src/client/types/app/bsky/unspecced/getSuggestionsSkeleton.ts
- packages/bsky/src/api/app/bsky/graph/getSuggestedFollowsByActor.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/graph/getSuggestedFollowsByActor.ts
- packages/bsky/src/lexicon/types/app/bsky/unspecced/getSuggestionsSkeleton.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/graph/getSuggestedFollowsByActor.ts
- packages/ozone/src/lexicon/types/app/bsky/unspecced/getSuggestionsSkeleton.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/graph/getSuggestedFollowsByActor.ts
- packages/pds/src/lexicon/types/app/bsky/unspecced/getSuggestionsSkeleton.ts
We want to know on the client if the results from this endpoint are actually specific to the actor we passed in as `relativeToDid` or not. This endpoint is used on Profile screens and nowhere else.
> Add `isFallback` to `getSuggestedFollowsByActor` method

- packages/oauth/oauth-provider/src/assets/app/components/sign-in-form.tsx
Fixes https://github.com/bluesky-social/social-app/issues/5448
The email OTP code we send is in lowercase for some reason - I'll try and fix that as well, but in social-app it tries some basic corrections on the code in case someone types it by hand. This PR uses the same function that social-app uses, which uppercases it and adds the dash in the middle if it's not present.
> [!NOTE]
> social-app uses the regex `/^[A-Z2-7]{5}-[A-Z2-7]{5}$/`, whereas I found oauth was using the slightly more lax `/^[A-Z0-9]{5}-[A-Z0-9]{5}$/`. I replaced it with social-app's one, I hope that's ok?
> Align OAuth 2FA code handling with social-app

- .changeset/purple-days-repeat.md
- packages/lexicon/src/validators/primitives.ts
- packages/lexicon/tests/general.test.ts
Not a huge deal but since we visit this codepath for every single validated string, seems like we'd want to avoid any unnecessary computation here, especially on low-end devices.
I don't know how encodings and grapheme work very well so this needs a close look.
- https://github.com/bluesky-social/atproto/pull/2817/commits/0d6b54d09a5674bd689d3b7d7df14d5448a541ec
- https://github.com/bluesky-social/atproto/pull/2817/commits/7b973823bad0759970307d95f278e5cb27c02874
- https://github.com/bluesky-social/atproto/pull/2817/commits/8b0bdcb0c1ebc03dc7118f2135ca8d09eacd0611?w=1
This was showing up in a profile for switching tabs with 6x throttling. (Note this is a DEV profile so in PROD its % would be higher compared to other things around it.)
It doesn't show up.
> Add fast path skipping grapheme counting

- packages/api/tests/atp-agent.test.ts
- Change tests to use AtpClient instead of the deprecated BskyClient
> Follow-on cleanup after #2483

- packages/oauth/oauth-client/README.md
- packages/pds/src/mailer/templates/confirm-email.hbs
- packages/pds/src/mailer/templates/delete-account.hbs
- packages/pds/src/mailer/templates/plc-operation.hbs
- packages/pds/src/mailer/templates/reset-password.hbs
- packages/pds/src/mailer/templates/update-email.hbs
Ensures codes are uppercased, since that's what our app expects. We could also loosen those regexes to allow lowercase i.e. `[A-z]` but let's just stick to the script.
Fixes #2825 and https://github.com/bluesky-social/social-app/issues/5448
> Use uppercase 2fa codes in email templates

- .changeset/dirty-foxes-bow.md
- .changeset/happy-islands-wash.md
- packages/common-web/src/util.ts
- packages/common/src/streams.ts
- packages/pds/src/config/config.ts
- packages/pds/src/config/env.ts
- packages/pds/src/pipethrough.ts
- packages/pds/tests/proxied/read-after-write.test.ts
This enables PDSs to serve un-compressed responses when the request does not contain `accept-encoding`. This is done by specifying `identity` as preferred `content-encoding` when performing the upstream request. If the upstream server did not respect our priority list, the PDS will decode the response before serving it.
If, at some point we would like to reduce the bandwidth (at the cost of increased CPU usage on both the PDS and AppView(s)), we can set `PDS_PROXY_PREFER_COMPRESSED=true`. This will cause the PDS to ask for compressed responses with higher priority than uncompressed (`identity`) payloads.
> Default to unencoded responses

- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
We had weird divergent behaviour if you asked for limit=1 or not where limit=1 would *only* return the pinned post. Since we ask for limit=1 to check to see if there are new posts, we should instead return the pin and the top post here so we can check both
> Don't replace first post with pin if limit=1

- .changeset/wicked-items-peel.md
- packages/oauth/oauth-provider/src/assets/app/components/accept-form.tsx
- packages/oauth/oauth-provider/src/assets/app/components/client-name.tsx
Reported here: https://github.com/bluesky-social/atproto/discussions/2656#discussioncomment-10767247
> Do not display the client_name of untrusted clients

- .changeset/long-rings-invent.md
- packages/api/src/moderation/subjects/post.ts
We had a report a while back that if a link card was attached along with a quoted post, mute words didn't apply to the link card. This fixes that.
> Add check for external media within RecordWithMedia

- packages/oauth/oauth-client-node/README.md
In the `@atproto/oauth-client-node` README code examples, this:
1. adds missing imports,
2. fixes the `NodeOAuthClient` import (because `NodeOAuthClientOptions` is just a type, not a constructor),
3. and adds `async` to some functions in the options, so they actually return `Promise`s.
> Fix wrong imports in oauth-client-node README

- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/src/util/uris.ts
- packages/bsky/src/views/index.ts
Looks like a client or bug may have been responsible for some bad pinned post values on profiles, causing some responses to be invalid.  This should set things straight while it gets worked out.
> Appview: temp fix for bad pinned post values

- .changeset/thirty-llamas-pay.md
- packages/sync/src/firehose/index.ts
If there are no relevant ops to process, then avoid parsing the commit, resolving the key, and verifying any claims
Closes https://github.com/bluesky-social/atproto/issues/2900
> @atproto/sync: avoid parsing commits with no relevant ops

- packages/pds/src/api/com/atproto/identity/updateHandle.ts
If a user's DID is not did:plc, then resolve the DID to ensure that they set their handle correctly & track handle update
> Support alternate did methods in update handle

- .changeset/flat-bees-argue.md
- lexicons/tools/ozone/moderation/queryEvents.json
- lexicons/tools/ozone/moderation/queryStatuses.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/tools/ozone/moderation/queryEvents.ts
- packages/api/src/client/types/tools/ozone/moderation/queryStatuses.ts
- packages/ozone/src/api/moderation/queryEvents.ts
- packages/ozone/src/api/moderation/queryStatuses.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/queryEvents.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/queryStatuses.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/tests/moderation-events.test.ts
- packages/ozone/tests/moderation-statuses.test.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/queryEvents.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/queryStatuses.ts
These new params allows ozone api consumers to only listen for 
- account events or record events
- certain collection events
along with being able to
- process only account queue or record queue
- process queue for certain collections only
> :sparkles: Add collection and subjectType filters to queryEvents and queryStatuses

- lexicons/com/atproto/admin/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/admin/defs.ts
- packages/api/src/client/types/tools/ozone/moderation/queryEvents.ts
- packages/api/src/client/types/tools/ozone/moderation/queryStatuses.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/admin/defs.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/com/atproto/admin/defs.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/queryEvents.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/queryStatuses.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/admin/defs.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/queryEvents.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/queryStatuses.ts
This is a relatively freeform field for attaching additional arbitrary threat signatures to a given admin view
> Add threat signatures to admin view

- .changeset/fluffy-baboons-flash.md
- lexicons/app/bsky/unspecced/getConfig.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/unspecced/getConfig.ts
- packages/bsky/src/api/app/bsky/unspecced/getConfig.ts
- packages/bsky/src/api/index.ts
- packages/bsky/src/config.ts
- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/unspecced/getConfig.ts
- packages/ozone/src/lexicon/index.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/unspecced/getConfig.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/unspecced/getConfig.ts
Adding `app.bsky.unspecced.getConfig`, which provides unspecced runtime configuration to the client.
> Add app.bsky.unspecced.getConfig endpoint

- .changeset/swift-sheep-confess.md
- packages/api/src/rich-text/rich-text.ts
- packages/api/tests/rich-text.test.ts
Negative-length facets cause text to be duplicated for whatever reason. Fixed by filtering out facets where `byteStart` is larger than `byteEnd`. Zero-length facets are still allowed.
A new test case was added to catch this:
> Filter out invalid facets in RichText

- packages/bsky/src/api/app/bsky/feed/getFeed.ts
We passed the limit in the feedgen call, but since they are not guaranteed to honor it, we were subject to hydrating a large number of posts if the feedgen didn't respect pagination. We were applying the limit again in the presentation, but hydration had already happened at that point.
Now we apply the limit + some margin right after fetching from the feedgen. The margin is added because some posts might be removed during filtering, so we should usually still have enough to fill a page even after filtering.
If the feed gen misbehaves (returning way more posts than the limit) and filtering doesn't remove enough of them, our pages will be larger than the limit. I figure it is better to return the page with more items in this case to keep the last result in sync with the cursor returned.
I …
> Enforce feed limit before hydration

- services/bsky/Dockerfile
Adds the Node flag `--heapsnapshot-signal=SIGUSR2` so we can take heap snapshots.
> Add --heapsnapshot-signal=SIGUSR2 to bsky service

- .changeset/funny-queens-lick.md
- packages/pds/src/api/app/bsky/feed/getPostThread.ts
- packages/pds/tests/proxied/read-after-write.test.ts
Previously, `getPostThread` read-after-write handling was not taking `at://<handle>/...` URIs into account. This resulted in the PDS returning 404 for post thread query whenever relay is lagging, which resulted in a confusing UX in the app (the post would show up but clicking into it would show 404). This should fix that.
See two additions to tests. One of those worked before, the other one failed. Now both work.
> Fix optimistic getPostThread for URIs with handle

- packages/bsky/package.json
- packages/pds/package.json
- pnpm-lock.yaml
Upgrades sharp from `0.32.6` to `0.33.5`. This brings a lot of improvements, notably [libvips 8.15](https://www.libvips.org/2023/10/10/What's-new-in-8.15.html), which brings quite a lot of performance improvements. It also includes prebuilt binaries of libvips and sharp, which is helpful for cases when there is no support for compiling vips/sharp from source.
I've run the tests in `packages/bsky/tests/image/sharp.test.ts`, and all of them pass as expected.
> bsky,pds: sharp 0.32.6 -> 0.33.5

- .changeset/dirty-trees-whisper.md
- packages/api/src/rich-text/rich-text.ts
There's no great reason for these to be a sequential client-server waterfall, let's grab them all together.
Ref: https://bsky.app/profile/aaronmcadam.com/post/3laevl2d33y2h
> Resolve facets in parallel

- lexicons/com/atproto/repo/applyWrites.json
- lexicons/com/atproto/repo/createRecord.json
- lexicons/com/atproto/repo/putRecord.json
- packages/api/src/client/lexicons.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/lexicons.ts
This is to match the rkey specification.
What we should probably really be doing is use the string format restriction (format: `record-key`), which is defined in the specs, but i'm not sure if we have codegen support for yet.
> com.atproto lexicions: longer rkey length

- packages/pds/example.env
This has changed about a year ago, but this example was missed.
Fixes: d664b51c6490ebed3557c002ad912cfa828aef56
> `PDS_BSKY_APP_VIEW_ENDPOINT` is now `PDS_BSKY_APP_VIEW_URL`

- .changeset/fuzzy-wolves-speak.md
- packages/pds/src/read-after-write/viewer.ts
Some folks noticed during the outage earlier today that quoteCount wasn't returned on responses for recently made posts, since those responses were served directly by the PDS via RAW and not the App View (bc outage). This was causing some rendering errors.
So this PR ensures that if we fall back to RAW, the response matches what's expected from `getPostThread`. Basically, `quoteCount` should not be `undefined`.
> Ensure RAW returns empty quoteCount

- packages/bsky/src/hydration/label.ts
Needs review labels are currently actioned on the server for `redact` labelers. Do not send these down to client as clients don't have proper logic for them yet
> Filter needs-review labels

- .changeset/fluffy-otters-study.md
- lexicons/app/bsky/actor/defs.json
- packages/api/src/agent.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/defs.ts
- packages/api/tests/atp-agent.test.ts
- packages/api/tests/moderation-prefs.test.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/actor/defs.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
Adds a new `hotness` thread sort option and changes the agent to return it as a default if not specified. Currently it's up to the client to interpret it, we'll add a simple implementation into the social-app that others can use. In the future, we might want to move that logic to the server but we're not well-prepared for that change right now.
> Add hotness as a default thread sort option

- packages/bsky/src/api/app/bsky/actor/getProfile.ts
- packages/bsky/src/auth-verifier.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/tests/views/labels-takedown.test.ts
Takendown blocklists were taking effect on `actor.getProfile`, but properly not taking effect other places in the app.  This ensures the behavior is consistent on `actor.getProfile`.
> Appview: fix takendown blocklist application on `actor.getProfile`

- packages/bsky/src/api/app/bsky/feed/getLikes.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/tests/views/likes.test.ts
This removes 3rd-party blocks from `getLikes`.
So a viewer seeing the likes in a post will not see the likes by users the viewer blocked and by users the post author blocked.
> Remove author blocks from getLikes

- lexicons/tools/ozone/moderation/queryEvents.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/tools/ozone/moderation/queryEvents.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/queryEvents.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/tests/__snapshots__/moderation-events.test.ts.snap
- packages/ozone/tests/moderation-events.test.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/queryEvents.ts
This PR adds a special character `||` in the comment param for `tools.ozone.moderation.queryEvents` endpoint which allows moderators to query events with certain keywords that are used with the `OR` operator.
> :sparkles: Allow querying events by multiple keywords using OR condition

- .changeset/new-poems-scream.md
- lexicons/tools/ozone/moderation/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/tools/ozone/moderation/defs.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/ozone/src/api/moderation/emitEvent.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/defs.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/src/mod-service/views.ts
- packages/ozone/tests/ack-all-subjects-of-account.test.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/defs.ts
This PR brings the same flag as takedown event from here https://github.com/bluesky-social/atproto/pull/2793 for the acknowledge event. This helps clean up moderation queue of unnecessary subjects that won't require individual reviews if the author's account is being acked.
> ✨ Optionally ack all open subjects from the author with acknowledge event

- packages/ozone/src/api/moderation/emitEvent.ts
- packages/ozone/tests/protected-tags.test.ts
due to how auth object is set up, for each level of access, all lower level access is also enabled. so when each level of role check passes, lower level access can be assumed to pass.
this PR fixes the redundant role check and refactors the tag level check into a separate function.
> :bug: Fix auth level check for protected tags

- packages/crypto/src/multibase.ts
The error message was printing the `Uint8Array` instead of the name of the unsupported encoding.
> fix(crypto): fix error message of `bytesToMultibase`

- packages/bsky/src/hydration/actor.ts
Correctly validate profile records so that we don't serve the client broken views. 
Note: this is what we do for all other record types, I think we just didn't do it for profiles because they're wrapped in the actor type and are structured a bit differently
> Validate profile records for views

- packages/bsky/src/api/app/bsky/unspecced/getTrendingTopics.ts
didn't spread params here, so missing the `limit` in the request.
> fix missing limit param in getTrendingTopics

- lexicons/tools/ozone/moderation/queryStatuses.json
- packages/api/src/client/lexicons.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/tests/moderation-status-tags.test.ts
- packages/pds/src/lexicon/lexicons.ts
This PR adds a special separator character in the `tags` filter param array on `tools.ozone.moderation.queryStatuses` endpoint which allows moderators to filter queue items for multiple tags using the AND operator instead of the default OR operator which is applied between different items in the array.
So, currently, there is no way for a moderator to find all subjects that have both `embed:image` and `lang:ja` tags because passing `tags: ['lang:ja', 'embed:image']` will return all items with either of the tags. This PR makes way for us to apply the expected filter using the syntax `tags: ['lang:ja && embed:image']`
> :sparkles: Add && separator for tags filter param on queryStatuses endpoint

- packages/ozone/src/api/moderation/emitEvent.ts
- packages/ozone/src/api/report/createReport.ts
- packages/ozone/src/tag-service/index.ts
- packages/ozone/src/tag-service/util.ts
- packages/ozone/tests/__snapshots__/get-record.test.ts.snap
- packages/ozone/tests/__snapshots__/get-records.test.ts.snap
- packages/ozone/tests/__snapshots__/get-repo.test.ts.snap
- packages/ozone/tests/__snapshots__/get-repos.test.ts.snap
- packages/ozone/tests/__snapshots__/moderation-events.test.ts.snap
- packages/ozone/tests/__snapshots__/moderation-statuses.test.ts.snap
- packages/ozone/tests/__snapshots__/moderation.test.ts.snap
- packages/ozone/tests/content-tagger.test.ts
- packages/ozone/tests/report-muting.test.ts
- packages/pds/tests/proxied/__snapshots__/admin.test.ts.snap
This PR adds report reason tags to subjects which enables moderators to filter queue items based on the subjects' report types.
> :sparkles: Add subject tags with report type

- .changeset/wet-bottles-travel.md
- packages/bsky/src/lexicon/index.ts
- packages/lex-cli/src/codegen/server.ts
- packages/ozone/src/lexicon/index.ts
- packages/pds/src/lexicon/index.ts
This matches the types in `xrpc-server` and was just an oversight in codegen
> Nullable ratelimit calcKey

- .changeset/metal-falcons-fail.md
- lexicons/tools/ozone/moderation/queryStatuses.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/tools/ozone/moderation/queryStatuses.ts
- packages/ozone/src/api/moderation/queryStatuses.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/queryStatuses.ts
- packages/ozone/src/mod-service/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/queryStatuses.ts
Up until now, we have been doing subject to queue mapping entirely on the client which is super inefficient and results in a LOT of load on the server and the client. This PR simply moves the same client side logic into the DB query.
This is the client side implementation of the queue allocation logic https://github.com/bluesky-social/ozone/blob/main/app/reports/page-content.tsx#L435
> :sparkles: Apply queue filter on database query when fetching subjects

- packages/bsky/src/lexicon/index.ts
- packages/ozone/src/lexicon/index.ts
- packages/pds/src/lexicon/index.ts
There were some recent codegen changes that were unintentionally clobbered in #3294, this just reverts those changes.
> Fix clobbered codegen changes

- .changeset/smooth-steaks-suffer.md
- lexicons/tools/ozone/moderation/defs.json
- lexicons/tools/ozone/moderation/queryEvents.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/tools/ozone/moderation/defs.ts
- packages/api/src/client/types/tools/ozone/moderation/queryEvents.ts
- packages/bsky/src/lexicon/index.ts
- packages/dev-env/src/moderator-client.ts
- packages/ozone/src/api/moderation/queryEvents.ts
- packages/ozone/src/lexicon/index.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/defs.ts
- packages/ozone/src/lexicon/types/tools/ozone/moderation/queryEvents.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/src/mod-service/views.ts
- packages/ozone/src/setting/constants.ts
- packages/ozone/src/setting/validators.ts
- packages/ozone/tests/takedown.test.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/defs.ts
- packages/pds/src/lexicon/types/tools/ozone/moderation/queryEvents.ts
This PR adds an optional `policy` property to all takedown events that allows an arbitrary string value and allows moderators to query for all takedowns by specifying a `policy` param through th `queryEvents` endpoint.
> :sparkles: Add a policy property to takedown events

- packages/bsky/src/api/blob-resolver.ts
Followup to changes in #3177, ensure we still follow redirects during blob resolution.
> Appview: permit redirects during blob resolution

- .changeset/silver-birds-run.md
- packages/internal/fetch-node/src/unicast.ts
The unicast check in here was unintentionally only passing through domains that are not themselves public suffix domains.  We want to use the logic from the `psl` package to check that the domain is valid and on a public TLD, but we did not want to omit domains on the PSL such as `s3-us-east-2.amazonaws.com` or `github.io`.
Some details here: https://github.com/lupomontero/psl/issues/258
Should resolve @snarfed's issue here: https://github.com/bluesky-social/atproto/pull/3370#issuecomment-2596713118
> fetch-node: ensure unicast checks allow psl domains

- .changeset/young-balloons-check.md
- packages/oauth/oauth-provider/src/dpop/dpop-manager.ts
- packages/oauth/oauth-provider/src/lib/http/router.ts
The following [issue](https://github.com/bluesky-social/atproto/issues/3410#issuecomment-2602138079) showed that the error message can contain `Authorization server requires nonce in DPoP proof` when a `nonce` is actually present in the proof.
This change uses a distinct error message in that particular case.
> Improve error description in case invalid DPoP nonce is used

- .changeset/new-owls-applaud.md
- packages/api/src/atp-agent.ts
- packages/api/src/types.ts
https://github.com/bluesky-social/atproto/pull/3251 added a new param, `allowTakendown`, to createSession. However, the API package doesn't expose it directly, instead providing the `login` method. We need to add a new optional parameter to `login` which just gets passed through.
> Allow passing `allowTakendown` to createSession

- .changeset/eighty-eggs-nail.md
- .changeset/quiet-geese-begin.md
- .changeset/weak-jobs-serve.md
- packages/pds/src/api/com/atproto/identity/updateHandle.ts
- packages/pds/src/index.ts
- packages/xrpc-server/src/server.ts
- packages/xrpc-server/src/types.ts
Changes:
- `xrpc-server`: add a new `errorParser` option to the `XRPCServer` constructor, allowing to properly convert unknwon erros to `XRPCError`
- `pds`: sets a custom `errorParser` so that `PlcClientError` are not rendered as generic `{ "error": "InvalidRequest", "message": "Request failed with status code 400"}` errors
> Improve error reporting in case of failed PLC update operation

- packages/pds/src/mailer/templates/confirm-email.hbs
Depends on https://github.com/bluesky-social/social-app/pull/5554
The above PR was merged in early October, which means the app's link handling is ready to go. But in testing just now, I noticed another bug, so we should wait on this until this commit is merged and released to production https://github.com/bluesky-social/social-app/pull/7416.
> Update confirm-email template

- packages/bsky/src/api/app/bsky/feed/getFeed.ts
- packages/bsky/src/api/blob-resolver.ts
- packages/bsky/src/api/util.ts
Appivew trying to be a friendly netizen.  In particular, some servers reject requests without a user-agent, which can impact the appview's ability to resolve blobs.
> Appview: add user-agent for feeds and resolving blobs

- .changeset/gorgeous-lies-warn.md
- .changeset/lovely-news-prove.md
- packages/did/jest.config.js
- packages/did/package.json
- packages/did/src/methods/plc.ts
- packages/did/src/methods/web.ts
- packages/did/tests/methods/plc.test.ts
- packages/did/tests/methods/web.test.ts
- packages/internal/did-resolver/src/did-resolver-base.ts
- packages/internal/did-resolver/src/methods/plc.ts
- packages/internal/did-resolver/src/methods/web.ts
- pnpm-lock.yaml
Current implementation does not properly encode/decode did webs as per spec:
https://w3c-ccg.github.io/did-method-web/#read-resolve
> Fix did:web encoding/decoding

- .changeset/three-papayas-begin.md
- packages/common/src/ipld-multi.ts
- packages/common/tests/ipld-multi.test.ts
`cbor-x` decodes `uint64`s as bigints even if they are safe to represent as javascript numbers (less than `2^57-1`). 
This was causing unnecessary validation errors in lexicon.
Fixes https://github.com/bluesky-social/atproto/issues/3479
> CBOR: parse safe uint64 as number

- .changeset/tame-cobras-lick.md
- lexicons/app/bsky/actor/defs.json
- lexicons/app/bsky/feed/postgate.json
- lexicons/app/bsky/feed/threadgate.json
- packages/api/src/agent.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/actor/defs.ts
- packages/api/src/client/types/app/bsky/feed/postgate.ts
- packages/api/src/client/types/app/bsky/feed/threadgate.ts
- packages/api/src/types.ts
- packages/api/tests/atp-agent.test.ts
- packages/api/tests/moderation-prefs.test.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/actor/defs.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/postgate.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/threadgate.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/actor/defs.ts
- packages/ozone/src/lexicon/types/app/bsky/feed/postgate.ts
- packages/ozone/src/lexicon/types/app/bsky/feed/threadgate.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/actor/defs.ts
- packages/pds/src/lexicon/types/app/bsky/feed/postgate.ts
- packages/pds/src/lexicon/types/app/bsky/feed/threadgate.ts
Introduces a new preferences object whereby the user can specify their preferred default threadgate/postgate rules. This data will be used to pre-fill their post interaction settings when creating new posts. It will not apply to previously existing posts.
```ts
agent.setPostInteractionSettings({
threadgateAllowRules: AppBskyFeedThreadgate.Record['allow']
postgateEmbeddingRules: AppBskyFeedPostgate.Record['embeddingRules']
})
```
I also added some clarifying descriptions to the lexicons so that they output to the types. The handling around these is a little different, and unclear. Main thing: `threadgate['allow']` being set to `undefined` means "no rules specified, anyone can reply" and `[]` means "no _allow_ rules were added by the user, no one can reply". This is some historical baggage …
> Add `setPostInteractionSettings` and related prefs

- packages/bsky/src/api/app/bsky/feed/getQuotes.ts
- packages/bsky/src/api/app/bsky/notification/listNotifications.ts
- packages/bsky/src/views/index.ts
- packages/bsky/tests/views/labels-needs-review.test.ts
These labels previously only applied at the account level.  This provides more granular application at the record level.
> Appview: apply needs-review to individual records

- packages/api/src/atp-agent.ts
Although the documentation does not explicitly state it, `com.atproto.server.deleteSession`  appears to require a refreshJwt in the Authorization header instead of an accessJwt.
https://docs.bsky.app/docs/api/com-atproto-server-delete-session
When I actually executed the API, I received a 400 error when using the accessJwt.
```bash
$ curl --silent -X POST -H "Content-Type: application/json" https://bsky.social/xrpc/com.atproto.server.createSession -d "{\"identifier\":\"$ID\",\"password\":\"$PASS\"}" | jq "{accessJwt, refreshJwt}"
{
"accessJwt": "...",
"refreshJwt": "..."
}
$ curl --silent -X POST -H "Authorization: Bearer $ACCESS" https://bsky.social/xrpc/com.atproto.server.deleteSession
{"error":"InvalidToken","message":"Invalid token type"}
$ curl --silent -X POST -H "Authorization: …
```
> fix(api): pass refreshJwt to `deleteSession` on `logout()`

- .changeset/yellow-cows-impress.md
- packages/oauth/oauth-provider/src/lib/util/time.ts
Current implementation of `constantTime` allows to deduce the time that was actually spent in that function. This fixes that issue.
> Properly compute sleep time in contantTime util

- .changeset/brown-eggs-rhyme.md
- packages/oauth/oauth-provider/src/device/device-manager.ts
- packages/oauth/oauth-provider/src/lib/http/request.ts
Small follow up on https://github.com/bluesky-social/atproto/pull/3525 that makes the exposed types in the hooks more convenient to work with.
> Mark "userAgent" as optional in `RequestMetadata`

- .changeset/slimy-trainers-tease.md
- lexicons/com/atproto/sync/listReposByCollection.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/sync/listReposByCollection.ts
- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/sync/listReposByCollection.ts
- packages/ozone/src/lexicon/index.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/com/atproto/sync/listReposByCollection.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/sync/listReposByCollection.ts
Pairs with: https://github.com/bluesky-social/indigo/pull/929
Have not run codegen in this repo; usually do that just before merge (after approval).
There was some back and forth on whether we should return array-of-objects or just array-of-strings (DIDs). I think it is good to have this more consistent with `listRepos`, which returns array-of-objects.
@brianolson had a minimum bound on the `limit` parameter (50). For consistency with other endpoints, I made the Lexicon minimum here 1.
This is just the `listReposByCollection` endpoint; I didn't do a Lexicon for `com.atproto.sync.countReposByCollection`.
> com.atproto.sync.listReposByCollection Lexicon, for collections directory

- .vscode/extensions.json
- .vscode/settings.json
This adds a local `settings` for VSCode that includes only defaults that make sense to use for everyone working in this project with VSCode.
The goal is *not* to impose a particular setup to contributors besides the rules imposed by our linting & code style.
> Add vscode settings and recommended extensions

- .changeset/perfect-jars-act.md
- lexicons/com/atproto/repo/applyWrites.json
- lexicons/com/atproto/repo/createRecord.json
- lexicons/com/atproto/repo/defs.json
- lexicons/com/atproto/repo/deleteRecord.json
- lexicons/com/atproto/repo/getRecord.json
- lexicons/com/atproto/repo/putRecord.json
- lexicons/com/atproto/sync/getLatestCommit.json
- lexicons/com/atproto/sync/getRecord.json
- lexicons/com/atproto/sync/getRepo.json
- lexicons/com/atproto/sync/getRepoStatus.json
- lexicons/com/atproto/sync/listBlobs.json
- lexicons/com/atproto/sync/listRepos.json
- lexicons/com/atproto/sync/subscribeRepos.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/repo/applyWrites.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/repo/applyWrites.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/com/atproto/repo/applyWrites.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/repo/applyWrites.ts
- packages/pds/tests/crud.test.ts
Depends on: https://github.com/bluesky-social/atproto/pull/2377
~We'd probably want to hold off on actually merging this until we've done some dev comms and let the specs and library support PRs sink in.~
Needs codegen.
> lexicons: use 'tid' and 'record-key' formats in sync+repo lexicons

- .changeset/good-dryers-poke.md
- .github/workflows/build-and-push-pds-ghcr.yaml
- packages/pds/src/api/com/atproto/repo/applyWrites.ts
- packages/pds/src/api/com/atproto/repo/createRecord.ts
- packages/pds/src/api/com/atproto/repo/deleteRecord.ts
- packages/pds/src/api/com/atproto/repo/putRecord.ts
Some commits are ending up out-of-order on a PDS's firehose. For instance commits `A->B->C` may be emitted in the order `A->C->B`.
This is because the sequencer database is a separate database from the user's actor store. While transactions to a user's repository are forced to be done serially by sqlite, the sequencer does not enforce that serialization. We rely on the fact that we send the event to the sequencer DB _immediately_ after processing the write in the user's repository. Unfortunately, it seems that events can end up getting processed by the sequencer out-of-order (especially when under high load).
To ensure that events are added to the sequencer in the same order that they are processed in the repository, we sequence the commit prior to commiting the transaction on the actor …
> Move sequenceCommit into actor store transaction

- .changeset/orange-chairs-act.md
- lexicons/com/atproto/repo/listRecords.json
- lexicons/com/atproto/sync/getRecord.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/repo/listRecords.ts
- packages/api/src/client/types/com/atproto/sync/getRecord.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/com/atproto/repo/listRecords.ts
- packages/ozone/src/lexicon/types/com/atproto/sync/getRecord.ts
- packages/pds/src/api/com/atproto/repo/listRecords.ts
- packages/pds/src/api/com/atproto/sync/getRecord.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/repo/listRecords.ts
- packages/pds/src/lexicon/types/com/atproto/sync/getRecord.ts
Part of splitting up https://github.com/bluesky-social/atproto/pull/2376 in to smaller chunks for easier merging.
These have been marked deprecated for a long time.
Removes from client and API-side at the same time. These are fairly low-level and not used by, eg, the app.
> remove deprecated sync fields

- .changeset/lovely-files-cross.md
- .changeset/six-fireants-hammer.md
- lexicons/app/bsky/labeler/defs.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/labeler/defs.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/labeler/defs.ts
- packages/bsky/src/views/index.ts
- packages/bsky/tests/views/__snapshots__/labeler-service.test.ts.snap
- packages/bsky/tests/views/labeler-service.test.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/labeler/defs.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/labeler/defs.ts
Stacked on #3521
This PR passes through the new labeler service record properties on the `LabelerViewDetailed`. We _could_ return the entire record on the detailed view, but we already pull out `policies` from the record, so I followed that pattern here.
> [APP-1072] Support labeler declaration fields on app view responses

- packages/crypto/tests/random.test.ts
This test depends on random number generation and sometimes it causes builds to fail. This doesn't solve the underlying issue, it just makes those failures much rarer.
Other options:
1. remove the test, but I can see how it is useful to at least catch obvious mistakes introduced by a change.
2. use some random sequence that we can control from an initial seed that doesn't vary. So we would generate a sequence of values we know doesn't break the tests, and it would still work as a safeguard against obvious mistakes introduced by a change.
> Make random test fail less often

- .changeset/selfish-suns-melt.md
- lexicons/app/bsky/embed/video.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/embed/video.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/embed/video.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/embed/video.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/embed/video.ts
This increases the video upload size limit from 50mb to 100mb in the `app.bsky.embed.video` lexicon.
Technically there is a minor compatibility issue at play here.  The PDS validates blob sizes at write time, so a PDS with an old version of this lexicon may be incompatible with a client assuming it can upload a 100mb video.  This is not expected to pose a major compatibility issue, partly because a. the PDS already de facto limits upload sizes it may accept, b. the user may choose to upload a smaller video (clients generally don't _increase_ original video sizes), and c. PDS distributions are generally updated within a timely manner these days.  Lowering the size limit, on the other hand, would be much more disruptive.
> app.bsky: permit 100mb video uploads

- packages/pds/src/api/com/atproto/admin/updateAccountHandle.ts
- packages/pds/src/handle/index.ts
On `admin.updateAccountHandle`, permit any valid handle as a break glass measure.
> PDS: allow admins to update to any valid handle

- .changeset/empty-apples-learn.md
- packages/sync/package.json
- packages/sync/src/runner/types.ts
- pnpm-lock.yaml
`FirehoseOptions`, the object passed to the `Firehose` constructor, is a union of some specific types and a config object type from `ws`. However, `ws` does not have types, so the union type is completely broken. This can be fixed by adding `@types/ws`
> [!WARNING]
> While it works in the monorepo, I have not verified that this works once packaged up. It would be good to verify that the built package's type are fixed - I don't know what the behaviour of `devDependencies` is in this context
> [sync] Fix types for Firehose options

- .changeset/fifty-hairs-heal.md
- .changeset/green-bobcats-join.md
- .changeset/hot-doors-build.md
- .changeset/light-pans-tap.md
- .changeset/light-seals-watch.md
- packages/oauth/oauth-provider/src/assets/app/backend-data.ts
- packages/oauth/oauth-provider/src/assets/asset.ts
- packages/oauth/oauth-provider/src/assets/assets-middleware.ts
- packages/oauth/oauth-provider/src/assets/index.ts
- packages/oauth/oauth-provider/src/lib/csp/index.ts
- packages/oauth/oauth-provider/src/lib/html/build-document.ts
- packages/oauth/oauth-provider/src/lib/html/html.ts
- packages/oauth/oauth-provider/src/lib/html/util.ts
- packages/oauth/oauth-provider/src/lib/http/response.ts
- packages/oauth/oauth-provider/src/lib/http/security-headers.ts
- packages/oauth/oauth-provider/src/lib/util/type.ts
- packages/oauth/oauth-provider/src/output/backend-data.ts
- packages/oauth/oauth-provider/src/output/output-manager.ts
- packages/oauth/oauth-provider/src/output/send-web-page.ts
- Removes un-necessary CSP directives (making CSP header shorted)
- Optimize backend injected data by generating fewer <script> tags (alloiwng to make CSP header shorter)
- Enables configuration of COEP, CORP & COOP headers in HTML responses
- Fixes issue in HTML class that would cause the output to sometimes be empty (preventing proper generation CSP headers)
- Disables pre-loading of assets that are referenced in the page (they were loaded twice)
- Improve type safety in front-end code by asserting backend vars are injected
Fixes #3625
> Set COEP header to "unsafe-none" when hcaptcha is enabled

- .changeset/afraid-spies-exist.md
- .changeset/great-tips-hide.md
- .changeset/serious-timers-notice.md
- .changeset/slimy-flowers-punch.md
- packages/oauth/oauth-provider/src/account/account-manager.ts
- packages/oauth/oauth-provider/src/account/account-store.ts
- packages/oauth/oauth-provider/src/account/sign-up-input.ts
- packages/oauth/oauth-provider/src/lib/hcaptcha.ts
- packages/oauth/oauth-provider/src/oauth-hooks.ts
- packages/oauth/oauth-provider/src/oauth-provider.ts
This change reworks the way sign-up hooks are triggered:
- The `onSignupAttempt` is now triggered before hcaptcha verification. The reason for an earlier check is to prevent sing-ups based, for example, on ip addresses.
- The `onSignedUp` hook and store's `createAccount` method now receives the hcaptcha verification result, allowing them to store hcaptcha results
- Remove `onSignupHcaptchaResult` hook
This change also fixes hcaptcha score validation
> OAuth: Allow `onSignedUp` hook to access hcaptcha result data

- .changeset/hip-turtles-poke.md
- packages/oauth/oauth-provider/src/lib/hcaptcha.ts
When trying to create an account using the signup flow with hCapctha configured, it currently fails as it expects there to be an error when calling the API.
Body sent in `/oauth/authorize/sign-up`:
```json
{"email":"abc@gmail.com","password":"REDACTED_PASSWORD","inviteCode":"abc@gmail.com","handle":"abc.partall.no","hcaptchaToken":"REDACTED_TOKEN","locale":"en"}
```
Looking at server side logs:
```
type:"InvalidRequestError"
message:"hCaptcha verification failed: [ { "code": "invalid_type", "expected": "array", "received": "undefined", "path": [ "error-codes" ], "message": "Required" } ]"
stack:"InvalidRequestError: hCaptcha verification failed at Function.from (/app/node_modules/.pnpm/@atproto+oauth-provider@0.6.0/node_modules/@atproto/oauth-provider/src/errors/invalid-request-error.ts:30 …
```
> fix(oauth-provider): hCaptcha error codes should be optional

- .changeset/small-melons-lay.md
- packages/api/src/agent.ts
Currently, an `Agent` can be instanciated like so:
```ts
// From a base url `string`
const agent = new Agent('https://base-url.com')
```
```ts
// From a base `URL`
const agent = new Agent(new URL('https://base-url.com'))
```
```ts
// From a `SessionManager` interface, if we need to manipulate the headers
const agent = new Agent({
did,
fetchHandler: (path, init) => {
const url = new URL(path, 'https://base-url.com')
const headers = new Headers(init?.headers)
headers.set('authorization', 'BaSiC ...')
return globalThis.fetch(url, { ...init, headers })
}
})
```
This change adds the possibility to instantiate an `Agent` using a more concise syntax, in particular when trying to add custom HTTP headers:
```ts
const agent = new Agent({
service: 'https://...'
headers: { authorization: 'BaSiC ...' …
```
> Support more ways to instantiate an `Agent`

- .changeset/four-baboons-perform.md
- lexicons/com/atproto/sync/defs.json
- lexicons/com/atproto/sync/getHostStatus.json
- lexicons/com/atproto/sync/listHosts.json
- lexicons/com/atproto/sync/requestCrawl.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/com/atproto/sync/defs.ts
- packages/api/src/client/types/com/atproto/sync/getHostStatus.ts
- packages/api/src/client/types/com/atproto/sync/listHosts.ts
- packages/api/src/client/types/com/atproto/sync/requestCrawl.ts
- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/com/atproto/sync/defs.ts
- packages/bsky/src/lexicon/types/com/atproto/sync/getHostStatus.ts
- packages/bsky/src/lexicon/types/com/atproto/sync/listHosts.ts
- packages/ozone/src/lexicon/index.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/com/atproto/sync/defs.ts
- packages/ozone/src/lexicon/types/com/atproto/sync/getHostStatus.ts
- packages/ozone/src/lexicon/types/com/atproto/sync/listHosts.ts
- packages/ozone/src/lexicon/types/com/atproto/sync/requestCrawl.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/com/atproto/sync/defs.ts
- packages/pds/src/lexicon/types/com/atproto/sync/getHostStatus.ts
- packages/pds/src/lexicon/types/com/atproto/sync/listHosts.ts
- packages/pds/src/lexicon/types/com/atproto/sync/requestCrawl.ts
The immediate use-case here is to help backfill new full-network relay instances, using the host list of an existing relay. It could also help relays stay in sync (eg, periodically pull an updated list of hosts), though this isn't really thought-through for that use case.
A side-effect is making it easier to see how large the network is (number of PDS instances, rough estimate of total accounts). FWIW, both bigsky and the new relay keep per-host counts pre-computed, so this is a simple/cheap single-table queries. That field is also left optional in case other relay implementations don't keep track in the same way.
This introduces a concept of "host status", similar to "account status". My thinking on these:
- `active`: actively connected (or reconnecting)
- `idle`: disconnected due to …
> new host status com.atproto.sync lexicons

- packages/bsky/proto/bsky.proto
- packages/bsky/src/api/app/bsky/feed/getAuthorFeed.ts
- packages/bsky/src/api/app/bsky/notification/getUnreadCount.ts
- packages/bsky/src/api/app/bsky/notification/listNotifications.ts
- packages/bsky/src/api/com/atproto/admin/getAccountInfos.ts
- packages/bsky/src/api/com/atproto/admin/getSubjectStatus.ts
- packages/bsky/src/api/com/atproto/repo/getRecord.ts
- packages/bsky/src/hydration/actor.ts
- packages/bsky/src/hydration/hydrator.ts
- packages/bsky/src/proto/bsky_pb.ts
This applies new cache control behavior to dataplane calls to `GetActors` within the appview.  In short, we want to ensure the user always sees fresh data about themselves.  There are a few other places where we skip the cache, mostly in moderation and admin-specific settings.
> Appview: skip actor cache for viewer

- .changeset/tall-rice-sparkle.md
- .github/workflows/build-and-push-ozone-aws.yaml
- packages/ozone/src/api/well-known.ts
The ozone distribution uses a [metadata endpoint](https://github.com/bluesky-social/ozone/blob/b6ad1e5e9102373b2c2e94dd99b758c0362b54ad/service/index.js#L34-L40) which allows ozone to help get itself configured through the UI.  Moving this up into the ozone backend itself is convenient when the backend and frontend aren't deployed together through the ozone distribution.
We can remove the endpoint from the ozone distribution once these changes are incorporated there.
> Ozone: add metadata endpoint

- .changeset/chilly-rats-wink.md
- packages/oauth/oauth-provider/src/router/assets/send-authorization-page.ts
https://github.com/hCaptcha/react-hcaptcha/issues/259
https://github.com/bluesky-social/atproto/issues/3625
> Use more secure COEP header when hCaptcha is enabled

- lexicons/chat/bsky/actor/defs.json
This PR fixes a small typo in `lexicons/chat/bsky/actor/defs.json`:
`converations`
⬇️
`conversations`
> Fix typo in lexicon

- .changeset/giant-maps-camp.md
- packages/oauth/oauth-provider/src/router/assets/send-authorization-page.ts
Reverts https://github.com/bluesky-social/atproto/pull/3755.  Hcaptcha will also need to provide a COEP header for this to be ready.
> Revert hcaptcha COEP requirements

- packages/ozone/src/mod-service/index.ts
- packages/ozone/tests/get-reporter-stats.test.ts
This fixes a couple issues with ozone reporter stats.  We were counting distinct accounts rather than records for takedowns and labels on `takendownRecordCount` and `labeledRecordCount`.  The join in that query also found all account actions rather than actions particular to the reported record.  In order to make the queries simpler to read I hoisted some logic up so that the queries themselves did not need to contain conditionals.  Lastly, we now handle the case where reporter stats are requested for an empty set of DIDs.
> Ozone: fix correctness and perf issues with reporter stats

- .changeset/great-sheep-hear.md
- packages/bsky/src/hydration/actor.ts
It's currently possible to issue verifications for users without display names (which equates to empty strings). However, we do not currently hydrate verifications without a display name, which means they are not returned to the client, and therefore the verifier cannot revoke and re-issue a verification for the user (after they update their display name).
This PR removes that check so that the client can present the verifier with the option to clear this invalid verification and thereby issue a fresh one.
> Return verification views with empty display name values

- .changeset/empty-stingrays-prove.md
- .changeset/short-seals-fry.md
- packages/common-web/src/types.ts
- packages/lexicon/src/blob-refs.ts
- Avoid double call to `CID.asCID`
- Improve typing of `BlobRef.toJSON()`
> Optimize parsing of `CID` values

- .changeset/gentle-crews-vanish.md
- .changeset/rotten-pillows-beg.md
- .changeset/shiny-horses-play.md
- packages/xrpc-server/src/types.ts
- packages/xrpc/src/types.ts
Currently, the only purpose of `ResponseTypeNames` is to allow mapping `ResponseType` values (number) to the related property name (string).
```ts
ResponseType.Success // 200
ResponseTypeNames[200] = "Success"
```
This is redundant with the `ResponseType` enum itself as an enum can be used in two ways:
```ts
ResponseType.Success // 200
ResponseType[200] // "Success"
```
The only problem with replacing `ResponseTypeNames` with `ResponseType` is the fact that `401` is called `AuthRequired` in `ResponseType` and `AuthenticationRequired` in `ResponseTypeNames`.
By introducing the breaking change of renaming `AuthRequired` to `AuthenticationRequired` in `ResponseType`, we can get rid of the `ResponseTypeNames` object as it becomes completely redundant with the `ResponseType` enum.
There are …
> Small XRPC fixes

- .changeset/smart-socks-destroy.md
- packages/bsky/src/api/health.ts
- packages/bsky/src/data-plane/server/background.ts
- packages/bsky/src/error.ts
- packages/bsky/src/image/server.ts
- packages/ozone/src/api/health.ts
- packages/ozone/src/background.ts
- packages/ozone/src/error.ts
- packages/ozone/src/mod-service/index.ts
- packages/ozone/src/team/index.ts
- packages/pds/src/background.ts
- packages/pds/src/basic-routes.ts
- packages/pds/src/error.ts
- packages/xrpc-server/src/server.ts
- packages/xrpc-server/src/stream/server.ts
- packages/xrpc-server/tests/bodies.test.ts
Pino logger should always be called with a "mixin object" `logger.error({ err })`. Currently, some places are calling `logger.error(err)`. This change fixes that.
> Consistenlty log errors with pino

- LICENSE.txt
- README.md
- package.json
I had this wrong previously; the formal company name does include "Social".
> use legally registered name for company

- .changeset/cyan-fishes-dress.md
- packages/pds/src/account-manager/db/migrations/005-oauth-account-management.ts
A recent PDS migration from #3659 was able to fail under the following conditions:
- an account was deleted from the pds
- the same account previously used the oauth functionality with "remember me" selected.
The issue would arise when a foreign key constraint was tripped loading data into the `account_device` table if it referenced an account that no longer exists.  A check was added into this part of the migration to ensure the foreign key constraint would be met.  All prior steps in the migration were made idempotent, so a migration that previously failed at this step should succeed on the next run.
> pds: fix account management migration, partial failure in some cases

- packages/bsky/src/api/well-known.ts
- packages/ozone/src/api/well-known.ts
Currently, the `did:web` DID documents served by `bsky` and `ozone` don't import the `multikey` context while they use the `Multikey` type. This leads to the DID documents expand to documents with a wrong URI for the `Multikey` type and no `publicKeyMultibase` property at all:
https://json-ld.org/playground/#startTab=tab-expanded&json-ld=https%3A%2F%2Fapi.bsky.app%2F.well-known%2Fdid.json
```jsonc
[{ /* … */
"https://w3id.org/security#verificationMethod": [{
"https://w3id.org/security#controller": [
{
"@id": "did:web:api.bsky.app"
}
],
"@id": "did:web:api.bsky.app#atproto",
"@type": [
"https://api.bsky.app/.well-known/Multikey"
]
}]}]
```
This patch adds the `multikey` context to the service DID documents, so that they can be properly consumed by JSON-LD processors. After this change, the …
> Add `@context` for multikey to service DID documents

- .changeset/lemon-ligers-taste.md
- packages/internal/fetch-node/src/unicast.ts
In the `unicastFetchWrap`, if the `didLookup` is false, the function will throw without canceling the response body, causing a memory leak. This change fixes that.
> Fix potential memory leak

- .changeset/brave-chairs-pull.md
- lexicons/app/bsky/feed/defs.json
- lexicons/app/bsky/feed/getFeedSkeleton.json
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/feed/defs.ts
- packages/api/src/client/types/app/bsky/feed/getFeedSkeleton.ts
- packages/bsky/src/api/app/bsky/feed/getFeed.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/defs.ts
- packages/bsky/src/lexicon/types/app/bsky/feed/getFeedSkeleton.ts
- packages/bsky/tests/__snapshots__/feed-generation.test.ts.snap
- packages/bsky/tests/feed-generation.test.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/feed/defs.ts
- packages/ozone/src/lexicon/types/app/bsky/feed/getFeedSkeleton.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/feed/defs.ts
- packages/pds/src/lexicon/types/app/bsky/feed/getFeedSkeleton.ts
Small PR that adds rec IDs to individual items in feeds to be sent back in `sendInteraction`.
cc @iwsmith
> add `reqId` to interactions

- lexicons/app/bsky/feed/searchPosts.json
- packages/api/src/client/lexicons.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/lexicons.ts
Doing some word-wrangling to phrase this in an provider-neutral way, though the real motivation here is that Bluesky mostly no longer allows public post search.
> lexicons: update searchPosts to indicate it isn't always available publicly

- lexicons/tools/ozone/verification/grantVerifications.json
- packages/api/src/client/lexicons.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/lexicons.ts
Pointed out by this PR https://github.com/bluesky-social/atproto/pull/3805 we were missing the format def for `createdAt` field which can break some codegen tools. The original PR didn't have codegen so created this new PR.
> :bug: Add datetime format in lexicon def for createdAt field on grantVerification input

- .changeset/seven-pans-press.md
- .changeset/ten-tools-exercise.md
- packages/oauth/oauth-client/src/oauth-server-agent.ts
- packages/oauth/oauth-types/src/oauth-authorization-request-parameters.ts
- packages/oauth/oauth-types/src/util.ts
As reported by @tom-sherman our OAuth requests are not using the proper encoding (JSON instead of Form encoded). This fixes that.
Fixes: #3723
> Use Form encoded body instead of JSON for OAuth requests

- .changeset/metal-oranges-sing.md
- .changeset/nasty-knives-kick.md
- .changeset/sweet-ways-allow.md
- .changeset/weak-cycles-speak.md
- package.json
- packages/oauth/jwk/src/jwt.ts
- packages/oauth/oauth-provider/src/dpop/dpop-manager.ts
- packages/oauth/oauth-provider/src/dpop/dpop-proof.ts
- packages/oauth/oauth-provider/src/dpop/dpop-result.ts
- packages/oauth/oauth-provider/src/lib/util/authorization-header.ts
- packages/oauth/oauth-provider/src/lib/util/cast.ts
- packages/oauth/oauth-provider/src/oauth-provider.ts
- packages/oauth/oauth-provider/src/oauth-verifier.ts
- packages/oauth/oauth-provider/src/request/request-manager.ts
- packages/oauth/oauth-provider/src/router/create-oauth-middleware.ts
- packages/oauth/oauth-provider/src/token/token-manager.ts
- packages/oauth/oauth-provider/src/token/verify-token-claims.ts
- packages/pds/src/auth-verifier.ts
- pnpm-lock.yaml
This PR deprecates the use of query & fragment in DPoP "htu" proofs and paves the way for removing support altogether.
This PR also makes the DPoP validation result (`dpopResult`) available in the return value from `authenticateRequest` allowing PDS to log the use of invalid `htu` claims.
Related to: https://github.com/bluesky-social/atproto/issues/3846
Related to: https://github.com/bluesky-social/atproto/commit/36d0d370c24498f74c243ebfb01564e5050c672d (client side fix)
> Deprecate query & fragment in DPoP proof `htu` claim

- .changeset/brave-beers-thank.md
- lexicons/app/bsky/unspecced/getPostThreadOtherV2.json
- lexicons/app/bsky/unspecced/getPostThreadV2.json
- packages/api/src/client/index.ts
- packages/api/src/client/lexicons.ts
- packages/api/src/client/types/app/bsky/unspecced/getPostThreadOtherV2.ts
- packages/api/src/client/types/app/bsky/unspecced/getPostThreadV2.ts
- packages/bsky/src/api/app/bsky/unspecced/getPostThreadOtherV2.ts
- packages/bsky/src/api/app/bsky/unspecced/getPostThreadV2.ts
- packages/bsky/src/api/index.ts
- packages/bsky/src/lexicon/index.ts
- packages/bsky/src/lexicon/lexicons.ts
- packages/bsky/src/lexicon/types/app/bsky/unspecced/getPostThreadOtherV2.ts
- packages/bsky/src/lexicon/types/app/bsky/unspecced/getPostThreadV2.ts
- packages/bsky/src/views/index.ts
- packages/bsky/src/views/threads-v2.ts
- packages/bsky/tests/views/__snapshots__/thread-v2.test.ts.snap
- packages/bsky/tests/views/thread-v2.test.ts
- packages/ozone/src/lexicon/index.ts
- packages/ozone/src/lexicon/lexicons.ts
- packages/ozone/src/lexicon/types/app/bsky/unspecced/getPostThreadOtherV2.ts
- packages/ozone/src/lexicon/types/app/bsky/unspecced/getPostThreadV2.ts
- packages/pds/src/lexicon/index.ts
- packages/pds/src/lexicon/lexicons.ts
- packages/pds/src/lexicon/types/app/bsky/unspecced/getPostThreadOtherV2.ts
- packages/pds/src/lexicon/types/app/bsky/unspecced/getPostThreadV2.ts
These are "other", or "extra" replies, so this PR updates the naming to be more aligned with the API intent.
> Update V2 additional replies naming convention

- .changeset/hot-cobras-attack.md
- packages/xrpc-server/src/server.ts
Currently, the check that asserts that the HTTP client used the right HTTP method is only triggered if there is no `catchall`. This PR introduces a change that will *not* trigger the `catchall` handler for invalid method used with known XRPC methods.
> Return an error if the wrong HTTP verb is used for a known XRPC method

- packages/oauth/oauth-client-node/README.md
I built an [example](https://github.com/kidGodzilla/bsky-oauth-example) and ran into a few small omissions in the examples here, that might make it difficult for a new developer not incredibly familiar with OAuth internals to figure out why their example doesn't work.
My recommended changes to `README.md`:
Each `JoseKey.fromImportable` call requires a key ID (parameter 2). Recommended change:
```
JoseKey.fromImportable(process.env.PRIVATE_KEY_1, 'key1'),
JoseKey.fromImportable(process.env.PRIVATE_KEY_2, 'key2'),
JoseKey.fromImportable(process.env.PRIVATE_KEY_3, 'key3'),
```
Otherwise, it fails silently in testing (localhost) and fails with an error in production (because kid is missing on each key in jwks.json).
---
Scope requires `atproto transition:generic` for the code example that …
> Update README.md to add some missing details in examples

- .changeset/heavy-apes-rush.md
- packages/oauth/oauth-provider/src/client/client-manager.ts
This change removes the restriction of the `redirect_uris` urls to be on the same origin as the client id.
Note that the ATProto spec needs to be adapted together with this PR. See this [PR](https://github.com/bluesky-social/atproto-website/pull/409)
> Allow HTTPS `redirect_uris` from any origin

- .changeset/gold-mice-burn.md
- packages/repo/src/car.ts
See https://bsky.app/profile/did:plc:ragtjsm2j2vknwkz3zp4oxrd/post/3lru2skt7wk2m
Somewhere around Node 16, slice became deprecated and its semantics changed so that it copies into new buffers. On large CAR files which have been read into buffers, this can cause parsing to take a very long time. The `subarray()` method avoids the allocations.
I'd suggest reviewing the entire codebase for this. I did find some other usages, but felt a little gunshy about just doing a search & replace. Uint8Array subarray support is broad so I don't think this creates compat issues in eg web or RN (though RN is a wildcard on this kind of thing).
> Replace slice() with subarray() in car file parsing

- .changeset/orange-boxes-know.md
- packages/api/src/client/index.ts
- packages/lex-cli/src/codegen/client.ts
`put()` was missing from the record utility classes - turns out it was commented out 3 years ago. Not sure why! I uncommented it and updated it with the latest types
> Add put method to record utility classes

- .changeset/sixty-ducks-clean.md
- packages/api/src/util.ts
- packages/api/tests/atp-agent.test.ts
`app.bsky.actor.defs#savedFeed` looks like this - `id` is just specified as a `string`
```json
"savedFeed": {
"type": "object",
"required": ["id", "type", "value", "pinned"],
"properties": {
"id": {
"type": "string"
},
"type": {
"type": "string",
"knownValues": ["feed", "list", "timeline"]
},
"value": {
"type": "string"
},
"pinned": {
"type": "boolean"
}
}
```
Then, the helper methods for updating saved feeds preferences validate the items, which includes ensuring the `id` is a valid TID. Unfortunately, since this constraint is not encoded in the lexicon, other clients have used other values such as UUIDs.
Since we probably shouldn't tighten the lexicon retroactively and the bad data is already out there, I think we should just loosen the constraint. There's no reason this ID actually …
> Loosen unspecced constraint on saved feed IDs

- .changeset/dull-shirts-laugh.md
- packages/pds/tests/file-uploads.test.ts
- packages/xrpc-server/src/util.ts
- packages/xrpc-server/tests/bodies.test.ts
Uploads of json and text content were failing, as xrpc-server would consume the request body by attempting to parse them.  This step could also apply lower text/json-specific size limitations.  This has been addressed by skipping body parsing when the lexicon's input encoding is `*/*`, which indicates that the handler accepts any content-type and will determine how to process the body.
Resolves #4026
> Fix json and text uploads: don't parse bodies with input encoding of */*

- packages/lex-cli/src/codegen/common.ts
fix #4053 
```ts
const nsidToEnum = (nsid: string): string => {
return nsid
.split('.')
.map((word) => word[0].toUpperCase() + word.slice(1))
.join('')
}
```
This method, used before the change, cannot properly handle NSIDs that contain hyphens and causes TypeScript compilation errors.
Use `toTitleCase` instead, which is used elsewhere and handles hyphens correctly.
`nsidToEnum` converts `win.tomo-x.example` to `WinTomo-xExample`, which is invalid as a TypeScript identifier due to the hyphen.
`toTitleCase` converts it to `WinTomoXExample`, which is a valid identifier.
> Fixed a bug in @atproto/lex-cli

- .changeset/nine-plants-peel.md
- packages/pds/src/api/com/atproto/repo/putRecord.ts
- packages/pds/tests/crud.test.ts
Related thread: https://bsky.app/profile/bnewbold.net/post/3lwcopaeubs2y
The check in `putRecord` assumed `repo` is a DID, but it may also be a handle. This PR uses the same logic as before (before OAuth scopes were introduced), and also mirrors the checks in `createRecord`.
Note: It builds, but not yet tested!
> Fix putRecord auth check

- .changeset/grumpy-pots-attend.md
- packages/lexicon/src/types.ts
- packages/lexicon/tests/general.test.ts
Allow unknown fields to be present in lexicon documents
> @atproto/lexicon: relax validation of lexicon documents

- .changeset/shy-cherries-argue.md
- packages/oauth/oauth-client/src/oauth-client.ts
- packages/oauth/oauth-client/src/oauth-server-agent.ts
- packages/oauth/oauth-client/src/types.ts
Previously the callback method assumed a singular `redirect_uris` value, and enforced only performing the callback with the first registered redirect URI (via `exchangeCode` being hardcoded to pick the first value from `redirect_uris`). This change allows passing the actual redirect URI to the `callback` method, much like the `authorize` method supports.
Fixes #4136
**Note:** I have not added support for multiple redirect URIs to `@atproto/oauth-client-browser` since the methods exposed there (`signInCallback` via `init`) does not currently support any additional options besides a `refresh` boolean. `readCallbackParams` would probably need to be modified to "discover" the correct redirect URI for which to use and subsequently pass to the `callback` method.
> Fix #4136: Support multiple redirect URIs in @atproto/oauth-client

- packages/bsky/src/context.ts
- packages/bsky/src/util.ts
I believe the intention of having an empty `atproto-accept-labelers` header is to apply _no_ moderation services to the output. At present however, this doesn't quite work. You can disable any given moderation service, but you must supply at least one, even a fake labeler. The expectation should be:
- No `atproto-accept-labeler` header provided -> Apply the default moderation service
- Supply a header with any moderation service -> Only apply those moderation services
- Supply a header with an empty string as the value -> Apply no moderation services
Outputs:
```
// Passing a DID
{
dids: [ 'did:plc:eotxm3k2kk6ravy6bu3w2e7t' ],
redact: Set(1) { 'did:plc:eotxm3k2kk6ravy6bu3w2e7t' }
}
// Empty but supplied header
{ dids: [], redact: Set(0) {} }
// Non-existent header
null // which will give …
```
> explicitly check for empty string in labelers header

- .changeset/fast-monkeys-punch.md
- packages/api/src/atp-agent.ts
Currently, if `resumeSession` fails with `network-error`, `this.session` gets cleared out. However, that's actually extremely unhelpful and used to be (in a more distant past) one of the causes of "random logouts" in the flagship atproto app, Bluesky.
The official Bluesky client already includes a hack to work around this:
https://github.com/bluesky-social/social-app/blob/7f4e3091f792963114dc8f11e246744b51127bf1/src/state/session/agent.ts#L324-L331
```js
let lastSession = this.sessionManager.session
this.persistSessionHandler = event => {
if (this.sessionManager.session) {
lastSession = this.sessionManager.session
} else if (event === 'network-error') {
// Put it back, we'll try again later.
this.sessionManager.session = lastSession
}
```
If the error is `network-error`, the Bluesky app …
> Restore session on network error
